WITH TEXT_IO;WITH TEXT_IO;WITH INT_NUMBER_IO;PACKAGE DATA_STRUCTURES IS
--{10:}
BUF_SIZE:CONSTANT:=100;MAX_BYTES:CONSTANT:=45000;
MAX_TOKS:CONSTANT:=50000;MAX_NAMES:CONSTANT:=4000;
MAX_TEXTS:CONSTANT:=2000;HASH_SIZE:CONSTANT:=353;
LONGEST_NAME:CONSTANT:=400;LINE_LENGTH:CONSTANT:=72;
OUT_BUF_SIZE:CONSTANT:=144;STACK_SIZE:CONSTANT:=50;
MAX_ID_LENGTH:CONSTANT:=LINE_LENGTH;
UNAMBIG_LENGTH:CONSTANT:=MAX_ID_LENGTH;--{:10}{11:}
TYPE HISTORY_TYPE IS(SPOTLESS,HARMLESS_MESSAGE,ERROR_MESSAGE,
FATAL_MESSAGE);HISTORY:HISTORY_TYPE:=SPOTLESS;--{:11}{12:}
SUBTYPE ASCII_CODE IS INTEGER RANGE 0..127;--{:12}{13:}
SUBTYPE TEXT_CHAR IS CHARACTER;SUBTYPE TEXT_FILE IS TEXT_IO.FILE_TYPE;
--{:13}{14:}
XORD:ARRAY(TEXT_CHAR)OF ASCII_CODE;XCHR:ARRAY(ASCII_CODE)OF TEXT_CHAR;
--{:14}{16:}
AND_SIGN:CONSTANT ASCII_CODE:=8#4#;NOT_SIGN:CONSTANT ASCII_CODE:=8#5#;
SET_ELEMENT_SIGN:CONSTANT ASCII_CODE:=8#6#;
TAB_MARK:CONSTANT ASCII_CODE:=8#11#;
LINE_FEED:CONSTANT ASCII_CODE:=8#12#;
FORM_FEED:CONSTANT ASCII_CODE:=8#14#;
CARRIAGE_RETURN:CONSTANT ASCII_CODE:=8#15#;
RIGHT_ARROW:CONSTANT ASCII_CODE:=8#21#;
BOX_SIGN:CONSTANT ASCII_CODE:=8#22#;
DOUBLE_STAR:CONSTANT ASCII_CODE:=8#23#;
LEFT_LABEL_BRACKET:CONSTANT ASCII_CODE:=8#24#;
RIGHT_LABEL_BRACKET:CONSTANT ASCII_CODE:=8#25#;
LEFT_ARROW:CONSTANT ASCII_CODE:=8#30#;
NOT_EQUAL:CONSTANT ASCII_CODE:=8#32#;
LESS_OR_EQUAL:CONSTANT ASCII_CODE:=8#34#;
GREATER_OR_EQUAL:CONSTANT ASCII_CODE:=8#35#;
EQUIVALENCE_SIGN:CONSTANT ASCII_CODE:=8#36#;
OR_SIGN:CONSTANT ASCII_CODE:=8#37#;--{:16}{22:}
WEB_FILE:TEXT_FILE;CHANGE_FILE:TEXT_FILE;--{:22}{25:}
ADA_FILE:TEXT_FILE;--{:25}{27:}
TYPE BUFFER_TYPE IS ARRAY(INTEGER RANGE<>)OF ASCII_CODE;
SUBTYPE BUFFER_INDEX IS INTEGER RANGE 0..BUF_SIZE;
BUFFER:BUFFER_TYPE(BUFFER_INDEX);--{:27}{30:}
PHASE_ONE:BOOLEAN;--{:30}{35:}
END_OF_ATANGLE:EXCEPTION;--{:35}{38:}
SUBTYPE EIGHT_BITS IS INTEGER RANGE 0..255;
SUBTYPE SIXTEEN_BITS IS INTEGER RANGE 0..65535;--{:38}{39:}
WW:CONSTANT INTEGER:=2;ZZ:CONSTANT INTEGER:=3;
SUBTYPE W_RANGE IS INTEGER RANGE 0..WW-1;
SUBTYPE Z_RANGE IS INTEGER RANGE 0..ZZ-1;
SUBTYPE BYTE_INDEX IS INTEGER RANGE 0..MAX_BYTES;
SUBTYPE TOKEN_INDEX IS INTEGER RANGE 0..MAX_TOKS;
SUBTYPE NAME_INDEX IS INTEGER RANGE 0..MAX_NAMES;
SUBTYPE TEXT_INDEX IS INTEGER RANGE 0..MAX_TEXTS;
TYPE BYTE_MEMORY IS ARRAY(W_RANGE,BYTE_INDEX)OF ASCII_CODE;
--PRAGMA PACK(BYTE_MEMORY);
TYPE TOKEN_MEMORY IS ARRAY(Z_RANGE,TOKEN_INDEX)OF EIGHT_BITS;
--PRAGMA PACK(TOKEN_MEMORY);
TYPE NAME_INFO IS ARRAY(NAME_INDEX)OF SIXTEEN_BITS;
TYPE TOKEN_INFO IS ARRAY(TEXT_INDEX)OF SIXTEEN_BITS;
BYTE_MEM:BYTE_MEMORY;TOK_MEM:TOKEN_MEMORY;BYTE_START:NAME_INFO;
TOK_START:TOKEN_INFO;LINK:NAME_INFO;ILK:NAME_INFO;EQUIV:NAME_INFO;
TEXT_LINK:TOKEN_INFO;--{:39}{40:}
SUBTYPE NAME_POINTER IS NAME_INDEX;NAME_PTR:NAME_POINTER:=1;
BYTE_PTR:ARRAY(W_RANGE)OF BYTE_INDEX:=(OTHERS=>0);--{:40}{42:}
SUBTYPE TEXT_POINTER IS TEXT_INDEX;TEXT_PTR:TEXT_POINTER:=1;
TOK_PTR:ARRAY(Z_RANGE)OF TOKEN_INDEX:=(OTHERS=>0);Z:Z_RANGE:=1 MOD ZZ;
--MAX_TOK_PTR:ARRAY(Z_RANGE)OF TOKEN_INDEX;
--{:42}{44:}
NORMAL:CONSTANT SIXTEEN_BITS:=0;SIMPLE:CONSTANT SIXTEEN_BITS:=1;
PARAMETRIC:CONSTANT SIXTEEN_BITS:=2;--{:44}{45:}
LLINK:NAME_INFO RENAMES LINK;RLINK:NAME_INFO RENAMES ILK;--{:45}{49:}
ID_FIRST:BUFFER_INDEX;ID_LOC:BUFFER_INDEX;
SUBTYPE HASH_INDEX IS INTEGER RANGE 0..HASH_SIZE;
SUBTYPE CHOP_HASH_INDEX IS INTEGER RANGE 0..UNAMBIG_LENGTH;
HASH,CHOP_HASH:ARRAY(HASH_INDEX)OF SIXTEEN_BITS:=(OTHERS=>0);
CHOPPED_ID:ARRAY(CHOP_HASH_INDEX)OF ASCII_CODE;--{:49}{62:}
SUBTYPE LONG_NAME_INDEX IS INTEGER RANGE 0..LONGEST_NAME;
MOD_TEXT:ARRAY(LONG_NAME_INDEX)OF ASCII_CODE;--{:62}{63:}
TYPE COMPARE IS(LESS,EQUAL,GREATER,PREFIX,EXTENSION);--{:63}{70:}
MODULE_FLAG:CONSTANT SIXTEEN_BITS:=MAX_TEXTS;
LAST_UNNAMED:TEXT_POINTER:=0;--{:70}{72:}
PARAM:CONSTANT EIGHT_BITS:=0;VERBATIM:CONSTANT EIGHT_BITS:=2;
FORCE_LINE:CONSTANT EIGHT_BITS:=3;
BEGIN_COMMENT:CONSTANT EIGHT_BITS:=8#11#;
END_COMMENT:CONSTANT EIGHT_BITS:=8#12#;
CHARACTER_TOK:CONSTANT EIGHT_BITS:=8#14#;
ASCII_TOK:CONSTANT EIGHT_BITS:=8#15#;
OUTPUT_TOK:CONSTANT EIGHT_BITS:=8#16#;
DOUBLE_DOT:CONSTANT EIGHT_BITS:=8#40#;JOIN:CONSTANT EIGHT_BITS:=8#177#;
--{:72}{76:}
SUBTYPE MOD_RANGE IS INTEGER RANGE 0..8#27777#;
TYPE OUTPUT_STATE IS RECORD END_FIELD:SIXTEEN_BITS;
BYTE_FIELD:SIXTEEN_BITS;NAME_FIELD:NAME_POINTER;REPL_FIELD:TEXT_POINTER;
MOD_FIELD:MOD_RANGE;END RECORD;CUR_STATE:OUTPUT_STATE;
STACK:ARRAY(1..STACK_SIZE)OF OUTPUT_STATE;
STACK_PTR:INTEGER RANGE 0..STACK_SIZE;
CUR_END:SIXTEEN_BITS RENAMES CUR_STATE.END_FIELD;
CUR_BYTE:SIXTEEN_BITS RENAMES CUR_STATE.BYTE_FIELD;
CUR_NAME:NAME_POINTER RENAMES CUR_STATE.NAME_FIELD;
CUR_REPL:TEXT_POINTER RENAMES CUR_STATE.REPL_FIELD;
CUR_MOD:MOD_RANGE RENAMES CUR_STATE.MOD_FIELD;--{:76}{77:}
ZO:Z_RANGE;--{:77}{79:}
BRACE_LEVEL:EIGHT_BITS;--{:79}{83:}
MODULE_NUMBER:CONSTANT SIXTEEN_BITS:=8#201#;
IDENTIFIER:CONSTANT SIXTEEN_BITS:=8#202#;CUR_VAL:INTEGER;--{:83}{91:}
SUBTYPE OUT_BUFFER_INDEX IS INTEGER RANGE 0..OUT_BUF_SIZE;
OUT_BUF:BUFFER_TYPE(OUT_BUFFER_INDEX);OUT_PTR:OUT_BUFFER_INDEX;
BREAK_PTR:OUT_BUFFER_INDEX;SEMI_PTR:OUT_BUFFER_INDEX;--{:91}{92:}
MISC:CONSTANT EIGHT_BITS:=0;NUM_OR_ID:CONSTANT EIGHT_BITS:=1;
UNBREAKABLE:CONSTANT EIGHT_BITS:=2;OUT_STATE:EIGHT_BITS;
COMMENT_OUTPUT:BOOLEAN;--{:92}{97:}
STR:CONSTANT EIGHT_BITS:=1;IDENT:CONSTANT EIGHT_BITS:=2;
FRAC:CONSTANT EIGHT_BITS:=3;OUT_CONTRIB:BUFFER_TYPE(1..LINE_LENGTH);
--{:97}{107:}
FILE_NAME:STRING(1..80);FN_LENGTH:INTEGER RANGE 1..80;F_LINE:INTEGER;
--{:107}{109:}
SCANNING_BASED_NUMBER:BOOLEAN:=FALSE;--{:109}{116:}
LINE:INTEGER;OTHER_LINE:INTEGER;TEMP_LINE:INTEGER;LIMIT:BUFFER_INDEX;
LOC:BUFFER_INDEX;INPUT_HAS_ENDED:BOOLEAN;CHANGING:BOOLEAN;--{:116}{118:}
CHANGE_BUFFER:BUFFER_TYPE(BUFFER_INDEX);CHANGE_LIMIT:BUFFER_INDEX;
--{:118}{131:}
IGNORE:CONSTANT EIGHT_BITS:=0;CONTROL_TEXT:CONSTANT EIGHT_BITS:=8#203#;
FORMAT:CONSTANT EIGHT_BITS:=8#204#;
DEFINITION:CONSTANT EIGHT_BITS:=8#205#;
BEGIN_ADA:CONSTANT EIGHT_BITS:=8#206#;
MODULE_NAME:CONSTANT EIGHT_BITS:=8#207#;
NEW_MODULE:CONSTANT EIGHT_BITS:=8#210#;--{:131}{136:}
CUR_MODULE:NAME_POINTER;SCANNING_CHARACTER:BOOLEAN:=FALSE;--{:136}{148:}
CUR_REPL_TEXT:TEXT_POINTER;NEXT_CONTROL:SIXTEEN_BITS;--{:148}{156:}
MODULE_COUNT:MOD_RANGE;--{:156}{165:}
OPENED:BOOLEAN:=FALSE;--{:165}{47:}
PROCEDURE PRINT_ID(P:NAME_POINTER);--{:47}{73:}
PROCEDURE STORE_TWO_BYTES(X:SIXTEEN_BITS);--{:73}
END DATA_STRUCTURES;
