WITH TEXT_IO,INT_NUMBER_IO;WITH INPUT_OUTPUT;USE INPUT_OUTPUT;
PACKAGE BODY INPUT_PHASE IS--{119:}
FUNCTION LINES_DONT_MATCH RETURN BOOLEAN IS BEGIN IF CHANGE_LIMIT/=LIMIT
THEN RETURN TRUE;END IF;
IF LIMIT>0 AND THEN CHANGE_BUFFER(0..LIMIT-1)/=BUFFER(0..LIMIT-1)THEN
RETURN TRUE;ELSE RETURN FALSE;END IF;END LINES_DONT_MATCH;--{:119}{120:}
PROCEDURE PRIME_THE_CHANGE_BUFFER IS BEGIN CHANGE_LIMIT:=0;--{121:}
LOOP LINE:=LINE+1;IF NOT INPUT_LN(CHANGE_FILE)THEN RETURN;END IF;
IF LIMIT<2 THEN GOTO CONTINUE;END IF;
IF BUFFER(0)/=64 THEN GOTO CONTINUE;END IF;
IF BUFFER(1)IN 88..90 THEN BUFFER(1):=BUFFER(1)+122-90;END IF;
EXIT WHEN BUFFER(1)=120;IF BUFFER(1)IN 121..122 THEN LOC:=2;
TEXT_IO.NEW_LINE;TEXT_IO.PUT("! Where is the matching @x?");ERROR;
END IF;<<CONTINUE>>NULL;END LOOP--{:121}
;--{122:}
LOOP LINE:=LINE+1;IF NOT INPUT_LN(CHANGE_FILE)THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Change file ended after @x");ERROR;RETURN;END IF;
EXIT WHEN LIMIT>0;END LOOP--{:122}
;--{123:}
CHANGE_LIMIT:=LIMIT;
IF LIMIT>0 THEN CHANGE_BUFFER(0..LIMIT-1):=BUFFER(0..LIMIT-1);END IF
--{:123}
;END PRIME_THE_CHANGE_BUFFER;--{:120}{124:}
PROCEDURE CHECK_CHANGE IS N:INTEGER:=0;
BEGIN IF LINES_DONT_MATCH THEN RETURN;END IF;
LOOP CHANGING:=NOT CHANGING;TEMP_LINE:=OTHER_LINE;OTHER_LINE:=LINE;
LINE:=TEMP_LINE;LINE:=LINE+1;
IF NOT INPUT_LN(CHANGE_FILE)THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Change file ended before @y");ERROR;CHANGE_LIMIT:=0;
CHANGING:=NOT CHANGING;TEMP_LINE:=OTHER_LINE;OTHER_LINE:=LINE;
LINE:=TEMP_LINE;RETURN;END IF;--{125:}
IF(LIMIT>1)AND THEN BUFFER(0)=64 THEN IF BUFFER(1)IN 88..90 THEN BUFFER(
1):=BUFFER(1)+122-90;END IF;
IF(BUFFER(1)=120)OR(BUFFER(1)=122)THEN LOC:=2;TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Where is the matching @y?");ERROR;
ELSIF BUFFER(1)=121 THEN IF N>0 THEN LOC:=2;TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Hmm... ");INT_NUMBER_IO.PUT(N,1);
TEXT_IO.PUT(" of the preceding lines failed to match");ERROR;END IF;
RETURN;END IF;END IF--{:125}
;--{123:}
CHANGE_LIMIT:=LIMIT;
IF LIMIT>0 THEN CHANGE_BUFFER(0..LIMIT-1):=BUFFER(0..LIMIT-1);END IF
--{:123}
;CHANGING:=NOT CHANGING;TEMP_LINE:=OTHER_LINE;OTHER_LINE:=LINE;
LINE:=TEMP_LINE;LINE:=LINE+1;
IF NOT INPUT_LN(WEB_FILE)THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! AWEB file ended during a change");ERROR;
INPUT_HAS_ENDED:=TRUE;RETURN;END IF;IF LINES_DONT_MATCH THEN N:=N+1;
END IF;END LOOP;END CHECK_CHANGE;--{:124}{127:}
PROCEDURE GET_LINE IS BEGIN<<RESTART>>IF CHANGING THEN--{129:}
LINE:=LINE+1;IF NOT INPUT_LN(CHANGE_FILE)THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Change file ended without @z");ERROR;
BUFFER(0..1):=(64,122);LIMIT:=2;END IF;
IF(LIMIT>1)AND THEN(BUFFER(0)=64)THEN IF BUFFER(1)IN 88..90 THEN BUFFER(
1):=BUFFER(1)+122-90;END IF;IF BUFFER(1)IN 120..121 THEN LOC:=2;
TEXT_IO.NEW_LINE;TEXT_IO.PUT("! Where is the matching @z?");ERROR;
ELSIF BUFFER(1)=122 THEN PRIME_THE_CHANGE_BUFFER;CHANGING:=NOT CHANGING;
TEMP_LINE:=OTHER_LINE;OTHER_LINE:=LINE;LINE:=TEMP_LINE;END IF;END IF
--{:129}
;END IF;IF NOT CHANGING THEN--{128:}
LINE:=LINE+1;IF NOT INPUT_LN(WEB_FILE)THEN INPUT_HAS_ENDED:=TRUE;
ELSIF(LIMIT=CHANGE_LIMIT)AND THEN((BUFFER(0)=CHANGE_BUFFER(0))AND THEN(
CHANGE_LIMIT>0))THEN CHECK_CHANGE;END IF--{:128}
;IF CHANGING THEN GOTO RESTART;END IF;END IF;LOC:=0;BUFFER(LIMIT):=32;
END GET_LINE;--{:127}{132:}
FUNCTION CONTROL_CODE(C:ASCII_CODE)RETURN EIGHT_BITS IS BEGIN CASE C IS
WHEN 64=>RETURN 64;WHEN 39=>RETURN ASCII_TOK;
WHEN 126=>RETURN OUTPUT_TOK;WHEN 32!TAB_MARK=>RETURN NEW_MODULE;
WHEN 42=>TEXT_IO.PUT("*");INT_NUMBER_IO.PUT(MODULE_COUNT+1,1);NULL;
RETURN NEW_MODULE;WHEN 68!100=>RETURN DEFINITION;
WHEN 70!102=>RETURN FORMAT;WHEN 123=>RETURN BEGIN_COMMENT;
WHEN 125=>RETURN END_COMMENT;WHEN 65!97=>RETURN BEGIN_ADA;
WHEN 84!116!94!105!73!98!66!114!82!112!80!115!83!46!58=>RETURN
CONTROL_TEXT;WHEN 38=>RETURN JOIN;WHEN 60=>RETURN MODULE_NAME;
WHEN 61=>RETURN VERBATIM;WHEN 92=>RETURN FORCE_LINE;
WHEN OTHERS=>RETURN IGNORE;END CASE;END CONTROL_CODE;--{:132}{133:}
FUNCTION SKIP_AHEAD RETURN EIGHT_BITS IS C:EIGHT_BITS;
BEGIN LOOP IF LOC>LIMIT THEN GET_LINE;
IF INPUT_HAS_ENDED THEN RETURN NEW_MODULE;END IF;END IF;
BUFFER(LIMIT+1):=64;WHILE BUFFER(LOC)/=64 LOOP LOC:=LOC+1;END LOOP;
IF LOC<=LIMIT THEN LOC:=LOC+2;C:=CONTROL_CODE(BUFFER(LOC-1));
IF(C/=IGNORE)OR(BUFFER(LOC-1)=62)THEN RETURN C;END IF;END IF;END LOOP;
END SKIP_AHEAD;--{:133}{134:}
PROCEDURE SKIP_COMMENT IS BAL:EIGHT_BITS:=0;C:ASCII_CODE;
BEGIN LOOP IF LOC>LIMIT THEN GET_LINE;
IF INPUT_HAS_ENDED THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Input ended in mid-comment");ERROR;RETURN;END IF;END IF;
C:=BUFFER(LOC);LOC:=LOC+1;--{135:}
IF C=64 THEN C:=BUFFER(LOC);
IF(C/=32)AND(C/=TAB_MARK)AND(C/=42)AND(C/=122)AND(C/=90)THEN LOC:=LOC+1;
ELSE TEXT_IO.NEW_LINE;TEXT_IO.PUT("! Section ended in mid-comment");
ERROR;LOC:=LOC-1;RETURN;END IF;
ELSIF(C=92)AND(BUFFER(LOC)/=64)THEN LOC:=LOC+1;
ELSIF C=123 THEN BAL:=BAL+1;ELSIF C=125 THEN IF BAL=0 THEN RETURN;
END IF;BAL:=BAL-1;END IF--{:135}
;END LOOP;END SKIP_COMMENT;--{:134}{137:}
FUNCTION GET_NEXT RETURN EIGHT_BITS IS C:EIGHT_BITS;D:EIGHT_BITS;
K:LONG_NAME_INDEX;BEGIN<<RESTART>>IF LOC>LIMIT THEN GET_LINE;
IF INPUT_HAS_ENDED THEN RETURN NEW_MODULE;
ELSIF SCANNING_BASED_NUMBER THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Improper based number, # sign missing");ERROR;
SCANNING_BASED_NUMBER:=FALSE;END IF;END IF;C:=BUFFER(LOC);LOC:=LOC+1;
IF SCANNING_BASED_NUMBER THEN IF C=35 THEN SCANNING_BASED_NUMBER:=FALSE;
END IF;RETURN C;
ELSIF SCANNING_CHARACTER THEN IF C=64 THEN IF BUFFER(LOC)=64 THEN LOC:=
LOC+1;ELSE TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! You should double @ signs in character literals");ERROR;
END IF;END IF;LOC:=LOC+1;SCANNING_CHARACTER:=FALSE;RETURN C;END IF;
CASE C IS WHEN 35=>IF(LOC>1)AND THEN(BUFFER(LOC-2)IN 48..57)THEN
SCANNING_BASED_NUMBER:=TRUE;END IF;RETURN 35;WHEN 65..90!97..122=>
--{139:}
IF(((C=101)OR(C=69))AND(LOC>1))AND THEN((BUFFER(LOC-2)IN 48..57)OR
BUFFER(LOC-2)=35)THEN C:=0;END IF;IF C/=0 THEN LOC:=LOC-1;ID_FIRST:=LOC;
LOOP LOC:=LOC+1;D:=BUFFER(LOC);
EXIT WHEN((D<48)OR((D>57)AND(D<65))OR((D>90)AND(D<97))OR(D>122))AND(D/=95
);END LOOP;IF LOC>ID_FIRST+1 THEN ID_LOC:=LOC;RETURN IDENTIFIER;END IF;
ELSE RETURN 69;END IF--{:139}
;WHEN 64=>--{140:}
C:=CONTROL_CODE(BUFFER(LOC));LOC:=LOC+1;IF C=IGNORE THEN GOTO RESTART;
ELSIF C=MODULE_NAME THEN--{141:}{143:}
K:=0;LOOP IF LOC>LIMIT THEN GET_LINE;
IF INPUT_HAS_ENDED THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Input ended in section name");ERROR;EXIT;END IF;END IF;
D:=BUFFER(LOC);--{144:}
IF D=64 THEN D:=BUFFER(LOC+1);IF D=62 THEN LOC:=LOC+2;EXIT;
ELSIF(D=32)OR(D=TAB_MARK)OR(D=42)THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Section name didn't end");ERROR;EXIT;END IF;K:=K+1;
MOD_TEXT(K):=64;LOC:=LOC+1;END IF--{:144}
;LOC:=LOC+1;IF K<LONGEST_NAME-1 THEN K:=K+1;END IF;
IF(D=32)OR(D=TAB_MARK)THEN D:=32;IF MOD_TEXT(K-1)=32 THEN K:=K-1;END IF;
END IF;MOD_TEXT(K):=D;END LOOP;--{145:}
IF K>=LONGEST_NAME-2 THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Section name too long: ");
FOR J IN INTEGER RANGE 1..25 LOOP TEXT_IO.PUT(XCHR(MOD_TEXT(J)));
END LOOP;TEXT_IO.PUT("...");
IF HISTORY=SPOTLESS THEN HISTORY:=HARMLESS_MESSAGE;END IF;END IF--{:145}
;IF(MOD_TEXT(K)=32)AND(K>0)THEN K:=K-1;END IF--{:143}
;IF(K>3)AND THEN(MOD_TEXT(K-2..K)=(46,46,46))THEN CUR_MODULE:=
PREFIX_LOOKUP(K-3);ELSE CUR_MODULE:=MOD_LOOKUP(K);END IF--{:141}
;ELSIF C=CONTROL_TEXT THEN LOOP C:=SKIP_AHEAD;EXIT WHEN C/=64;END LOOP;
IF BUFFER(LOC-1)/=62 THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Improper @ within control text");ERROR;END IF;
GOTO RESTART;
ELSIF C=ASCII_TOK THEN IF(BUFFER(LOC+1)=39)OR ELSE(BUFFER(LOC..LOC+2)=(64
,64,39))THEN SCANNING_CHARACTER:=TRUE;ELSE TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Improper ASCII-code sequence, ' sign mising");ERROR;
END IF;END IF--{:140}
;--{138:}
WHEN 46=>IF BUFFER(LOC)=46 THEN IF LOC<=LIMIT THEN C:=DOUBLE_DOT;
LOC:=LOC+1;END IF;END IF;
WHEN 58=>IF BUFFER(LOC)=61 THEN IF LOC<=LIMIT THEN C:=LEFT_ARROW;
LOC:=LOC+1;END IF;END IF;
WHEN 61=>IF BUFFER(LOC)=61 THEN IF LOC<=LIMIT THEN C:=EQUIVALENCE_SIGN;
LOC:=LOC+1;END IF;
ELSIF BUFFER(LOC)=62 THEN IF LOC<=LIMIT THEN C:=RIGHT_ARROW;LOC:=LOC+1;
END IF;END IF;
WHEN 62=>IF BUFFER(LOC)=61 THEN IF LOC<=LIMIT THEN C:=GREATER_OR_EQUAL;
LOC:=LOC+1;END IF;
ELSIF BUFFER(LOC)=62 THEN IF LOC<=LIMIT THEN C:=RIGHT_LABEL_BRACKET;
LOC:=LOC+1;END IF;END IF;
WHEN 60=>IF BUFFER(LOC)=61 THEN IF LOC<=LIMIT THEN C:=LESS_OR_EQUAL;
LOC:=LOC+1;END IF;
ELSIF BUFFER(LOC)=60 THEN IF LOC<=LIMIT THEN C:=LEFT_LABEL_BRACKET;
LOC:=LOC+1;END IF;
ELSIF BUFFER(LOC)=62 THEN IF LOC<=LIMIT THEN C:=BOX_SIGN;LOC:=LOC+1;
END IF;END IF;
WHEN 47=>IF BUFFER(LOC)=61 THEN IF LOC<=LIMIT THEN C:=NOT_EQUAL;
LOC:=LOC+1;END IF;END IF;
WHEN 42=>IF BUFFER(LOC)=42 THEN IF LOC<=LIMIT THEN C:=DOUBLE_STAR;
LOC:=LOC+1;END IF;END IF;--{:138}
WHEN 32!TAB_MARK=>GOTO RESTART;WHEN 123=>SKIP_COMMENT;GOTO RESTART;
WHEN 39=>--{146:}
IF(BUFFER(LOC+1)=39)OR ELSE(BUFFER(LOC..LOC+2)=(64,64,39))THEN
SCANNING_CHARACTER:=TRUE;RETURN CHARACTER_TOK;END IF--{:146}
;WHEN OTHERS=>NULL;END CASE;RETURN C;END GET_NEXT;--{:137}{149:}
PROCEDURE SCAN_REPL(T:EIGHT_BITS)IS A:SIXTEEN_BITS;B:ASCII_CODE;
BAL:EIGHT_BITS:=0;BEGIN LOOP<<CONTINUE>>A:=GET_NEXT;
CASE A IS WHEN 40=>BAL:=BAL+1;WHEN 41=>IF BAL=0 THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Extra )");ERROR;ELSE BAL:=BAL-1;END IF;WHEN 34=>--{152:}
B:=34;LOOP IF TOK_PTR(Z)=MAX_TOKS THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Sorry, "&"token"&" capacity exceeded");ERROR;
HISTORY:=FATAL_MESSAGE;RAISE END_OF_ATANGLE;END IF;
TOK_MEM(Z,TOK_PTR(Z)):=B;TOK_PTR(Z):=TOK_PTR(Z)+1;
IF B=64 THEN IF BUFFER(LOC)=64 THEN LOC:=LOC+1;ELSE TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! You should double @ signs in strings");ERROR;END IF;
END IF;IF LOC=LIMIT THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! String didn't end");ERROR;BUFFER(LOC..LOC+1):=(34,0);
END IF;B:=BUFFER(LOC);LOC:=LOC+1;IF B=34 THEN EXIT WHEN BUFFER(LOC)/=34;
LOC:=LOC+1;IF TOK_PTR(Z)=MAX_TOKS THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Sorry, "&"token"&" capacity exceeded");ERROR;
HISTORY:=FATAL_MESSAGE;RAISE END_OF_ATANGLE;END IF;
TOK_MEM(Z,TOK_PTR(Z)):=34;TOK_PTR(Z):=TOK_PTR(Z)+1;END IF;END LOOP
--{:152}
;WHEN CHARACTER_TOK!ASCII_TOK=>IF TOK_PTR(Z)=MAX_TOKS THEN TEXT_IO.
NEW_LINE;TEXT_IO.PUT("! Sorry, "&"token"&" capacity exceeded");ERROR;
HISTORY:=FATAL_MESSAGE;RAISE END_OF_ATANGLE;END IF;
TOK_MEM(Z,TOK_PTR(Z)):=A;TOK_PTR(Z):=TOK_PTR(Z)+1;A:=GET_NEXT;
WHEN 35=>IF T=PARAMETRIC THEN A:=PARAM;END IF;--{151:}
WHEN IDENTIFIER=>A:=ID_LOOKUP(NORMAL);
IF TOK_PTR(Z)=MAX_TOKS THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Sorry, "&"token"&" capacity exceeded");ERROR;
HISTORY:=FATAL_MESSAGE;RAISE END_OF_ATANGLE;END IF;
TOK_MEM(Z,TOK_PTR(Z)):=(A/8#400#)+8#200#;TOK_PTR(Z):=TOK_PTR(Z)+1;
A:=A MOD 8#400#;WHEN MODULE_NAME=>EXIT WHEN T/=MODULE_NAME;
IF TOK_PTR(Z)=MAX_TOKS THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Sorry, "&"token"&" capacity exceeded");ERROR;
HISTORY:=FATAL_MESSAGE;RAISE END_OF_ATANGLE;END IF;
TOK_MEM(Z,TOK_PTR(Z)):=(CUR_MODULE/8#400#)+8#250#;
TOK_PTR(Z):=TOK_PTR(Z)+1;A:=CUR_MODULE MOD 8#400#;WHEN VERBATIM=>
--{153:}
IF TOK_PTR(Z)=MAX_TOKS THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Sorry, "&"token"&" capacity exceeded");ERROR;
HISTORY:=FATAL_MESSAGE;RAISE END_OF_ATANGLE;END IF;
TOK_MEM(Z,TOK_PTR(Z)):=VERBATIM;TOK_PTR(Z):=TOK_PTR(Z)+1;
BUFFER(LIMIT+1):=64;
WHILE BUFFER(LOC)/=64 LOOP IF TOK_PTR(Z)=MAX_TOKS THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Sorry, "&"token"&" capacity exceeded");ERROR;
HISTORY:=FATAL_MESSAGE;RAISE END_OF_ATANGLE;END IF;
TOK_MEM(Z,TOK_PTR(Z)):=BUFFER(LOC);TOK_PTR(Z):=TOK_PTR(Z)+1;LOC:=LOC+1;
IF(LOC<LIMIT)AND THEN(BUFFER(LOC..LOC+1)=(64,64))THEN IF TOK_PTR(Z)=
MAX_TOKS THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Sorry, "&"token"&" capacity exceeded");ERROR;
HISTORY:=FATAL_MESSAGE;RAISE END_OF_ATANGLE;END IF;
TOK_MEM(Z,TOK_PTR(Z)):=64;TOK_PTR(Z):=TOK_PTR(Z)+1;LOC:=LOC+2;END IF;
END LOOP;IF LOC>=LIMIT THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Verbatim string didn't end");ERROR;
IF LOC>=BUF_SIZE-1 THEN LOC:=BUF_SIZE-2;END IF;
ELSIF BUFFER(LOC+1)/=62 THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! You should double @ signs in verbatim strings");ERROR;
END IF;LOC:=LOC+2--{:153}
;WHEN OUTPUT_TOK=>--{154:}
IF TOK_PTR(Z)=MAX_TOKS THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Sorry, "&"token"&" capacity exceeded");ERROR;
HISTORY:=FATAL_MESSAGE;RAISE END_OF_ATANGLE;END IF;
TOK_MEM(Z,TOK_PTR(Z)):=OUTPUT_TOK;TOK_PTR(Z):=TOK_PTR(Z)+1;
BUFFER(LIMIT+1):=64;
WHILE BUFFER(LOC)/=64 LOOP IF TOK_PTR(Z)=MAX_TOKS THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Sorry, "&"token"&" capacity exceeded");ERROR;
HISTORY:=FATAL_MESSAGE;RAISE END_OF_ATANGLE;END IF;
TOK_MEM(Z,TOK_PTR(Z)):=BUFFER(LOC);TOK_PTR(Z):=TOK_PTR(Z)+1;LOC:=LOC+1;
IF(LOC<LIMIT)AND THEN(BUFFER(LOC..LOC+1)=(64,64))THEN IF TOK_PTR(Z)=
MAX_TOKS THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Sorry, "&"token"&" capacity exceeded");ERROR;
HISTORY:=FATAL_MESSAGE;RAISE END_OF_ATANGLE;END IF;
TOK_MEM(Z,TOK_PTR(Z)):=64;TOK_PTR(Z):=TOK_PTR(Z)+1;LOC:=LOC+2;END IF;
END LOOP;IF LOC>=LIMIT THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Output file name didn't end");ERROR;
ELSIF BUFFER(LOC+1)/=62 THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! You should double @ signs in output file-names");ERROR;
END IF;LOC:=LOC+2--{:154}
;WHEN DEFINITION!FORMAT!BEGIN_ADA=>EXIT WHEN T/=MODULE_NAME;
TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! @"&XCHR(BUFFER(LOC-1))&" is ignored in ADA text");ERROR;
GOTO CONTINUE;WHEN NEW_MODULE=>EXIT;--{:151}
WHEN OTHERS=>NULL;END CASE;IF TOK_PTR(Z)=MAX_TOKS THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Sorry, "&"token"&" capacity exceeded");ERROR;
HISTORY:=FATAL_MESSAGE;RAISE END_OF_ATANGLE;END IF;
TOK_MEM(Z,TOK_PTR(Z)):=A;TOK_PTR(Z):=TOK_PTR(Z)+1;END LOOP;
NEXT_CONTROL:=A;--{150:}
IF BAL>0 THEN IF BAL=1 THEN TEXT_IO.NEW_LINE;TEXT_IO.PUT("! Missing )");
ERROR;ELSE TEXT_IO.NEW_LINE;TEXT_IO.PUT("! Missing ");
INT_NUMBER_IO.PUT(BAL,1);TEXT_IO.PUT(" )'s");ERROR;END IF;
WHILE BAL>0 LOOP IF TOK_PTR(Z)=MAX_TOKS THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Sorry, "&"token"&" capacity exceeded");ERROR;
HISTORY:=FATAL_MESSAGE;RAISE END_OF_ATANGLE;END IF;
TOK_MEM(Z,TOK_PTR(Z)):=41;TOK_PTR(Z):=TOK_PTR(Z)+1;BAL:=BAL-1;END LOOP;
END IF--{:150}
;IF TEXT_PTR>MAX_TEXTS-ZZ THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Sorry, "&"text"&" capacity exceeded");ERROR;
HISTORY:=FATAL_MESSAGE;RAISE END_OF_ATANGLE;END IF;
CUR_REPL_TEXT:=TEXT_PTR;TOK_START(TEXT_PTR+ZZ):=TOK_PTR(Z);
TEXT_PTR:=TEXT_PTR+1;IF Z=ZZ-1 THEN Z:=0;ELSE Z:=Z+1;END IF;
END SCAN_REPL;--{:149}{155:}
PROCEDURE DEFINE_MACRO(T:EIGHT_BITS)IS P:NAME_POINTER;
BEGIN P:=ID_LOOKUP(T);SCAN_REPL(T);EQUIV(P):=CUR_REPL_TEXT;
TEXT_LINK(CUR_REPL_TEXT):=0;END DEFINE_MACRO;--{:155}{157:}
PROCEDURE SCAN_MODULE IS P:NAME_POINTER;
BEGIN MODULE_COUNT:=MODULE_COUNT+1;--{158:}
NEXT_CONTROL:=0;
LOOP<<CONTINUE>>WHILE NEXT_CONTROL<=FORMAT LOOP NEXT_CONTROL:=SKIP_AHEAD
;IF NEXT_CONTROL=MODULE_NAME THEN LOC:=LOC-2;NEXT_CONTROL:=GET_NEXT;
END IF;END LOOP;EXIT WHEN NEXT_CONTROL/=DEFINITION;
NEXT_CONTROL:=GET_NEXT;
IF NEXT_CONTROL/=IDENTIFIER THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Definition flushed, must start with "&
"identifier of length > 1");ERROR;GOTO CONTINUE;END IF;
NEXT_CONTROL:=GET_NEXT;
IF NEXT_CONTROL=EQUIVALENCE_SIGN THEN DEFINE_MACRO(SIMPLE);
GOTO CONTINUE;ELSE--{159:}
IF NEXT_CONTROL=40 THEN NEXT_CONTROL:=GET_NEXT;
IF NEXT_CONTROL=35 THEN NEXT_CONTROL:=GET_NEXT;
IF NEXT_CONTROL=41 THEN NEXT_CONTROL:=GET_NEXT;
IF NEXT_CONTROL=61 THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Use == for macros");ERROR;NEXT_CONTROL:=EQUIVALENCE_SIGN;
END IF;IF NEXT_CONTROL=EQUIVALENCE_SIGN THEN DEFINE_MACRO(PARAMETRIC);
GOTO CONTINUE;END IF;END IF;END IF;END IF--{:159}
;END IF;TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Definition flushed since it starts badly");ERROR;END LOOP
--{:158}
;--{160:}
CASE NEXT_CONTROL IS WHEN BEGIN_ADA=>P:=0;
WHEN MODULE_NAME=>P:=CUR_MODULE;--{161:}
LOOP NEXT_CONTROL:=GET_NEXT;EXIT WHEN NEXT_CONTROL/=43;END LOOP;
IF(NEXT_CONTROL/=61)AND(NEXT_CONTROL/=EQUIVALENCE_SIGN)THEN TEXT_IO.
NEW_LINE;TEXT_IO.PUT("! ADA text flushed, = sign is missing");ERROR;
LOOP NEXT_CONTROL:=SKIP_AHEAD;EXIT WHEN NEXT_CONTROL=NEW_MODULE;
END LOOP;RETURN;END IF--{:161}
;WHEN OTHERS=>RETURN;END CASE;--{162:}
STORE_TWO_BYTES(8#150000#+MODULE_COUNT)--{:162}
;SCAN_REPL(MODULE_NAME);--{163:}
IF P=0 THEN TEXT_LINK(LAST_UNNAMED):=CUR_REPL_TEXT;
LAST_UNNAMED:=CUR_REPL_TEXT;
ELSIF EQUIV(P)=0 THEN EQUIV(P):=CUR_REPL_TEXT;ELSE P:=EQUIV(P);
WHILE TEXT_LINK(P)<MODULE_FLAG LOOP P:=TEXT_LINK(P);END LOOP;
TEXT_LINK(P):=CUR_REPL_TEXT;END IF;TEXT_LINK(CUR_REPL_TEXT):=MODULE_FLAG
--{:163}{:160}
;END SCAN_MODULE;--{:157}{164:}
PROCEDURE PHASE_I IS BEGIN--{126:}
LINE:=0;OTHER_LINE:=0;CHANGING:=TRUE;PRIME_THE_CHANGE_BUFFER;
CHANGING:=NOT CHANGING;TEMP_LINE:=OTHER_LINE;OTHER_LINE:=LINE;
LINE:=TEMP_LINE;LIMIT:=0;LOC:=1;BUFFER(0):=32;INPUT_HAS_ENDED:=FALSE
--{:126}
;TEXT_IO.PUT("This is ATANGLE, Version 1.1 (NRaD Version)");
TEXT_IO.NEW_LINE;--{167:}
PHASE_ONE:=TRUE;MODULE_COUNT:=0;LOOP NEXT_CONTROL:=SKIP_AHEAD;
EXIT WHEN NEXT_CONTROL=NEW_MODULE;END LOOP;
WHILE NOT INPUT_HAS_ENDED LOOP SCAN_MODULE;END LOOP;--{130:}
IF CHANGE_LIMIT/=0 THEN BUFFER(0..CHANGE_LIMIT):=CHANGE_BUFFER(0..
CHANGE_LIMIT);LIMIT:=CHANGE_LIMIT;CHANGING:=TRUE;LINE:=OTHER_LINE;
LOC:=CHANGE_LIMIT;TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Change file entry did not match");ERROR;END IF--{:130}
;PHASE_ONE:=FALSE--{:167}
;END PHASE_I;--{:164}
END INPUT_PHASE;--{:7}{166:}
