WITH TEXT_IO,INT_NUMBER_IO;PACKAGE BODY INPUT_OUTPUT IS--{24:}
PROCEDURE OPEN_A_FILE(F:IN OUT TEXT_FILE;MODE_OF_FILE:TEXT_IO.FILE_MODE;
DEFAULT_NAME:STRING;
SUCCESS:OUT BOOLEAN)IS BEGIN IF TEXT_IO.IS_OPEN(F)THEN SUCCESS:=TRUE;
ELSE TEXT_IO.OPEN(FILE=>F,MODE=>MODE_OF_FILE,NAME=>DEFAULT_NAME);
SUCCESS:=TRUE;END IF;
EXCEPTION WHEN TEXT_IO.STATUS_ERROR!TEXT_IO.NAME_ERROR!TEXT_IO.USE_ERROR
=>SUCCESS:=FALSE;RETURN;END OPEN_A_FILE;--{:24}{26:}
FUNCTION CREATE_ADA_FILE(ADA_FILE_NAME:STRING)RETURN BOOLEAN IS BEGIN IF
TEXT_IO.IS_OPEN(ADA_FILE)THEN IF TEXT_IO.NAME(ADA_FILE)=ADA_FILE_NAME
THEN RETURN TRUE;ELSE RETURN FALSE;END IF;
ELSE TEXT_IO.CREATE(FILE=>ADA_FILE,MODE=>TEXT_IO.OUT_FILE,NAME=>
ADA_FILE_NAME);RETURN TRUE;END IF;
EXCEPTION WHEN TEXT_IO.STATUS_ERROR!TEXT_IO.NAME_ERROR!TEXT_IO.USE_ERROR
=>RETURN FALSE;END CREATE_ADA_FILE;--{:26}{29:}
FUNCTION INPUT_LN(F:TEXT_FILE)RETURN BOOLEAN IS FINAL_LIMIT:BUFFER_INDEX
:=0;C:TEXT_CHAR;BEGIN LIMIT:=0;
IF NOT TEXT_IO.IS_OPEN(F)OR ELSE TEXT_IO.END_OF_FILE(F)THEN RETURN FALSE
;ELSE WHILE NOT TEXT_IO.END_OF_LINE(F)LOOP TEXT_IO.GET(F,C);
BUFFER(LIMIT):=XORD(C);LIMIT:=LIMIT+1;
IF BUFFER(LIMIT-1)/=32 THEN FINAL_LIMIT:=LIMIT;END IF;
IF LIMIT=BUF_SIZE THEN TEXT_IO.SKIP_LINE(F);LIMIT:=LIMIT-1;
TEXT_IO.NEW_LINE;TEXT_IO.PUT("! Input line too long");LOC:=0;ERROR;
RETURN TRUE;END IF;END LOOP;TEXT_IO.SKIP_LINE(F);LIMIT:=FINAL_LIMIT;
RETURN TRUE;END IF;END INPUT_LN;--{:29}{32:}
PROCEDURE ERROR IS L:BUFFER_INDEX;BEGIN IF PHASE_ONE THEN--{33:}
IF CHANGING THEN TEXT_IO.PUT(". (change file ");ELSE TEXT_IO.PUT(". (");
END IF;TEXT_IO.PUT("l.");INT_NUMBER_IO.PUT(LINE,1);TEXT_IO.PUT(")");
TEXT_IO.NEW_LINE;IF LOC>=LIMIT THEN L:=LIMIT;ELSE L:=LOC;END IF;
FOR K IN 1..L LOOP IF BUFFER(K-1)=TAB_MARK THEN TEXT_IO.PUT(" ");
ELSE TEXT_IO.PUT(XCHR(BUFFER(K-1)));END IF;END LOOP;TEXT_IO.NEW_LINE;
FOR K IN 1..L LOOP TEXT_IO.PUT(" ");END LOOP;
FOR K IN L+1..LIMIT LOOP TEXT_IO.PUT(XCHR(BUFFER(K-1)));END LOOP;
TEXT_IO.PUT(" ")--{:33}
;ELSE--{34:}
TEXT_IO.PUT(".("&FILE_NAME(1..FN_LENGTH)&" l.");
INT_NUMBER_IO.PUT(F_LINE,1);TEXT_IO.PUT(")");TEXT_IO.NEW_LINE;
FOR J IN 1..OUT_PTR LOOP TEXT_IO.PUT(XCHR(OUT_BUF(J-1)));END LOOP;
TEXT_IO.PUT("... ")--{:34}
;END IF;NULL;HISTORY:=ERROR_MESSAGE;END ERROR;--{:32}
END INPUT_OUTPUT;--{:4}{5:}
