WITH TEXT_IO;WITH INPUT_OUTPUT;USE INPUT_OUTPUT;PACKAGE BODY HASHING IS
--{51:}
FUNCTION ID_LOOKUP(T:EIGHT_BITS)RETURN NAME_POINTER IS C:EIGHT_BITS;
I:BUFFER_INDEX;H:HASH_INDEX;K:BYTE_INDEX;W:W_RANGE;
L:BUFFER_INDEX:=ID_LOC-ID_FIRST;P,Q:NAME_POINTER;S:CHOP_HASH_INDEX;BEGIN
--{52:}
H:=BUFFER(ID_FIRST);I:=ID_FIRST+1;
WHILE I<ID_LOC LOOP H:=(H+H+BUFFER(I))MOD HASH_SIZE;I:=I+1;END LOOP
--{:52}
;--{53:}
P:=HASH(H);WHILE P/=0 LOOP IF BYTE_START(P+WW)-BYTE_START(P)=L THEN
--{54:}
I:=ID_FIRST;K:=BYTE_START(P);W:=P MOD WW;
WHILE(I<ID_LOC)AND(BUFFER(I)=BYTE_MEM(W,K))LOOP I:=I+1;K:=K+1;END LOOP;
IF I=ID_LOC THEN GOTO FOUND;END IF--{:54}
;END IF;P:=LINK(P);END LOOP;P:=NAME_PTR;LINK(P):=HASH(H);HASH(H):=P;
<<FOUND>>NULL--{:53}
;IF(P=NAME_PTR)OR(T/=NORMAL)THEN--{55:}
IF((P/=NAME_PTR)AND(T/=NORMAL)AND(ILK(P)=NORMAL))OR((P=NAME_PTR)AND(T=
NORMAL))THEN--{56:}
I:=ID_FIRST;S:=0;H:=0;
WHILE(I<ID_LOC)AND(S<UNAMBIG_LENGTH)LOOP IF BUFFER(I)>=97 THEN
CHOPPED_ID(S):=BUFFER(I)-8#40#;ELSE CHOPPED_ID(S):=BUFFER(I);END IF;
H:=(H+H+CHOPPED_ID(S))MOD HASH_SIZE;S:=S+1;I:=I+1;END LOOP;
CHOPPED_ID(S):=0--{:56}
;END IF;IF P/=NAME_PTR THEN--{57:}
IF ILK(P)=NORMAL THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! This identifier has already appeared");ERROR;--{58:}
Q:=CHOP_HASH(H);IF Q=P THEN CHOP_HASH(H):=EQUIV(P);
ELSE WHILE EQUIV(Q)/=P LOOP Q:=EQUIV(Q);END LOOP;EQUIV(Q):=EQUIV(P);
END IF--{:58}
;ELSE TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! This identifier was defined before");ERROR;END IF;
ILK(P):=T--{:57}
;ELSE--{59:}
IF T=NORMAL THEN--{60:}
Q:=CHOP_HASH(H);WHILE Q/=0 LOOP--{61:}
K:=BYTE_START(Q);S:=0;W:=Q MOD WW;
WHILE(K<BYTE_START(Q+WW))AND(S<UNAMBIG_LENGTH)LOOP C:=BYTE_MEM(W,K);
IF C>=97 THEN C:=C-8#40#;END IF;IF CHOPPED_ID(S)/=C THEN GOTO NOT_FOUND;
END IF;S:=S+1;K:=K+1;END LOOP;
IF(K=BYTE_START(Q+WW))AND(CHOPPED_ID(S)/=0)THEN GOTO NOT_FOUND;END IF;
TEXT_IO.NEW_LINE;TEXT_IO.PUT("! Identifier conflict with ");
FOR KL IN BYTE_START(Q)..BYTE_START(Q+WW)-1 LOOP TEXT_IO.PUT(XCHR(
BYTE_MEM(W,KL)));END LOOP;ERROR;Q:=0;<<NOT_FOUND>>NULL--{:61}
;Q:=EQUIV(Q);END LOOP;EQUIV(P):=CHOP_HASH(H);CHOP_HASH(H):=P--{:60}
;END IF;W:=NAME_PTR MOD WW;K:=BYTE_PTR(W);
IF K+L>MAX_BYTES THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Sorry, "&"byte memory"&" capacity exceeded");ERROR;
HISTORY:=FATAL_MESSAGE;RAISE END_OF_ATANGLE;END IF;
IF NAME_PTR>MAX_NAMES-WW THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Sorry, "&"name"&" capacity exceeded");ERROR;
HISTORY:=FATAL_MESSAGE;RAISE END_OF_ATANGLE;END IF;I:=ID_FIRST;
WHILE I<ID_LOC LOOP BYTE_MEM(W,K):=BUFFER(I);K:=K+1;I:=I+1;END LOOP;
BYTE_PTR(W):=K;BYTE_START(NAME_PTR+WW):=K;NAME_PTR:=NAME_PTR+1;ILK(P):=T
--{:59}
;END IF--{:55}
;END IF;RETURN P;END ID_LOOKUP;--{:51}{65:}
FUNCTION MOD_LOOKUP(L:SIXTEEN_BITS)RETURN NAME_POINTER IS C:COMPARE:=
GREATER;J:LONG_NAME_INDEX;K:BYTE_INDEX;W:W_RANGE;P:NAME_POINTER;
Q:NAME_POINTER:=0;BEGIN P:=RLINK(0);WHILE P/=0 LOOP--{67:}
K:=BYTE_START(P);W:=P MOD WW;C:=EQUAL;J:=1;
WHILE(K<BYTE_START(P+WW))AND(J<=L)AND(MOD_TEXT(J)=BYTE_MEM(W,K))LOOP K:=
K+1;J:=J+1;END LOOP;IF K=BYTE_START(P+WW)THEN IF J>L THEN C:=EQUAL;
ELSE C:=EXTENSION;END IF;ELSIF J>L THEN C:=PREFIX;
ELSIF MOD_TEXT(J)<BYTE_MEM(W,K)THEN C:=LESS;ELSE C:=GREATER;END IF
--{:67}
;Q:=P;IF C=LESS THEN P:=LLINK(Q);ELSIF C=GREATER THEN P:=RLINK(Q);
ELSE GOTO FOUND;END IF;END LOOP;--{66:}
W:=NAME_PTR MOD WW;K:=BYTE_PTR(W);
IF K+L>MAX_BYTES THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Sorry, "&"byte memory"&" capacity exceeded");ERROR;
HISTORY:=FATAL_MESSAGE;RAISE END_OF_ATANGLE;END IF;
IF NAME_PTR>MAX_NAMES-WW THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Sorry, "&"name"&" capacity exceeded");ERROR;
HISTORY:=FATAL_MESSAGE;RAISE END_OF_ATANGLE;END IF;P:=NAME_PTR;
IF C=LESS THEN LLINK(Q):=P;ELSE RLINK(Q):=P;END IF;LLINK(P):=0;
RLINK(P):=0;C:=EQUAL;EQUIV(P):=0;
FOR KJ IN 1..L LOOP BYTE_MEM(W,K+KJ-1):=MOD_TEXT(KJ);END LOOP;
BYTE_PTR(W):=K+L;BYTE_START(NAME_PTR+WW):=K+L;NAME_PTR:=NAME_PTR+1
--{:66}
;<<FOUND>>IF C/=EQUAL THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Incompatible section names");ERROR;P:=0;END IF;RETURN P;
END MOD_LOOKUP;--{:65}{69:}
FUNCTION PREFIX_LOOKUP(L:SIXTEEN_BITS)RETURN NAME_POINTER IS C:COMPARE;
COUNT:NAME_INDEX:=0;J:LONG_NAME_INDEX;K:BYTE_INDEX;W:W_RANGE;
P:NAME_POINTER;Q:NAME_POINTER:=0;R:NAME_POINTER:=0;BEGIN P:=RLINK(0);
WHILE P/=0 LOOP--{67:}
K:=BYTE_START(P);W:=P MOD WW;C:=EQUAL;J:=1;
WHILE(K<BYTE_START(P+WW))AND(J<=L)AND(MOD_TEXT(J)=BYTE_MEM(W,K))LOOP K:=
K+1;J:=J+1;END LOOP;IF K=BYTE_START(P+WW)THEN IF J>L THEN C:=EQUAL;
ELSE C:=EXTENSION;END IF;ELSIF J>L THEN C:=PREFIX;
ELSIF MOD_TEXT(J)<BYTE_MEM(W,K)THEN C:=LESS;ELSE C:=GREATER;END IF
--{:67}
;IF C=LESS THEN P:=LLINK(P);ELSIF C=GREATER THEN P:=RLINK(P);ELSE R:=P;
COUNT:=COUNT+1;Q:=RLINK(P);P:=LLINK(P);END IF;IF P=0 THEN P:=Q;Q:=0;
END IF;END LOOP;IF COUNT/=1 THEN IF COUNT=0 THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Name does not match");ERROR;ELSE TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Ambiguous prefix");ERROR;END IF;END IF;RETURN R;
END PREFIX_LOOKUP;--{:69}
END HASHING;--{:5}{6:}
