WITH DATA_STRUCTURES;USE DATA_STRUCTURES;PACKAGE HASHING IS--{50:}
FUNCTION ID_LOOKUP(T:EIGHT_BITS)RETURN NAME_POINTER;--{:50}{64:}
FUNCTION MOD_LOOKUP(L:SIXTEEN_BITS)RETURN NAME_POINTER;--{:64}{68:}
FUNCTION PREFIX_LOOKUP(L:SIXTEEN_BITS)RETURN NAME_POINTER;--{:68}
END HASHING;
