WITH TEXT_IO;WITH DATA_STRUCTURES;USE DATA_STRUCTURES;
PACKAGE INPUT_OUTPUT IS--{23:}
PROCEDURE OPEN_A_FILE(F:IN OUT TEXT_FILE;MODE_OF_FILE:TEXT_IO.FILE_MODE;
DEFAULT_NAME:STRING;SUCCESS:OUT BOOLEAN);
FUNCTION CREATE_ADA_FILE(ADA_FILE_NAME:STRING)RETURN BOOLEAN;
--{:23}{28:}
FUNCTION INPUT_LN(F:TEXT_FILE)RETURN BOOLEAN;--{:28}{31:}
PROCEDURE ERROR;--{:31}
END INPUT_OUTPUT;
