WITH TEXT_IO,INT_NUMBER_IO;WITH INPUT_OUTPUT;USE INPUT_OUTPUT;
PACKAGE BODY OUTPUT_PHASE IS--{81:}
PROCEDURE PUSH_LEVEL(P:NAME_POINTER)IS BEGIN IF STACK_PTR=STACK_SIZE
THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Sorry, "&"stack"&" capacity exceeded");ERROR;
HISTORY:=FATAL_MESSAGE;RAISE END_OF_ATANGLE;
ELSE STACK(STACK_PTR):=CUR_STATE;STACK_PTR:=STACK_PTR+1;CUR_NAME:=P;
CUR_REPL:=EQUIV(P);ZO:=CUR_REPL MOD ZZ;CUR_BYTE:=TOK_START(CUR_REPL);
CUR_END:=TOK_START(CUR_REPL+ZZ);CUR_MOD:=0;END IF;END PUSH_LEVEL;
--{:81}{82:}
PROCEDURE POP_LEVEL IS BEGIN IF TEXT_LINK(CUR_REPL)=0 THEN IF ILK(
CUR_NAME)=PARAMETRIC THEN--{88:}
NAME_PTR:=NAME_PTR-1;TEXT_PTR:=TEXT_PTR-1;Z:=TEXT_PTR MOD ZZ;
--IF TOK_PTR(Z)>MAX_TOK_PTR(Z)THEN MAX_TOK_PTR(Z):=TOK_PTR(Z);END IF;
TOK_PTR(Z):=TOK_START(TEXT_PTR)--{:88}
;END IF;
ELSIF TEXT_LINK(CUR_REPL)<MODULE_FLAG THEN CUR_REPL:=TEXT_LINK(CUR_REPL)
;ZO:=CUR_REPL MOD ZZ;CUR_BYTE:=TOK_START(CUR_REPL);
CUR_END:=TOK_START(CUR_REPL+ZZ);RETURN;END IF;STACK_PTR:=STACK_PTR-1;
IF STACK_PTR>0 THEN CUR_STATE:=STACK(STACK_PTR);ZO:=CUR_REPL MOD ZZ;
END IF;END POP_LEVEL;--{:82}{84:}
FUNCTION GET_OUTPUT RETURN SIXTEEN_BITS IS A:SIXTEEN_BITS;B:EIGHT_BITS;
BAL:SIXTEEN_BITS;K:BYTE_INDEX;W:W_RANGE;
BEGIN<<RESTART>>IF STACK_PTR=0 THEN RETURN 0;END IF;
IF CUR_BYTE=CUR_END THEN CUR_VAL:=-CUR_MOD;POP_LEVEL;
IF CUR_VAL=0 THEN GOTO RESTART;END IF;RETURN MODULE_NUMBER;END IF;
A:=TOK_MEM(ZO,CUR_BYTE);CUR_BYTE:=CUR_BYTE+1;
IF A<8#200# THEN IF A=PARAM THEN--{89:}
PUSH_LEVEL(NAME_PTR-1);GOTO RESTART--{:89}
;ELSE RETURN A;END IF;END IF;A:=(A-8#200#)*8#400#+TOK_MEM(ZO,CUR_BYTE);
CUR_BYTE:=CUR_BYTE+1;IF A<8#24000# THEN--{86:}
CASE ILK(A)IS WHEN NORMAL=>CUR_VAL:=A;RETURN IDENTIFIER;
WHEN SIMPLE=>PUSH_LEVEL(A);GOTO RESTART;WHEN PARAMETRIC=>--{87:}
WHILE(CUR_BYTE=CUR_END)AND(STACK_PTR>0)LOOP POP_LEVEL;END LOOP;
IF(STACK_PTR=0)OR(TOK_MEM(ZO,CUR_BYTE)/=40)THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! No parameter given for ");PRINT_ID(A);ERROR;GOTO RESTART;
END IF;--{90:}
BAL:=1;CUR_BYTE:=CUR_BYTE+1;LOOP B:=TOK_MEM(ZO,CUR_BYTE);
CUR_BYTE:=CUR_BYTE+1;IF B=PARAM THEN STORE_TWO_BYTES(NAME_PTR+8#77777#);
ELSE IF B>=8#200# THEN IF TOK_PTR(Z)=MAX_TOKS THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Sorry, "&"token"&" capacity exceeded");ERROR;
HISTORY:=FATAL_MESSAGE;RAISE END_OF_ATANGLE;END IF;
TOK_MEM(Z,TOK_PTR(Z)):=B;TOK_PTR(Z):=TOK_PTR(Z)+1;
B:=TOK_MEM(ZO,CUR_BYTE);CUR_BYTE:=CUR_BYTE+1;
ELSE CASE B IS WHEN 40=>BAL:=BAL+1;WHEN 41=>BAL:=BAL-1;EXIT WHEN BAL=0;
WHEN CHARACTER_TOK!ASCII_TOK=>IF TOK_PTR(Z)=MAX_TOKS THEN TEXT_IO.
NEW_LINE;TEXT_IO.PUT("! Sorry, "&"token"&" capacity exceeded");ERROR;
HISTORY:=FATAL_MESSAGE;RAISE END_OF_ATANGLE;END IF;
TOK_MEM(Z,TOK_PTR(Z)):=B;TOK_PTR(Z):=TOK_PTR(Z)+1;
B:=TOK_MEM(ZO,CUR_BYTE);CUR_BYTE:=CUR_BYTE+1;
WHEN 34=>LOOP IF TOK_PTR(Z)=MAX_TOKS THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Sorry, "&"token"&" capacity exceeded");ERROR;
HISTORY:=FATAL_MESSAGE;RAISE END_OF_ATANGLE;END IF;
TOK_MEM(Z,TOK_PTR(Z)):=B;TOK_PTR(Z):=TOK_PTR(Z)+1;
B:=TOK_MEM(ZO,CUR_BYTE);CUR_BYTE:=CUR_BYTE+1;
IF B=34 AND TOK_MEM(ZO,CUR_BYTE)=34 THEN IF TOK_PTR(Z)=MAX_TOKS THEN
TEXT_IO.NEW_LINE;TEXT_IO.PUT("! Sorry, "&"token"&" capacity exceeded");
ERROR;HISTORY:=FATAL_MESSAGE;RAISE END_OF_ATANGLE;END IF;
TOK_MEM(Z,TOK_PTR(Z)):=34;TOK_PTR(Z):=TOK_PTR(Z)+1;
IF TOK_PTR(Z)=MAX_TOKS THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Sorry, "&"token"&" capacity exceeded");ERROR;
HISTORY:=FATAL_MESSAGE;RAISE END_OF_ATANGLE;END IF;
TOK_MEM(Z,TOK_PTR(Z)):=34;TOK_PTR(Z):=TOK_PTR(Z)+1;
B:=TOK_MEM(ZO,CUR_BYTE+1);CUR_BYTE:=CUR_BYTE+2;END IF;EXIT WHEN B=34;
END LOOP;WHEN OTHERS=>NULL;END CASE;END IF;
IF TOK_PTR(Z)=MAX_TOKS THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Sorry, "&"token"&" capacity exceeded");ERROR;
HISTORY:=FATAL_MESSAGE;RAISE END_OF_ATANGLE;END IF;
TOK_MEM(Z,TOK_PTR(Z)):=B;TOK_PTR(Z):=TOK_PTR(Z)+1;END IF;END LOOP--{:90}
;EQUIV(NAME_PTR):=TEXT_PTR;ILK(NAME_PTR):=SIMPLE;W:=NAME_PTR MOD WW;
K:=BYTE_PTR(W);IF NAME_PTR>MAX_NAMES-WW THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Sorry, "&"name"&" capacity exceeded");ERROR;
HISTORY:=FATAL_MESSAGE;RAISE END_OF_ATANGLE;END IF;
BYTE_START(NAME_PTR+WW):=K;NAME_PTR:=NAME_PTR+1;
IF TEXT_PTR>MAX_TEXTS-ZZ THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Sorry, "&"text"&" capacity exceeded");ERROR;
HISTORY:=FATAL_MESSAGE;RAISE END_OF_ATANGLE;END IF;
TEXT_LINK(TEXT_PTR):=0;TOK_START(TEXT_PTR+ZZ):=TOK_PTR(Z);
TEXT_PTR:=TEXT_PTR+1;Z:=TEXT_PTR MOD ZZ--{:87}
;PUSH_LEVEL(A);GOTO RESTART;WHEN OTHERS=>TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! This can't happen ("&"output"&")");ERROR;
HISTORY:=FATAL_MESSAGE;RAISE END_OF_ATANGLE;END CASE;RETURN A--{:86}
;END IF;IF A<8#50000# THEN--{85:}
A:=A-8#24000#;IF EQUIV(A)/=0 THEN PUSH_LEVEL(A);
ELSIF A/=0 THEN TEXT_IO.NEW_LINE;TEXT_IO.PUT("! Not present: <");
PRINT_ID(A);TEXT_IO.PUT(">");ERROR;END IF;GOTO RESTART--{:85}
;END IF;CUR_VAL:=A-8#50000#;CUR_MOD:=CUR_VAL;RETURN MODULE_NUMBER;
END GET_OUTPUT;--{:84}{94:}
PROCEDURE FLUSH_BUFFER IS B:OUT_BUFFER_INDEX:=BREAK_PTR;
BEGIN IF COMMENT_OUTPUT THEN TEXT_IO.PUT(ADA_FILE,"--");END IF;
IF(SEMI_PTR/=0)AND(OUT_PTR-SEMI_PTR<=LINE_LENGTH)THEN BREAK_PTR:=
SEMI_PTR;END IF;
FOR K IN 1..BREAK_PTR LOOP TEXT_IO.PUT(ADA_FILE,XCHR(OUT_BUF(K-1)));
END LOOP;TEXT_IO.NEW_LINE(ADA_FILE);LINE:=LINE+1;F_LINE:=F_LINE+1;
IF LINE MOD 100=0 THEN TEXT_IO.PUT(".");
IF LINE MOD 500=0 THEN INT_NUMBER_IO.PUT(LINE,1);NULL;END IF;END IF;
IF BREAK_PTR<OUT_PTR THEN IF OUT_BUF(BREAK_PTR)=32 THEN BREAK_PTR:=
BREAK_PTR+1;IF BREAK_PTR>B THEN B:=BREAK_PTR;END IF;END IF;
OUT_BUF(0..OUT_PTR-BREAK_PTR-1):=OUT_BUF(BREAK_PTR..OUT_PTR-1);END IF;
OUT_PTR:=OUT_PTR-BREAK_PTR;BREAK_PTR:=B-BREAK_PTR;SEMI_PTR:=0;
IF OUT_PTR>LINE_LENGTH THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Long line must be truncated");ERROR;OUT_PTR:=LINE_LENGTH;
END IF;END FLUSH_BUFFER;--{:94}{96:}
PROCEDURE SEND_VAL(V:INTEGER)IS K:OUT_BUFFER_INDEX:=OUT_BUF_SIZE;
U:INTEGER:=V;BEGIN LOOP OUT_BUF(K):=U MOD 10;U:=U/10;K:=K-1;
EXIT WHEN U=0;END LOOP;LOOP K:=K+1;OUT_BUF(OUT_PTR):=OUT_BUF(K)+48;
OUT_PTR:=OUT_PTR+1;EXIT WHEN K=OUT_BUF_SIZE;END LOOP;END SEND_VAL;
--{:96}{98:}
PROCEDURE SEND_OUT(T:EIGHT_BITS;V:SIXTEEN_BITS)IS BEGIN--{99:}
<<RESTART>>CASE OUT_STATE IS WHEN NUM_OR_ID=>IF T/=FRAC THEN BREAK_PTR:=
OUT_PTR;IF T=IDENT THEN OUT_BUF(OUT_PTR):=32;OUT_PTR:=OUT_PTR+1;END IF;
END IF;WHEN MISC=>IF T/=FRAC THEN BREAK_PTR:=OUT_PTR;END IF;
WHEN OTHERS=>NULL;END CASE--{:99}
;IF T/=MISC THEN FOR K IN 1..V LOOP OUT_BUF(OUT_PTR):=OUT_CONTRIB(K);
OUT_PTR:=OUT_PTR+1;END LOOP;ELSE OUT_BUF(OUT_PTR):=V;OUT_PTR:=OUT_PTR+1;
END IF;IF OUT_PTR>LINE_LENGTH THEN FLUSH_BUFFER;END IF;
IF(T=MISC)AND(V=59)THEN SEMI_PTR:=OUT_PTR;BREAK_PTR:=OUT_PTR;END IF;
IF T>=IDENT THEN OUT_STATE:=NUM_OR_ID;ELSE OUT_STATE:=MISC;END IF;
END SEND_OUT;--{:98}{101:}
PROCEDURE SEND_THE_OUTPUT IS CUR_CHAR:EIGHT_BITS;
K:INTEGER RANGE 0..LINE_LENGTH;J:BYTE_INDEX;W:W_RANGE;
BEGIN WHILE STACK_PTR>0 LOOP CUR_CHAR:=GET_OUTPUT;
<<RESWITCH>>CASE CUR_CHAR IS WHEN 0=>NULL;--{104:}
WHEN 65..90=>OUT_CONTRIB(1):=CUR_CHAR;SEND_OUT(IDENT,1);
WHEN 97..122=>OUT_CONTRIB(1):=CUR_CHAR-8#40#;SEND_OUT(IDENT,1);
WHEN IDENTIFIER=>K:=0;J:=BYTE_START(CUR_VAL);W:=CUR_VAL MOD WW;
WHILE(K<MAX_ID_LENGTH)AND(J<BYTE_START(CUR_VAL+WW))LOOP K:=K+1;
OUT_CONTRIB(K):=BYTE_MEM(W,J);J:=J+1;
IF OUT_CONTRIB(K)>=97 THEN OUT_CONTRIB(K):=OUT_CONTRIB(K)-8#40#;END IF;
END LOOP;SEND_OUT(IDENT,K);--{:104}{110:}
WHEN 48..57=>SCANNING_BASED_NUMBER:=FALSE;K:=0;
LOOP IF CUR_CHAR/=95 THEN K:=K+1;OUT_CONTRIB(K):=CUR_CHAR;
CUR_CHAR:=GET_OUTPUT;
IF CUR_CHAR=35 THEN SCANNING_BASED_NUMBER:=NOT SCANNING_BASED_NUMBER;
ELSE EXIT WHEN((NOT SCANNING_BASED_NUMBER)AND(CUR_CHAR NOT IN 48..57)AND
(CUR_CHAR/=95));END IF;ELSE CUR_CHAR:=GET_OUTPUT;END IF;END LOOP;
SEND_OUT(IDENT,K);K:=0;IF CUR_CHAR=101 THEN CUR_CHAR:=69;END IF;
IF CUR_CHAR=69 THEN GOTO GET_FRACTION;ELSE GOTO RESWITCH;END IF;
WHEN 46=>K:=1;OUT_CONTRIB(1):=46;CUR_CHAR:=GET_OUTPUT;
IF CUR_CHAR=46 THEN OUT_CONTRIB(2):=46;SEND_OUT(STR,2);
ELSIF CUR_CHAR IN 48..57 THEN GOTO GET_FRACTION;ELSE SEND_OUT(MISC,46);
GOTO RESWITCH;END IF;--{:110}{102:}
WHEN AND_SIGN=>OUT_CONTRIB(1..3):=(65,78,68);SEND_OUT(IDENT,3);
WHEN NOT_SIGN=>OUT_CONTRIB(1..3):=(78,79,84);SEND_OUT(IDENT,3);
WHEN SET_ELEMENT_SIGN=>OUT_CONTRIB(1..2):=(73,78);SEND_OUT(IDENT,2);
WHEN OR_SIGN=>OUT_CONTRIB(1..2):=(79,82);SEND_OUT(IDENT,2);
WHEN LEFT_ARROW=>OUT_CONTRIB(1..2):=(58,61);SEND_OUT(STR,2);
WHEN NOT_EQUAL=>OUT_CONTRIB(1..2):=(47,61);SEND_OUT(STR,2);
WHEN LESS_OR_EQUAL=>OUT_CONTRIB(1..2):=(60,61);SEND_OUT(STR,2);
WHEN GREATER_OR_EQUAL=>OUT_CONTRIB(1..2):=(62,61);SEND_OUT(STR,2);
WHEN EQUIVALENCE_SIGN=>OUT_CONTRIB(1..2):=(61,61);SEND_OUT(STR,2);
WHEN DOUBLE_DOT=>OUT_CONTRIB(1..2):=(46,46);SEND_OUT(STR,2);
WHEN RIGHT_ARROW=>OUT_CONTRIB(1..2):=(61,62);SEND_OUT(STR,2);
WHEN BOX_SIGN=>OUT_CONTRIB(1..2):=(60,62);SEND_OUT(STR,2);
WHEN LEFT_LABEL_BRACKET=>OUT_CONTRIB(1..2):=(60,60);SEND_OUT(STR,2);
WHEN RIGHT_LABEL_BRACKET=>OUT_CONTRIB(1..2):=(62,62);SEND_OUT(STR,2);
WHEN DOUBLE_STAR=>OUT_CONTRIB(1..2):=(42,42);SEND_OUT(STR,2);
WHEN CHARACTER_TOK=>OUT_CONTRIB(1..3):=(39,GET_OUTPUT,39);
SEND_OUT(STR,3);
WHEN ASCII_TOK=>IF OUT_STATE=NUM_OR_ID THEN SEND_OUT(MISC,32);END IF;
SEND_VAL(GET_OUTPUT);OUT_STATE:=NUM_OR_ID;--{:102}
WHEN 34=>--{105:}
K:=1;OUT_CONTRIB(1):=34;LOOP IF K<LINE_LENGTH THEN K:=K+1;END IF;
OUT_CONTRIB(K):=GET_OUTPUT;EXIT WHEN(OUT_CONTRIB(K)=34)OR(STACK_PTR=0);
END LOOP;IF K=LINE_LENGTH THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! String too long");ERROR;END IF;SEND_OUT(STR,K);
CUR_CHAR:=GET_OUTPUT;IF CUR_CHAR=34 THEN OUT_STATE:=UNBREAKABLE;END IF;
GOTO RESWITCH--{:105}
;WHEN--{103:}
33!35!36!37!38!39!40!41!42!44!47!58!59!60!61!62!63!64!91!92!93!94!95!96!123
!124!43!45--{:103}
=>SEND_OUT(MISC,CUR_CHAR);--{112:}
WHEN BEGIN_COMMENT=>--{113:}
SEND_OUT(STR,0);
WHILE OUT_PTR>0 LOOP IF OUT_PTR<=LINE_LENGTH THEN BREAK_PTR:=OUT_PTR;
END IF;FLUSH_BUFFER;END LOOP;OUT_STATE:=MISC--{:113}
;BRACE_LEVEL:=BRACE_LEVEL+1;COMMENT_OUTPUT:=TRUE;
WHEN END_COMMENT=>IF BRACE_LEVEL>0 THEN BRACE_LEVEL:=BRACE_LEVEL-1;
IF BRACE_LEVEL=0 THEN--{113:}
SEND_OUT(STR,0);
WHILE OUT_PTR>0 LOOP IF OUT_PTR<=LINE_LENGTH THEN BREAK_PTR:=OUT_PTR;
END IF;FLUSH_BUFFER;END LOOP;OUT_STATE:=MISC--{:113}
;COMMENT_OUTPUT:=FALSE;END IF;ELSE TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Extra @}");ERROR;END IF;WHEN MODULE_NUMBER=>SEMI_PTR:=0;
OUT_CONTRIB(1..2):=(45,45);SEND_OUT(STR,2);
WHILE CUR_CHAR=MODULE_NUMBER LOOP OUT_STATE:=UNBREAKABLE;
SEND_OUT(MISC,123);OUT_STATE:=UNBREAKABLE;
IF CUR_VAL<0 THEN SEND_OUT(MISC,58);OUT_STATE:=UNBREAKABLE;
SEND_VAL(-CUR_VAL);ELSE SEND_VAL(CUR_VAL);OUT_STATE:=UNBREAKABLE;
SEND_OUT(MISC,58);END IF;OUT_STATE:=UNBREAKABLE;SEND_OUT(MISC,125);
CUR_CHAR:=GET_OUTPUT;END LOOP;--{113:}
SEND_OUT(STR,0);
WHILE OUT_PTR>0 LOOP IF OUT_PTR<=LINE_LENGTH THEN BREAK_PTR:=OUT_PTR;
END IF;FLUSH_BUFFER;END LOOP;OUT_STATE:=MISC--{:113}
;GOTO RESWITCH;--{:112}
WHEN JOIN=>SEND_OUT(FRAC,0);OUT_STATE:=UNBREAKABLE;WHEN VERBATIM=>
--{106:}
K:=0;LOOP IF K<LINE_LENGTH THEN K:=K+1;END IF;
OUT_CONTRIB(K):=GET_OUTPUT;
EXIT WHEN(OUT_CONTRIB(K)=VERBATIM)OR(STACK_PTR=0);END LOOP;
IF K=LINE_LENGTH THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Verbatim string too long");ERROR;END IF;SEND_OUT(STR,K-1)
--{:106}
;WHEN OUTPUT_TOK=>--{108:}{113:}
SEND_OUT(STR,0);
WHILE OUT_PTR>0 LOOP IF OUT_PTR<=LINE_LENGTH THEN BREAK_PTR:=OUT_PTR;
END IF;FLUSH_BUFFER;END LOOP;OUT_STATE:=MISC--{:113}
;K:=0;LOOP CUR_CHAR:=GET_OUTPUT;
EXIT WHEN(CUR_CHAR=OUTPUT_TOK)OR(STACK_PTR=0);K:=K+1;
FILE_NAME(K):=XCHR(CUR_CHAR);END LOOP;
IF K>0 THEN TEXT_IO.CLOSE(ADA_FILE);FN_LENGTH:=K;
IF NOT CREATE_ADA_FILE(FILE_NAME(1..K))THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Could not open file `"&FILE_NAME(1..K)&"'.");ERROR;
HISTORY:=FATAL_MESSAGE;RAISE END_OF_ATANGLE;END IF;F_LINE:=1;
ELSE TEXT_IO.NEW_LINE;TEXT_IO.PUT("! File name should have length > 0");
ERROR;END IF--{:108}
;WHEN FORCE_LINE=>--{113:}
SEND_OUT(STR,0);
WHILE OUT_PTR>0 LOOP IF OUT_PTR<=LINE_LENGTH THEN BREAK_PTR:=OUT_PTR;
END IF;FLUSH_BUFFER;END LOOP;OUT_STATE:=MISC--{:113}
;WHEN OTHERS=>TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Can't output ASCII code ");INT_NUMBER_IO.PUT(CUR_CHAR,1);
ERROR;END CASE;GOTO CONTINUE;<<GET_FRACTION>>--{111:}
LOOP IF K<LINE_LENGTH THEN K:=K+1;END IF;OUT_CONTRIB(K):=CUR_CHAR;
CUR_CHAR:=GET_OUTPUT;
IF(OUT_CONTRIB(K)=69)AND((CUR_CHAR=43)OR(CUR_CHAR=45))THEN IF K<
LINE_LENGTH THEN K:=K+1;END IF;OUT_CONTRIB(K):=CUR_CHAR;
CUR_CHAR:=GET_OUTPUT;ELSIF CUR_CHAR=101 THEN CUR_CHAR:=69;END IF;
EXIT WHEN(CUR_CHAR/=69)AND(CUR_CHAR NOT IN 48..57);END LOOP;
IF K=LINE_LENGTH THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Fraction too long");ERROR;END IF;SEND_OUT(FRAC,K);
GOTO RESWITCH--{:111}
;<<CONTINUE>>NULL;END LOOP;END SEND_THE_OUTPUT;--{:101}{114:}
PROCEDURE PHASE_II IS BEGIN--{100:}
IF TEXT_LINK(0)=0 THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! No output was specified.");
IF HISTORY=SPOTLESS THEN HISTORY:=HARMLESS_MESSAGE;END IF;
ELSE TEXT_IO.NEW_LINE;TEXT_IO.PUT("Writing the output file");NULL;
--{80:}
STACK_PTR:=1;BRACE_LEVEL:=0;CUR_NAME:=0;CUR_REPL:=TEXT_LINK(0);
ZO:=CUR_REPL MOD ZZ;CUR_BYTE:=TOK_START(CUR_REPL);
CUR_END:=TOK_START(CUR_REPL+ZZ);CUR_MOD:=0;--{:80}{93:}
OUT_STATE:=MISC;OUT_PTR:=0;BREAK_PTR:=0;SEMI_PTR:=0;OUT_BUF(0):=0;
LINE:=1;COMMENT_OUTPUT:=FALSE;--{:93}
SEND_THE_OUTPUT;--{95:}
BREAK_PTR:=OUT_PTR;SEMI_PTR:=0;FLUSH_BUFFER;
IF BRACE_LEVEL/=0 THEN TEXT_IO.NEW_LINE;
TEXT_IO.PUT("! Program ended at brace level ");
INT_NUMBER_IO.PUT(BRACE_LEVEL,1);ERROR;END IF;--{:95}
TEXT_IO.NEW_LINE;TEXT_IO.PUT("Done.");END IF--{:100}
;END PHASE_II;--{:114}
END OUTPUT_PHASE;--{:6}{7:}
