WITH TEXT_IO;WITH INT_NUMBER_IO;WITH TEXT_IO;PACKAGE DATA_STRUCTURES IS
--{14:}
MAX_BYTES:CONSTANT:=45000;MAX_NAMES:CONSTANT:=5000;
MAX_MODULES:CONSTANT:=2000;HASH_SIZE:CONSTANT:=353;
BUF_SIZE:CONSTANT:=100;LONGEST_NAME:CONSTANT:=400;
LONG_BUF_SIZE:CONSTANT:=500;LINE_LENGTH:CONSTANT:=80;
MAX_REFS:CONSTANT:=60000;MAX_TOKS:CONSTANT:=60000;
MAX_TEXTS:CONSTANT:=10000;MAX_SCRAPS:CONSTANT:=8000;
STACK_SIZE:CONSTANT:=800;--{:14}{15:}
TYPE HISTORY_TYPE IS(SPOTLESS,HARMLESS_MESSAGE,ERROR_MESSAGE,
FATAL_MESSAGE);HISTORY:HISTORY_TYPE:=SPOTLESS;--{:15}{16:}
SUBTYPE ASCII_CODE IS INTEGER RANGE 0..127;--{:16}{17:}
SUBTYPE TEXT_CHAR IS CHARACTER;SUBTYPE TEXT_FILE IS TEXT_IO.FILE_TYPE;
--{:17}{18:}
XORD:ARRAY(TEXT_CHAR)OF ASCII_CODE;XCHR:ARRAY(ASCII_CODE)OF TEXT_CHAR;
--{:18}{20:}
AND_SIGN:CONSTANT ASCII_CODE:=8#4#;NOT_SIGN:CONSTANT ASCII_CODE:=8#5#;
SET_ELEMENT_SIGN:CONSTANT ASCII_CODE:=8#6#;
TAB_MARK:CONSTANT ASCII_CODE:=8#11#;
LINE_FEED:CONSTANT ASCII_CODE:=8#12#;
FORM_FEED:CONSTANT ASCII_CODE:=8#14#;
CARRIAGE_RETURN:CONSTANT ASCII_CODE:=8#15#;
RIGHT_ARROW:CONSTANT ASCII_CODE:=8#21#;
BOX_SIGN:CONSTANT ASCII_CODE:=8#22#;
DOUBLE_STAR:CONSTANT ASCII_CODE:=8#23#;
LEFT_LABEL_BRACKET:CONSTANT ASCII_CODE:=8#24#;
RIGHT_LABEL_BRACKET:CONSTANT ASCII_CODE:=8#25#;
LEFT_ARROW:CONSTANT ASCII_CODE:=8#30#;
NOT_EQUAL:CONSTANT ASCII_CODE:=8#32#;
LESS_OR_EQUAL:CONSTANT ASCII_CODE:=8#34#;
GREATER_OR_EQUAL:CONSTANT ASCII_CODE:=8#35#;
EQUIVALENCE_SIGN:CONSTANT ASCII_CODE:=8#36#;
OR_SIGN:CONSTANT ASCII_CODE:=8#37#;--{:20}{26:}
AWEB_FILE:TEXT_FILE;CHANGE_FILE:TEXT_FILE;--{:26}{29:}
TEX_FILE:TEXT_FILE;--{:29}{31:}
TYPE BUFFER_TYPE IS ARRAY(INTEGER RANGE<>)OF ASCII_CODE;
SUBTYPE LONG_BUFFER_INDEX IS INTEGER RANGE 0..LONG_BUF_SIZE;
SUBTYPE BUFFER_INDEX IS LONG_BUFFER_INDEX RANGE 0..BUF_SIZE;
BUFFER:BUFFER_TYPE(BUFFER_INDEX);--{:31}{34:}
PHASE_ONE:BOOLEAN;PHASE_THREE:BOOLEAN;--{:34}{38:}
END_OF_AWEAVE:EXCEPTION;--{:38}{41:}
SUBTYPE EIGHT_BITS IS INTEGER RANGE 0..255;
SUBTYPE SIXTEEN_BITS IS INTEGER RANGE 0..65535;--{:41}{42:}
WW:CONSTANT INTEGER:=2;SUBTYPE W_RANGE IS INTEGER RANGE 0..WW-1;
SUBTYPE BYTE_INDEX IS INTEGER RANGE 0..MAX_BYTES;
SUBTYPE NAME_INDEX IS INTEGER RANGE 0..MAX_NAMES;
TYPE BYTE_MEMORY IS ARRAY(W_RANGE,BYTE_INDEX)OF ASCII_CODE;
--PRAGMA PACK(BYTE_MEMORY);
TYPE NAME_INFO IS ARRAY(NAME_INDEX)OF SIXTEEN_BITS;BYTE_MEM:BYTE_MEMORY;
BYTE_START:NAME_INFO;LINK:NAME_INFO;ILK:NAME_INFO;XREF:NAME_INFO;
--{:42}{43:}
SUBTYPE NAME_POINTER IS NAME_INDEX;NAME_PTR:NAME_POINTER:=1;
BYTE_PTR:ARRAY(W_RANGE)OF BYTE_INDEX:=(OTHERS=>0);--{:43}{45:}
NORMAL:CONSTANT INTEGER:=0;ROMAN:CONSTANT INTEGER:=1;
WILDCARD:CONSTANT INTEGER:=2;ITALIC:CONSTANT INTEGER:=3;
BOLD_FACE:CONSTANT INTEGER:=4;SLANTED:CONSTANT INTEGER:=5;
TYPEWRITER:CONSTANT INTEGER:=6;PREDEFINED:CONSTANT INTEGER:=7;
ACCEPT_LIKE:CONSTANT INTEGER:=8;ALL_LIKE:CONSTANT INTEGER:=9;
AND_LIKE:CONSTANT INTEGER:=10;ARRAY_LIKE:CONSTANT INTEGER:=11;
AT_LIKE:CONSTANT INTEGER:=12;BEGIN_LIKE:CONSTANT INTEGER:=13;
BODY_LIKE:CONSTANT INTEGER:=14;CASE_LIKE:CONSTANT INTEGER:=15;
DECLARE_LIKE:CONSTANT INTEGER:=16;ELSE_LIKE:CONSTANT INTEGER:=17;
ELSIF_LIKE:CONSTANT INTEGER:=18;END_LIKE:CONSTANT INTEGER:=19;
EXCEPTION_LIKE:CONSTANT INTEGER:=20;GENERIC_LIKE:CONSTANT INTEGER:=21;
GOTO_LIKE:CONSTANT INTEGER:=22;IF_LIKE:CONSTANT INTEGER:=23;
IN_LIKE:CONSTANT INTEGER:=24;IS_LIKE:CONSTANT INTEGER:=25;
LOOP_LIKE:CONSTANT INTEGER:=26;MOD_LIKE:CONSTANT INTEGER:=27;
NEW_LIKE:CONSTANT INTEGER:=28;NOT_LIKE:CONSTANT INTEGER:=29;
OF_LIKE:CONSTANT INTEGER:=30;OR_LIKE:CONSTANT INTEGER:=31;
PRAGMA_LIKE:CONSTANT INTEGER:=32;PRIVATE_LIKE:CONSTANT INTEGER:=33;
PROC_LIKE:CONSTANT INTEGER:=34;RANGE_LIKE:CONSTANT INTEGER:=35;
RECORD_LIKE:CONSTANT INTEGER:=36;RETURN_LIKE:CONSTANT INTEGER:=37;
SEPARATE_LIKE:CONSTANT INTEGER:=38;THEN_LIKE:CONSTANT INTEGER:=39;
TYPE_LIKE:CONSTANT INTEGER:=40;WHEN_LIKE:CONSTANT INTEGER:=41;
WITH_LIKE:CONSTANT INTEGER:=42;--{:45}{46:}
LLINK:NAME_INFO RENAMES LINK;RLINK:NAME_INFO RENAMES ILK;
ROOT:SIXTEEN_BITS RENAMES RLINK(0);--{:46}{50:}
SUBTYPE MODULE_INDEX IS INTEGER RANGE 0..MAX_MODULES;
MODULE_COUNT:MODULE_INDEX;CHANGED_MODULE:ARRAY(MODULE_INDEX)OF BOOLEAN;
CHANGE_EXISTS:BOOLEAN;--{:50}{51:}
DEF_FLAG:CONSTANT INTEGER:=10240;
BODY_FLAG:CONSTANT INTEGER:=DEF_FLAG+DEF_FLAG;
SUBTYPE XREF_NUMBER IS INTEGER RANGE 0..MAX_REFS;
TYPE XMEM_FIELD IS RECORD NUM_FIELD:SIXTEEN_BITS;
XLINK_FIELD:SIXTEEN_BITS;END RECORD;
XMEM:ARRAY(XREF_NUMBER)OF XMEM_FIELD;XREF_PTR:XREF_NUMBER:=0;
XREF_SWITCH,MOD_XREF_SWITCH:INTEGER RANGE 0..BODY_FLAG:=0;--{:51}{56:}
SUBTYPE TEXT_POINTER IS INTEGER RANGE 0..MAX_TEXTS;--{:56}{57:}
SUBTYPE TOKEN_INDEX IS INTEGER RANGE 0..MAX_TOKS;
TOK_MEM:ARRAY(TOKEN_INDEX)OF SIXTEEN_BITS;
TOK_START:ARRAY(TEXT_POINTER)OF SIXTEEN_BITS;TEXT_PTR:TEXT_POINTER:=1;
TOK_PTR:TOKEN_INDEX:=1;
--MAX_TOK_PTR,MAX_TXT_PTR:TOKEN_INDEX:=1;
--{:57}{59:}
ID_FIRST:BUFFER_INDEX;ID_LOC:BUFFER_INDEX;
SUBTYPE HASH_INDEX IS INTEGER RANGE 0..HASH_SIZE;
HASH:ARRAY(HASH_INDEX)OF SIXTEEN_BITS:=(OTHERS=>0);--{:59}{66:}
CUR_NAME:NAME_POINTER;--{:66}{73:}
SUBTYPE LONG_NAME_INDEX IS INTEGER RANGE 0..LONGEST_NAME;
MOD_TEXT:ARRAY(LONG_NAME_INDEX)OF ASCII_CODE;--{:73}{74:}
TYPE COMPARE IS(LESS,EQUAL,GREATER,PREFIX,EXTENSION);--{:74}{82:}
LINE:INTEGER;OTHER_LINE:INTEGER;TEMP_LINE:INTEGER;LIMIT:BUFFER_INDEX;
LOC:BUFFER_INDEX;INPUT_HAS_ENDED:BOOLEAN;CHANGING:BOOLEAN;--{:82}{84:}
CHANGE_BUFFER:BUFFER_TYPE(BUFFER_INDEX);CHANGE_LIMIT:BUFFER_INDEX;
--{:84}{99:}
IGNORE:CONSTANT EIGHT_BITS:=0;VERBATIM:CONSTANT EIGHT_BITS:=8#2#;
FORCE_LINE:CONSTANT EIGHT_BITS:=8#3#;
BEGIN_COMMENT:CONSTANT EIGHT_BITS:=8#11#;
END_COMMENT:CONSTANT EIGHT_BITS:=8#12#;
CHARACTER_TOK:CONSTANT EIGHT_BITS:=8#14#;
ASCII_TOK:CONSTANT EIGHT_BITS:=8#15#;
OUTPUT_TOK:CONSTANT EIGHT_BITS:=8#16#;
DOUBLE_DOT:CONSTANT EIGHT_BITS:=8#40#;
NO_UNDERLINE:CONSTANT EIGHT_BITS:=8#175#;
UNDERLINE:CONSTANT EIGHT_BITS:=8#176#;PARAM:CONSTANT EIGHT_BITS:=8#177#;
XREF_ROMAN:CONSTANT EIGHT_BITS:=8#204#;
XREF_WILDCARD:CONSTANT EIGHT_BITS:=8#205#;
XREF_ITALIC:CONSTANT EIGHT_BITS:=8#206#;
XREF_BOLD_FACE:CONSTANT EIGHT_BITS:=8#207#;
XREF_SLANTED:CONSTANT EIGHT_BITS:=8#210#;
XREF_TYPEWRITER:CONSTANT EIGHT_BITS:=8#211#;
XREF_PREDEFINED:CONSTANT EIGHT_BITS:=8#212#;
XREF_RESERVED:CONSTANT EIGHT_BITS:=8#213#;
TEX_STRING:CONSTANT EIGHT_BITS:=8#214#;JOIN:CONSTANT EIGHT_BITS:=8#215#;
THIN_SPACE:CONSTANT EIGHT_BITS:=8#216#;
MATH_BREAK:CONSTANT EIGHT_BITS:=8#217#;
LINE_BREAK:CONSTANT EIGHT_BITS:=8#220#;
BIG_LINE_BREAK:CONSTANT EIGHT_BITS:=8#221#;
NO_LINE_BREAK:CONSTANT EIGHT_BITS:=8#222#;
PSEUDO_SEMI:CONSTANT EIGHT_BITS:=8#223#;
FORMAT:CONSTANT EIGHT_BITS:=8#224#;
DEFINITION:CONSTANT EIGHT_BITS:=8#225#;
BEGIN_ADA:CONSTANT EIGHT_BITS:=8#226#;
MODULE_NAME:CONSTANT EIGHT_BITS:=8#227#;
NEW_MODULE:CONSTANT EIGHT_BITS:=8#230#;--{:99}{109:}
EXPONENT:CONSTANT EIGHT_BITS:=8#201#;STR:CONSTANT EIGHT_BITS:=8#202#;
IDENTIFIER:CONSTANT EIGHT_BITS:=8#203#;CUR_MODULE:NAME_POINTER;
SCANNING_BASED_NUMBER:BOOLEAN:=FALSE;--{:109}{125:}
NEXT_CONTROL:EIGHT_BITS;--{:125}{131:}
LHS,RHS:NAME_POINTER;TEMP_ILK:SIXTEEN_BITS;--{:131}{136:}
CUR_XREF:XREF_NUMBER;--{:136}{139:}
SUBTYPE LENGTH_INDEX IS INTEGER RANGE 0..LINE_LENGTH;
OUT_BUF:ARRAY(LENGTH_INDEX)OF ASCII_CODE;OUT_PTR:LENGTH_INDEX;
OUT_LINE:INTEGER;--{:139}{150:}
DIG:ARRAY(0..4)OF INTEGER RANGE 0..9;--{:150}{167:}
ACCEPT_SCRAP:CONSTANT EIGHT_BITS:=1;AND_SCRAP:CONSTANT EIGHT_BITS:=2;
ARROW:CONSTANT EIGHT_BITS:=3;BASE:CONSTANT EIGHT_BITS:=4;
BEGIN_LABEL_SCRAP:CONSTANT EIGHT_BITS:=5;
BEGINNING:CONSTANT EIGHT_BITS:=6;CASE_SCRAP:CONSTANT EIGHT_BITS:=7;
CLAUSE:CONSTANT EIGHT_BITS:=8;CLOSE_SCRAP:CONSTANT EIGHT_BITS:=9;
COLON:CONSTANT EIGHT_BITS:=10;DECL:CONSTANT EIGHT_BITS:=11;
DIGIT_SCRAP:CONSTANT EIGHT_BITS:=12;ELSE_SCRAP:CONSTANT EIGHT_BITS:=13;
END_LABEL_SCRAP:CONSTANT EIGHT_BITS:=14;ENDING:CONSTANT EIGHT_BITS:=15;
EXCEPTION_SCRAP:CONSTANT EIGHT_BITS:=16;EXP:CONSTANT EIGHT_BITS:=17;
FOLLOWS:CONSTANT EIGHT_BITS:=18;GENERIC_SCRAP:CONSTANT EIGHT_BITS:=19;
GPROC:CONSTANT EIGHT_BITS:=20;IF_SCRAP:CONSTANT EIGHT_BITS:=21;
IN_SCRAP:CONSTANT EIGHT_BITS:=22;LABEL:CONSTANT EIGHT_BITS:=23;
LOOP_SCRAP:CONSTANT EIGHT_BITS:=24;MATH:CONSTANT EIGHT_BITS:=25;
MOD_SCRAP:CONSTANT EIGHT_BITS:=26;NEW_SCRAP:CONSTANT EIGHT_BITS:=27;
NOT_SCRAP:CONSTANT EIGHT_BITS:=28;OPEN_SCRAP:CONSTANT EIGHT_BITS:=29;
PERIOD:CONSTANT EIGHT_BITS:=30;PRIVATE_SCRAP:CONSTANT EIGHT_BITS:=31;
PROC:CONSTANT EIGHT_BITS:=32;RECORD_SCRAP:CONSTANT EIGHT_BITS:=33;
RETURN_SCRAP:CONSTANT EIGHT_BITS:=34;SEMI:CONSTANT EIGHT_BITS:=35;
SEPARATE_SCRAP:CONSTANT EIGHT_BITS:=36;STMT:CONSTANT EIGHT_BITS:=37;
TERMINATOR:CONSTANT EIGHT_BITS:=38;THEN_SCRAP:CONSTANT EIGHT_BITS:=39;
WHEN_SCRAP:CONSTANT EIGHT_BITS:=40;WITH_SCRAP:CONSTANT EIGHT_BITS:=41;
--{:167}{168:}
MATH_BIN:CONSTANT EIGHT_BITS:=8#204#;
MATH_REL:CONSTANT EIGHT_BITS:=8#205#;
MATH_OP:CONSTANT EIGHT_BITS:=8#206#;PDOLLAR:CONSTANT EIGHT_BITS:=8#207#;
PSPACE:CONSTANT EIGHT_BITS:=8#210#;SSPACE:CONSTANT EIGHT_BITS:=8#211#;
BIG_CANCEL:CONSTANT EIGHT_BITS:=8#212#;
CANCEL:CONSTANT EIGHT_BITS:=8#213#;INDENT:CONSTANT EIGHT_BITS:=8#214#;
OUTDENT:CONSTANT EIGHT_BITS:=8#215#;OPT:CONSTANT EIGHT_BITS:=8#216#;
BACKUP:CONSTANT EIGHT_BITS:=8#217#;
BREAK_SPACE:CONSTANT EIGHT_BITS:=8#220#;
FORCE:CONSTANT EIGHT_BITS:=8#221#;BIG_FORCE:CONSTANT EIGHT_BITS:=8#222#;
END_TRANSLATION:CONSTANT EIGHT_BITS:=8#223#;--{:168}{171:}
SUBTYPE SCRAP_INDEX IS INTEGER RANGE 0..MAX_SCRAPS;
TYPE CAT_TYPE IS ARRAY(SCRAP_INDEX)OF EIGHT_BITS;
TYPE TRANS_TYPE IS ARRAY(SCRAP_INDEX)OF INTEGER RANGE 0..10239;
CAT:CAT_TYPE;TRANS:TRANS_TYPE;PP:SCRAP_INDEX;SCRAP_BASE:SCRAP_INDEX:=1;
SCRAP_PTR:SCRAP_INDEX:=0;LO_PTR:SCRAP_INDEX;HI_PTR:SCRAP_INDEX;
--MAX_SCR_PTR:SCRAP_INDEX:=0;
--{:171}{172:}
ID_FLAG:CONSTANT SIXTEEN_BITS:=10240;
RES_FLAG:CONSTANT SIXTEEN_BITS:=20480;
MOD_FLAG:CONSTANT SIXTEEN_BITS:=30720;
TOK_FLAG:CONSTANT SIXTEEN_BITS:=40960;
INNER_TOK_FLAG:CONSTANT SIXTEEN_BITS:=51200;--{:172}{243:}
TYPE OUTPUT_MODE IS(INNER,OUTER);
TYPE OUTPUT_STATE IS RECORD END_FIELD:SIXTEEN_BITS;
TOK_FIELD:SIXTEEN_BITS;MODE_FIELD:OUTPUT_MODE;END RECORD;
CUR_STATE:OUTPUT_STATE;
STACK:ARRAY(INTEGER RANGE 1..STACK_SIZE)OF OUTPUT_STATE;
STACK_PTR:INTEGER RANGE 0..STACK_SIZE;
--MAX_STACK_PTR:INTEGER RANGE 0..STACK_SIZE:=0;
CUR_END:SIXTEEN_BITS RENAMES CUR_STATE.END_FIELD;
CUR_TOK:SIXTEEN_BITS RENAMES CUR_STATE.TOK_FIELD;
CUR_MODE:OUTPUT_MODE RENAMES CUR_STATE.MODE_FIELD;--{:243}{247:}
RES_WORD:CONSTANT EIGHT_BITS:=8#201#;
MOD_NAME:CONSTANT EIGHT_BITS:=8#200#;--{:247}{263:}
SAVE_LINE:INTEGER;SAVE_PLACE:SIXTEEN_BITS;--{:263}{271:}
THIS_MODULE:NAME_POINTER;--{:271}{276:}
NEXT_XREF,THIS_XREF,FIRST_XREF,MID_XREF:XREF_NUMBER;--{:276}{283:}
K_MODULE:MODULE_INDEX;--{:283}{285:}
BUCKET:ARRAY(ASCII_CODE)OF NAME_POINTER;NEXT_NAME:NAME_POINTER;
BLINK:NAME_INFO;C:ASCII_CODE;--{:285}{287:}
DEPTH:CAT_TYPE RENAMES CAT;HEAD:TRANS_TYPE RENAMES TRANS;
SORT_PTR:SCRAP_INDEX RENAMES SCRAP_PTR;MAX_SORTS:CONSTANT:=MAX_SCRAPS;
CUR_DEPTH:EIGHT_BITS;CUR_BYTE:BYTE_INDEX;CUR_BANK:W_RANGE;
CUR_VAL:SIXTEEN_BITS;
--MAX_SORT_PTR:INTEGER RANGE 0..MAX_SORTS:=0;
--{:287}{288:}
COLLATE:ARRAY(0..100)OF ASCII_CODE;--{:288}{290:}
INFINITY:CONSTANT EIGHT_BITS:=255;--{:290}{307:}
OPENED:BOOLEAN:=FALSE;--{:307}{48:}
PROCEDURE PRINT_ID(P:NAME_POINTER);--{:48}{53:}
PROCEDURE NEW_XREF(P:NAME_POINTER);
PROCEDURE NEW_MOD_XREF(P:NAME_POINTER);--{:53}
PROCEDURE INITIALIZE;END DATA_STRUCTURES;
