WITH TEXT_IO,INT_NUMBER_IO;WITH INPUT_OUTPUT;USE INPUT_OUTPUT;
WITH SEARCHING;USE SEARCHING;WITH LEXICAL_SCANNING;USE LEXICAL_SCANNING;
PACKAGE BODY FIRST_PHASE IS--{129:}
PROCEDURE ADA_XREF IS P:NAME_POINTER;I:INTEGER;
BEGIN WHILE NEXT_CONTROL<FORMAT LOOP IF NEXT_CONTROL IN IDENTIFIER..
XREF_PREDEFINED THEN P:=ID_LOOKUP(NEXT_CONTROL-IDENTIFIER);
IF(ILK(P)=BODY_LIKE)OR(ILK(P)=TYPE_LIKE)THEN XREF_SWITCH:=0;END IF;
NEW_XREF(P);
IF(ILK(P)=PROC_LIKE)OR(ILK(P)=TYPE_LIKE)THEN XREF_SWITCH:=DEF_FLAG;
ELSIF(ILK(P)=ACCEPT_LIKE)OR(ILK(P)=BODY_LIKE)THEN XREF_SWITCH:=BODY_FLAG
;END IF;ELSIF NEXT_CONTROL=XREF_RESERVED THEN P:=ID_LOOKUP(NORMAL);
I:=ILK(P);ILK(P):=NORMAL;NEW_XREF(P);ILK(P):=I;END IF;
NEXT_CONTROL:=GET_NEXT;
IF(NEXT_CONTROL=124)OR(NEXT_CONTROL=123)THEN RETURN;END IF;END LOOP;
END ADA_XREF;--{:129}{130:}
PROCEDURE OUTER_XREF IS BAL:EIGHT_BITS;
BEGIN WHILE NEXT_CONTROL<FORMAT LOOP IF NEXT_CONTROL/=123 THEN ADA_XREF;
ELSE BAL:=SKIP_COMMENT(1);NEXT_CONTROL:=124;WHILE BAL>0 LOOP ADA_XREF;
IF NEXT_CONTROL=124 THEN BAL:=SKIP_COMMENT(BAL);ELSE BAL:=0;END IF;
END LOOP;END IF;END LOOP;END OUTER_XREF;--{:130}{137:}
PROCEDURE MOD_CHECK(P:NAME_POINTER)IS BEGIN IF P>0 THEN MOD_CHECK(LLINK(
P));CUR_XREF:=XREF(P);
IF XMEM(CUR_XREF).NUM_FIELD<DEF_FLAG THEN TEXT_IO.NEW_LINE(TEXT_IO.
STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Never defined: <");PRINT_ID(P);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,">");
IF HISTORY=SPOTLESS THEN HISTORY:=HARMLESS_MESSAGE;END IF;END IF;
WHILE XMEM(CUR_XREF).NUM_FIELD>=DEF_FLAG LOOP CUR_XREF:=XMEM(CUR_XREF).
XLINK_FIELD;END LOOP;
IF CUR_XREF=0 THEN TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Never used: <");PRINT_ID(P);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,">");
IF HISTORY=SPOTLESS THEN HISTORY:=HARMLESS_MESSAGE;END IF;END IF;
MOD_CHECK(RLINK(P));END IF;END MOD_CHECK;--{:137}{302:}
PROCEDURE PHASE_I IS BEGIN--{126:}
PHASE_ONE:=TRUE;PHASE_THREE:=FALSE;RESET_INPUT;MODULE_COUNT:=0;
SKIP_LIMBO;CHANGE_EXISTS:=FALSE;WHILE NOT INPUT_HAS_ENDED LOOP--{127:}
MODULE_COUNT:=MODULE_COUNT+1;
IF MODULE_COUNT=MAX_MODULES THEN TEXT_IO.NEW_LINE(TEXT_IO.
STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Sorry, "&"section number"&
" capacity exceeded");ERROR;HISTORY:=FATAL_MESSAGE;RAISE END_OF_AWEAVE;
END IF;CHANGED_MODULE(MODULE_COUNT):=FALSE;
IF BUFFER(LOC-1)=42 THEN TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"*");
INT_NUMBER_IO.PUT(TEXT_IO.STANDARD_OUTPUT,MODULE_COUNT,1);NULL;END IF;
--{132:}
LOOP NEXT_CONTROL:=SKIP_TEX;
CASE NEXT_CONTROL IS WHEN UNDERLINE=>IF XREF_SWITCH<BODY_FLAG THEN
XREF_SWITCH:=XREF_SWITCH+DEF_FLAG;END IF;
WHEN NO_UNDERLINE=>IF XREF_SWITCH>0 THEN XREF_SWITCH:=XREF_SWITCH-
DEF_FLAG;END IF;WHEN 124=>ADA_XREF;
WHEN XREF_ROMAN..XREF_PREDEFINED!MODULE_NAME=>LOC:=LOC-2;
NEXT_CONTROL:=GET_NEXT;
IF NEXT_CONTROL/=MODULE_NAME THEN NEW_XREF(ID_LOOKUP(NEXT_CONTROL-
IDENTIFIER));END IF;WHEN XREF_RESERVED=>LOC:=LOC-2;
NEXT_CONTROL:=GET_NEXT;LHS:=ID_LOOKUP(NORMAL);TEMP_ILK:=ILK(LHS);
ILK(LHS):=NORMAL;NEW_XREF(LHS);ILK(LHS):=TEMP_ILK;WHEN OTHERS=>NULL;
END CASE;EXIT WHEN NEXT_CONTROL>=FORMAT;END LOOP--{:132}
;--{133:}
WHILE NEXT_CONTROL<=DEFINITION LOOP XREF_SWITCH:=DEF_FLAG;
IF NEXT_CONTROL=DEFINITION THEN NEXT_CONTROL:=GET_NEXT;ELSE--{134:}
NEXT_CONTROL:=GET_NEXT;
IF NEXT_CONTROL=IDENTIFIER THEN LHS:=ID_LOOKUP(NORMAL);ILK(LHS):=NORMAL;
NEW_XREF(LHS);NEXT_CONTROL:=GET_NEXT;
IF NEXT_CONTROL=EQUIVALENCE_SIGN THEN NEXT_CONTROL:=GET_NEXT;
IF NEXT_CONTROL=IDENTIFIER THEN RHS:=ID_LOOKUP(NORMAL);
ILK(LHS):=ILK(RHS);ILK(RHS):=NORMAL;NEW_XREF(RHS);ILK(RHS):=ILK(LHS);
NEXT_CONTROL:=GET_NEXT;END IF;END IF;END IF--{:134}
;END IF;OUTER_XREF;END LOOP--{:133}
;--{135:}
IF NEXT_CONTROL<=MODULE_NAME THEN IF NEXT_CONTROL=BEGIN_ADA THEN
MOD_XREF_SWITCH:=0;ELSE MOD_XREF_SWITCH:=DEF_FLAG;END IF;
LOOP IF NEXT_CONTROL=MODULE_NAME THEN NEW_MOD_XREF(CUR_MODULE);END IF;
NEXT_CONTROL:=GET_NEXT;OUTER_XREF;EXIT WHEN NEXT_CONTROL>MODULE_NAME;
END LOOP;END IF--{:135}
;IF CHANGED_MODULE(MODULE_COUNT)THEN CHANGE_EXISTS:=TRUE;END IF--{:127}
;END LOOP;CHANGED_MODULE(MODULE_COUNT):=CHANGE_EXISTS;PHASE_ONE:=FALSE;
--{138:}
MOD_CHECK(ROOT)--{:138}{:126}
;END PHASE_I;--{:302}
END FIRST_PHASE;--{:7}{8:}
