WITH TEXT_IO;WITH DATA_STRUCTURES;USE DATA_STRUCTURES;
PACKAGE INPUT_OUTPUT IS--{27:}
PROCEDURE OPEN_A_FILE(F:IN OUT TEXT_FILE;MODE_OF_FILE:TEXT_IO.FILE_MODE;
DEFAULT_NAME:STRING;SUCCESS:OUT BOOLEAN);
FUNCTION CREATE_TEX_FILE(TEX_FILE_NAME:STRING)RETURN BOOLEAN;
--{:27}{32:}
FUNCTION INPUT_LN(F:TEXT_FILE)RETURN BOOLEAN;--{:32}{35:}
PROCEDURE ERROR;--{:35}
END INPUT_OUTPUT;
