WITH DATA_STRUCTURES;USE DATA_STRUCTURES;PACKAGE LEXICAL_SCANNING IS
--{92:}
PROCEDURE RESET_INPUT;--{:92}{94:}
PROCEDURE GET_LINE;--{:94}{100:}
FUNCTION CONTROL_CODE(C:ASCII_CODE)RETURN EIGHT_BITS;--{:100}{102:}
PROCEDURE SKIP_LIMBO;--{:102}{104:}
FUNCTION SKIP_TEX RETURN EIGHT_BITS;--{:104}{106:}
FUNCTION SKIP_COMMENT(BAL:EIGHT_BITS)RETURN EIGHT_BITS;--{:106}{110:}
FUNCTION GET_NEXT RETURN EIGHT_BITS;--{:110}
END LEXICAL_SCANNING;
