WITH TEXT_IO,INT_NUMBER_IO;WITH INPUT_OUTPUT;USE INPUT_OUTPUT;
WITH SEARCHING;USE SEARCHING;PACKAGE BODY LEXICAL_SCANNING IS--{85:}
FUNCTION LINES_DONT_MATCH RETURN BOOLEAN IS BEGIN IF CHANGE_LIMIT/=LIMIT
THEN RETURN TRUE;END IF;
IF(LIMIT>0)AND THEN CHANGE_BUFFER(0..LIMIT-1)/=BUFFER(0..LIMIT-1)THEN
RETURN TRUE;END IF;RETURN FALSE;END LINES_DONT_MATCH;--{:85}{86:}
PROCEDURE PRIME_THE_CHANGE_BUFFER IS BEGIN CHANGE_LIMIT:=0;--{87:}
LOOP LINE:=LINE+1;IF NOT INPUT_LN(CHANGE_FILE)THEN RETURN;
ELSIF LIMIT<2 THEN GOTO CONTINUE;ELSIF BUFFER(0)/=64 THEN GOTO CONTINUE;
ELSIF BUFFER(1)IN 88..90 THEN BUFFER(1):=BUFFER(1)+8#40#;END IF;
EXIT WHEN BUFFER(1)=120;IF BUFFER(1)IN 121..122 THEN LOC:=2;
IF NOT PHASE_ONE THEN TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Where is the matching @x?");
ERROR;END IF;END IF;<<CONTINUE>>NULL;END LOOP--{:87}
;--{88:}
LOOP LINE:=LINE+1;
IF NOT INPUT_LN(CHANGE_FILE)THEN IF NOT PHASE_ONE THEN TEXT_IO.NEW_LINE(
TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Change file ended after @x");
ERROR;END IF;RETURN;END IF;EXIT WHEN LIMIT>0;END LOOP--{:88}
;--{89:}
CHANGE_LIMIT:=LIMIT;
IF LIMIT>0 THEN CHANGE_BUFFER(0..LIMIT-1):=BUFFER(0..LIMIT-1);END IF
--{:89}
;END PRIME_THE_CHANGE_BUFFER;--{:86}{90:}
PROCEDURE CHECK_CHANGE IS N:INTEGER:=0;
BEGIN IF LINES_DONT_MATCH THEN RETURN;END IF;
LOOP CHANGING:=NOT CHANGING;TEMP_LINE:=OTHER_LINE;OTHER_LINE:=LINE;
LINE:=TEMP_LINE;LINE:=LINE+1;
IF NOT INPUT_LN(CHANGE_FILE)THEN IF NOT PHASE_ONE THEN TEXT_IO.NEW_LINE(
TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Change file ended before @y");
ERROR;END IF;CHANGE_LIMIT:=0;CHANGING:=NOT CHANGING;
TEMP_LINE:=OTHER_LINE;OTHER_LINE:=LINE;LINE:=TEMP_LINE;RETURN;END IF;
--{91:}
IF(LIMIT>1)AND THEN BUFFER(0)=64 THEN IF BUFFER(1)IN 88..90 THEN BUFFER(
1):=BUFFER(1)+8#40#;END IF;
IF(BUFFER(1)=120)OR(BUFFER(1)=122)THEN LOC:=2;
IF NOT PHASE_ONE THEN TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Where is the matching @y?");
ERROR;END IF;ELSIF BUFFER(1)=121 THEN IF N>0 THEN LOC:=2;
TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Hmm... ");
INT_NUMBER_IO.PUT(TEXT_IO.STANDARD_OUTPUT,N,1);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,
" of the preceding lines failed to match");ERROR;END IF;RETURN;END IF;
END IF--{:91}
;--{89:}
CHANGE_LIMIT:=LIMIT;
IF LIMIT>0 THEN CHANGE_BUFFER(0..LIMIT-1):=BUFFER(0..LIMIT-1);END IF
--{:89}
;CHANGING:=NOT CHANGING;TEMP_LINE:=OTHER_LINE;OTHER_LINE:=LINE;
LINE:=TEMP_LINE;LINE:=LINE+1;
IF NOT INPUT_LN(AWEB_FILE)THEN IF NOT PHASE_ONE THEN TEXT_IO.NEW_LINE(
TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! AWEB file ended during a change")
;ERROR;END IF;INPUT_HAS_ENDED:=TRUE;RETURN;END IF;
IF LINES_DONT_MATCH THEN N:=N+1;END IF;END LOOP;END CHECK_CHANGE;
--{:90}{93:}
PROCEDURE RESET_INPUT IS BEGIN TEXT_IO.RESET(AWEB_FILE);
IF TEXT_IO.IS_OPEN(CHANGE_FILE)THEN TEXT_IO.RESET(CHANGE_FILE);END IF;
LINE:=0;OTHER_LINE:=0;CHANGING:=TRUE;PRIME_THE_CHANGE_BUFFER;
CHANGING:=NOT CHANGING;TEMP_LINE:=OTHER_LINE;OTHER_LINE:=LINE;
LINE:=TEMP_LINE;LIMIT:=0;LOC:=1;BUFFER(0):=32;INPUT_HAS_ENDED:=FALSE;
END RESET_INPUT;--{:93}{95:}
PROCEDURE GET_LINE IS BEGIN<<RESTART>>IF CHANGING THEN CHANGED_MODULE(
MODULE_COUNT):=TRUE;ELSE--{96:}
LINE:=LINE+1;IF NOT INPUT_LN(AWEB_FILE)THEN INPUT_HAS_ENDED:=TRUE;
ELSIF(LIMIT=CHANGE_LIMIT)AND((BUFFER(0)=CHANGE_BUFFER(0))AND(
CHANGE_LIMIT>0))THEN CHECK_CHANGE;END IF--{:96}
;END IF;IF CHANGING THEN--{97:}
LINE:=LINE+1;
IF NOT INPUT_LN(CHANGE_FILE)THEN IF NOT PHASE_ONE THEN TEXT_IO.NEW_LINE(
TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Change file ended without @z");
ERROR;END IF;BUFFER(0..1):=(64,122);LIMIT:=2;END IF;
IF(LIMIT>1)AND THEN(BUFFER(0)=64)THEN IF BUFFER(1)IN 88..90 THEN BUFFER(
1):=BUFFER(1)+8#40#;END IF;IF BUFFER(1)IN 120..121 THEN LOC:=2;
IF NOT PHASE_ONE THEN TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Where is the matching @z?");
ERROR;END IF;ELSIF BUFFER(1)=122 THEN PRIME_THE_CHANGE_BUFFER;
CHANGING:=NOT CHANGING;TEMP_LINE:=OTHER_LINE;OTHER_LINE:=LINE;
LINE:=TEMP_LINE;END IF;END IF--{:97}
;IF NOT CHANGING THEN CHANGED_MODULE(MODULE_COUNT):=TRUE;GOTO RESTART;
END IF;END IF;LOC:=0;BUFFER(LIMIT):=32;END GET_LINE;--{:95}{101:}
FUNCTION CONTROL_CODE(C:ASCII_CODE)RETURN EIGHT_BITS IS BEGIN CASE C IS
WHEN 64=>RETURN 64;WHEN 39=>RETURN ASCII_TOK;
WHEN 126=>RETURN OUTPUT_TOK;WHEN 32!TAB_MARK!42=>RETURN NEW_MODULE;
WHEN 61=>RETURN VERBATIM;WHEN 92=>RETURN FORCE_LINE;
WHEN 68!100=>RETURN DEFINITION;WHEN 70!102=>RETURN FORMAT;
WHEN 123=>RETURN BEGIN_COMMENT;WHEN 125=>RETURN END_COMMENT;
WHEN 65!97=>RETURN BEGIN_ADA;WHEN 38=>RETURN JOIN;
WHEN 60=>RETURN MODULE_NAME;
WHEN 62=>IF NOT PHASE_ONE THEN TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT)
;TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Extra @>");ERROR;END IF;
RETURN IGNORE;WHEN 84!116=>RETURN TEX_STRING;WHEN 33=>RETURN UNDERLINE;
WHEN 63=>RETURN NO_UNDERLINE;WHEN 94=>RETURN XREF_ROMAN;
WHEN 58=>RETURN XREF_WILDCARD;WHEN 105!73=>RETURN XREF_ITALIC;
WHEN 98!66=>RETURN XREF_BOLD_FACE;WHEN 115!83=>RETURN XREF_SLANTED;
WHEN 112!80=>RETURN XREF_PREDEFINED;WHEN 114!82=>RETURN XREF_RESERVED;
WHEN 46=>RETURN XREF_TYPEWRITER;WHEN 44=>RETURN THIN_SPACE;
WHEN 124=>RETURN MATH_BREAK;WHEN 47=>RETURN LINE_BREAK;
WHEN 35=>RETURN BIG_LINE_BREAK;WHEN 43=>RETURN NO_LINE_BREAK;
WHEN 59=>RETURN PSEUDO_SEMI;
WHEN OTHERS=>IF NOT PHASE_ONE THEN TEXT_IO.NEW_LINE(TEXT_IO.
STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Unknown control code");ERROR;
END IF;RETURN IGNORE;END CASE;END CONTROL_CODE;--{:101}{103:}
PROCEDURE SKIP_LIMBO IS C:ASCII_CODE;
BEGIN LOOP IF LOC>LIMIT THEN GET_LINE;IF INPUT_HAS_ENDED THEN RETURN;
END IF;ELSE BUFFER(LIMIT+1):=64;WHILE BUFFER(LOC)/=64 LOOP LOC:=LOC+1;
END LOOP;IF LOC<=LIMIT THEN LOC:=LOC+2;C:=BUFFER(LOC-1);
IF(C=32)OR(C=TAB_MARK)OR(C=42)THEN RETURN;END IF;END IF;END IF;END LOOP;
END SKIP_LIMBO;--{:103}{105:}
FUNCTION SKIP_TEX RETURN EIGHT_BITS IS C:EIGHT_BITS;
BEGIN LOOP IF LOC>LIMIT THEN GET_LINE;
IF INPUT_HAS_ENDED THEN RETURN NEW_MODULE;END IF;END IF;
BUFFER(LIMIT+1):=64;LOOP C:=BUFFER(LOC);LOC:=LOC+1;
IF C=124 THEN RETURN 124;END IF;EXIT WHEN C=64;END LOOP;
IF LOC<=LIMIT THEN C:=CONTROL_CODE(BUFFER(LOC));LOC:=LOC+1;RETURN C;
END IF;END LOOP;END SKIP_TEX;--{:105}{107:}
FUNCTION SKIP_COMMENT(BAL:EIGHT_BITS)RETURN EIGHT_BITS IS B:EIGHT_BITS:=
BAL;C:ASCII_CODE;BEGIN LOOP IF LOC>LIMIT THEN GET_LINE;
IF INPUT_HAS_ENDED THEN RETURN 0;END IF;END IF;C:=BUFFER(LOC);
LOC:=LOC+1;IF C=124 THEN RETURN B;END IF;--{108:}
IF C=64 THEN C:=BUFFER(LOC);
IF(C/=32)AND(C/=TAB_MARK)AND(C/=42)THEN LOC:=LOC+1;ELSE LOC:=LOC-1;
RETURN 0;END IF;ELSIF(C=92)AND(BUFFER(LOC)/=64)THEN LOC:=LOC+1;
ELSIF C=123 THEN B:=B+1;ELSIF C=125 THEN B:=B-1;IF B=0 THEN RETURN 0;
END IF;END IF--{:108}
;END LOOP;END SKIP_COMMENT;--{:107}{111:}
FUNCTION GET_NEXT RETURN EIGHT_BITS IS C:EIGHT_BITS;D:EIGHT_BITS;
J,K:LONG_NAME_INDEX;BEGIN<<RESTART>>IF LOC>LIMIT THEN GET_LINE;
IF INPUT_HAS_ENDED THEN RETURN NEW_MODULE;
ELSIF SCANNING_BASED_NUMBER THEN IF NOT PHASE_ONE THEN TEXT_IO.NEW_LINE(
TEXT_IO.STANDARD_OUTPUT);TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,
"! Improper based number, # sign missing");ERROR;END IF;END IF;END IF;
C:=BUFFER(LOC);LOC:=LOC+1;
IF SCANNING_BASED_NUMBER THEN IF C=35 THEN SCANNING_BASED_NUMBER:=FALSE;
END IF;RETURN C;END IF;
CASE C IS WHEN 35=>IF(LOC>1)AND THEN(BUFFER(LOC-2)IN 48..57)THEN
SCANNING_BASED_NUMBER:=TRUE;END IF;RETURN 35;WHEN 65..90!97..122=>
--{113:}
IF(((C=69)OR(C=101))AND(LOC>1))AND THEN((BUFFER(LOC-2)IN 48..57)OR
BUFFER(LOC-2)=35)THEN C:=EXPONENT;END IF;IF C/=EXPONENT THEN LOC:=LOC-1;
ID_FIRST:=LOC;LOOP LOC:=LOC+1;D:=BUFFER(LOC);
EXIT WHEN(D NOT IN 48..57)AND(D NOT IN 65..90)AND(D NOT IN 97..122)AND(D
/=95);END LOOP;C:=IDENTIFIER;ID_LOC:=LOC;END IF--{:113}
;WHEN 39=>--{123:}
ID_FIRST:=LOC-1;IF BUFFER(LOC+1)=39 THEN LOC:=LOC+2;ID_LOC:=LOC;
C:=CHARACTER_TOK;ELSIF BUFFER(LOC..LOC+2)=(64,64,39)THEN LOC:=LOC+3;
ID_LOC:=LOC;C:=CHARACTER_TOK;END IF--{:123}
;WHEN 34=>--{114:}
ID_FIRST:=LOC-1;LOOP D:=BUFFER(LOC);LOC:=LOC+1;
IF LOC>LIMIT THEN IF NOT PHASE_ONE THEN TEXT_IO.NEW_LINE(TEXT_IO.
STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! String constant didn't end");
ERROR;END IF;LOC:=LIMIT;D:=C;END IF;EXIT WHEN D=C;END LOOP;ID_LOC:=LOC;
C:=STR--{:114}
;WHEN 64=>--{115:}
C:=CONTROL_CODE(BUFFER(LOC));LOC:=LOC+1;
CASE C IS WHEN UNDERLINE=>IF XREF_SWITCH<BODY_FLAG THEN XREF_SWITCH:=
XREF_SWITCH+DEF_FLAG;END IF;GOTO RESTART;
WHEN NO_UNDERLINE=>IF XREF_SWITCH>0 THEN XREF_SWITCH:=XREF_SWITCH-
DEF_FLAG;END IF;GOTO RESTART;WHEN XREF_ROMAN..TEX_STRING=>--{121:}
ID_FIRST:=LOC;BUFFER(LIMIT+1):=64;WHILE BUFFER(LOC)/=64 LOOP LOC:=LOC+1;
END LOOP;ID_LOC:=LOC;
IF LOC>LIMIT THEN IF NOT PHASE_ONE THEN TEXT_IO.NEW_LINE(TEXT_IO.
STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Control text didn't end");ERROR;
END IF;LOC:=LIMIT;ELSE LOC:=LOC+2;
IF BUFFER(LOC-1)/=62 THEN IF NOT PHASE_ONE THEN TEXT_IO.NEW_LINE(TEXT_IO
.STANDARD_OUTPUT);TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,
"! Control codes are forbidden in control text");ERROR;END IF;END IF;
END IF--{:121}
;WHEN MODULE_NAME=>--{116:}{118:}
K:=0;LOOP IF LOC>LIMIT THEN GET_LINE;
IF INPUT_HAS_ENDED THEN IF NOT PHASE_ONE THEN TEXT_IO.NEW_LINE(TEXT_IO.
STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Input ended in section name");
ERROR;END IF;LOC:=1;EXIT;END IF;END IF;D:=BUFFER(LOC);--{119:}
IF D=64 THEN D:=BUFFER(LOC+1);IF D=62 THEN LOC:=LOC+2;EXIT;END IF;
IF(D=32)OR(D=TAB_MARK)OR(D=42)THEN IF NOT PHASE_ONE THEN TEXT_IO.
NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Section name didn't end");ERROR;
END IF;EXIT;END IF;K:=K+1;MOD_TEXT(K):=64;LOC:=LOC+1;END IF--{:119}
;LOC:=LOC+1;IF K<LONGEST_NAME-1 THEN K:=K+1;END IF;
IF(D=32)OR(D=TAB_MARK)THEN D:=32;IF MOD_TEXT(K-1)=32 THEN K:=K-1;END IF;
END IF;MOD_TEXT(K):=D;END LOOP;--{120:}
IF K>=LONGEST_NAME-2 THEN TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Section name too long: ");
FOR I IN 1..25 LOOP TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,XCHR(MOD_TEXT(I)
));END LOOP;TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"...");
IF HISTORY=SPOTLESS THEN HISTORY:=HARMLESS_MESSAGE;END IF;END IF--{:120}
;IF(MOD_TEXT(K)=32)AND(K>0)THEN K:=K-1;END IF--{:118}
;IF(K>3)AND THEN(MOD_TEXT(K-2..K)=(46,46,46))THEN CUR_MODULE:=
PREFIX_LOOKUP(K-3);ELSE CUR_MODULE:=MOD_LOOKUP(K);END IF;XREF_SWITCH:=0
--{:116}
;WHEN VERBATIM!OUTPUT_TOK=>--{122:}
ID_FIRST:=LOC;LOC:=LOC+1;BUFFER(LIMIT+1):=64;BUFFER(LIMIT+2):=62;
WHILE(BUFFER(LOC)/=64)OR(BUFFER(LOC+1)/=62)LOOP LOC:=LOC+1;END LOOP;
IF LOC>=LIMIT THEN IF NOT PHASE_ONE THEN TEXT_IO.NEW_LINE(TEXT_IO.
STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Verbatim string didn't end");
ERROR;END IF;END IF;ID_LOC:=LOC;LOC:=LOC+2--{:122}
;WHEN ASCII_TOK=>--{124:}
ID_FIRST:=LOC-1;LOC:=LOC+1;
IF BUFFER(LOC)/=39 THEN IF BUFFER(LOC-1..LOC)/=(64,64)THEN IF NOT
PHASE_ONE THEN TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,
"! Improper ASCII-code sequence, ' sign missing");ERROR;END IF;
ELSE LOC:=LOC+1;END IF;END IF;LOC:=LOC+1;ID_LOC:=LOC--{:124}
;WHEN OTHERS=>NULL;END CASE--{:115}
;--{112:}
WHEN 46=>IF BUFFER(LOC)=46 THEN IF LOC<=LIMIT THEN C:=DOUBLE_DOT;
LOC:=LOC+1;END IF;END IF;
WHEN 58=>IF BUFFER(LOC)=61 THEN IF LOC<=LIMIT THEN C:=LEFT_ARROW;
LOC:=LOC+1;END IF;END IF;
WHEN 61=>IF BUFFER(LOC)=61 THEN IF LOC<=LIMIT THEN C:=EQUIVALENCE_SIGN;
LOC:=LOC+1;END IF;
ELSIF BUFFER(LOC)=62 THEN IF LOC<=LIMIT THEN C:=RIGHT_ARROW;LOC:=LOC+1;
END IF;END IF;
WHEN 62=>IF BUFFER(LOC)=61 THEN IF LOC<=LIMIT THEN C:=GREATER_OR_EQUAL;
LOC:=LOC+1;END IF;
ELSIF BUFFER(LOC)=62 THEN IF LOC<=LIMIT THEN C:=RIGHT_LABEL_BRACKET;
LOC:=LOC+1;END IF;END IF;
WHEN 60=>IF BUFFER(LOC)=61 THEN IF LOC<=LIMIT THEN C:=LESS_OR_EQUAL;
LOC:=LOC+1;END IF;
ELSIF BUFFER(LOC)=60 THEN IF LOC<=LIMIT THEN C:=LEFT_LABEL_BRACKET;
LOC:=LOC+1;END IF;
ELSIF BUFFER(LOC)=62 THEN IF LOC<=LIMIT THEN C:=BOX_SIGN;LOC:=LOC+1;
END IF;END IF;
WHEN 47=>IF BUFFER(LOC)=61 THEN IF LOC<=LIMIT THEN C:=NOT_EQUAL;
LOC:=LOC+1;END IF;END IF;
WHEN 42=>IF BUFFER(LOC)=42 THEN IF LOC<=LIMIT THEN C:=DOUBLE_STAR;
LOC:=LOC+1;END IF;END IF;--{:112}
WHEN 32!TAB_MARK=>GOTO RESTART;WHEN OTHERS=>NULL;END CASE;RETURN C;
END GET_NEXT;--{:111}
END LEXICAL_SCANNING;--{:6}{7:}
