WITH TEXT_IO,INT_NUMBER_IO;WITH INPUT_OUTPUT;USE INPUT_OUTPUT;
WITH LEXICAL_SCANNING;USE LEXICAL_SCANNING;PACKAGE BODY OUTPUT IS
--{141:}
PROCEDURE FLUSH_BUFFER(B:EIGHT_BITS;
PER_CENT:BOOLEAN)IS J:LENGTH_INDEX:=B;
BEGIN IF NOT PER_CENT THEN LOOP EXIT WHEN(J=0)OR ELSE(OUT_BUF(J)/=32);
J:=J-1;END LOOP;END IF;
FOR K IN 1..J LOOP TEXT_IO.PUT(TEX_FILE,XCHR(OUT_BUF(K)));END LOOP;
IF PER_CENT THEN TEXT_IO.PUT(TEX_FILE,XCHR(37));END IF;
TEXT_IO.NEW_LINE(TEX_FILE);OUT_LINE:=OUT_LINE+1;
IF B<OUT_PTR THEN OUT_BUF(1..OUT_PTR-B):=OUT_BUF(B+1..OUT_PTR);END IF;
OUT_PTR:=OUT_PTR-B;END FLUSH_BUFFER;--{:141}{143:}
PROCEDURE FINISH_LINE IS BEGIN IF OUT_PTR>0 THEN FLUSH_BUFFER(OUT_PTR,
FALSE);
ELSE FOR K IN 0..LIMIT LOOP IF(BUFFER(K)/=32)AND(BUFFER(K)/=TAB_MARK)
THEN RETURN;END IF;END LOOP;FLUSH_BUFFER(0,FALSE);END IF;
END FINISH_LINE;--{:143}{148:}
PROCEDURE BREAK_OUT IS K:LENGTH_INDEX:=OUT_PTR;C,D:ASCII_CODE;
BEGIN LOOP IF K=0 THEN--{149:}
TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Line had to be broken (output l."
);INT_NUMBER_IO.PUT(TEXT_IO.STANDARD_OUTPUT,OUT_LINE,1);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"):");
TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
FOR J IN 1..OUT_PTR-1 LOOP TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,XCHR(
OUT_BUF(J)));END LOOP;TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
IF HISTORY=SPOTLESS THEN HISTORY:=HARMLESS_MESSAGE;END IF;
FLUSH_BUFFER(OUT_PTR-1,TRUE);RETURN--{:149}
;END IF;D:=OUT_BUF(K);IF D=32 THEN FLUSH_BUFFER(K,FALSE);RETURN;END IF;
IF(D=92)AND(OUT_BUF(K-1)/=92)THEN FLUSH_BUFFER(K-1,TRUE);RETURN;END IF;
K:=K-1;END LOOP;END BREAK_OUT;--{:148}{152:}
PROCEDURE OUT_MOD(M:INTEGER;C:INTEGER:=1)IS K:INTEGER RANGE 0..5;
A:INTEGER;BEGIN A:=M;--{153:}
K:=0;LOOP DIG(K):=A MOD 10;A:=A/10;K:=K+1;EXIT WHEN A=0;END LOOP;
LOOP K:=K-1;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=DIG(K)+48;EXIT WHEN K=0;END LOOP
--{:153}
;IF CHANGED_MODULE(M)THEN IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=92;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=42;END IF;
IF C>1 THEN IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=40;A:=C;--{153:}
K:=0;LOOP DIG(K):=A MOD 10;A:=A/10;K:=K+1;EXIT WHEN A=0;END LOOP;
LOOP K:=K-1;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=DIG(K)+48;EXIT WHEN K=0;END LOOP
--{:153}
;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=41;END IF;END OUT_MOD;--{:152}{155:}
PROCEDURE OUT_NAME(P:NAME_POINTER)IS W:W_RANGE;
BEGIN IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=123;W:=P MOD WW;
FOR K IN BYTE_START(P)..BYTE_START(P+WW)-1 LOOP IF BYTE_MEM(W,K)=95 THEN
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=92;END IF;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;
END IF;OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=BYTE_MEM(W,K);END LOOP;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=125;END OUT_NAME;--{:155}{157:}
PROCEDURE COPY_LIMBO IS C:ASCII_CODE;
BEGIN LOOP IF LOC>LIMIT THEN FINISH_LINE;GET_LINE;
IF INPUT_HAS_ENDED THEN RETURN;END IF;ELSE BUFFER(LIMIT+1):=64;--{158:}
WHILE BUFFER(LOC)/=64 LOOP IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=BUFFER(LOC);LOC:=LOC+1;END LOOP;
IF LOC<=LIMIT THEN LOC:=LOC+2;C:=BUFFER(LOC-1);
IF(C=32)OR(C=TAB_MARK)OR(C=42)THEN RETURN;END IF;
IF(C/=122)AND(C/=90)THEN IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=64;
IF C/=64 THEN IF NOT PHASE_ONE THEN TEXT_IO.NEW_LINE(TEXT_IO.
STANDARD_OUTPUT);TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,
"! Double @ required outside of sections");ERROR;END IF;END IF;END IF;
END IF--{:158}
;END IF;END LOOP;END COPY_LIMBO;--{:157}{160:}
FUNCTION COPY_TEX RETURN EIGHT_BITS IS C:EIGHT_BITS;
BEGIN LOOP IF LOC>LIMIT THEN FINISH_LINE;GET_LINE;
IF INPUT_HAS_ENDED THEN RETURN NEW_MODULE;END IF;END IF;
BUFFER(LIMIT+1):=64;--{161:}
LOOP C:=BUFFER(LOC);LOC:=LOC+1;IF C=124 THEN RETURN 124;END IF;
IF C/=64 THEN IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=C;
IF(OUT_PTR=1)AND((C=32)OR(C=TAB_MARK))THEN OUT_PTR:=OUT_PTR-1;END IF;
END IF;EXIT WHEN C=64;END LOOP;
IF LOC<=LIMIT THEN C:=CONTROL_CODE(BUFFER(LOC));LOC:=LOC+1;RETURN C;
END IF--{:161}
;END LOOP;END COPY_TEX;--{:160}{163:}
FUNCTION COPY_COMMENT(BAL:EIGHT_BITS)RETURN EIGHT_BITS IS C:ASCII_CODE;
B:EIGHT_BITS:=BAL;BEGIN LOOP IF LOC>LIMIT THEN GET_LINE;
IF INPUT_HAS_ENDED THEN IF NOT PHASE_ONE THEN TEXT_IO.NEW_LINE(TEXT_IO.
STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Input ended in mid-comment");
ERROR;END IF;LOC:=1;--{165:}
IF TOK_PTR+2>MAX_TOKS THEN TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Sorry, "&"token"&
" capacity exceeded");ERROR;HISTORY:=FATAL_MESSAGE;RAISE END_OF_AWEAVE;
END IF;TOK_MEM(TOK_PTR):=32;TOK_PTR:=TOK_PTR+1;
WHILE B>0 LOOP IF TOK_PTR+2>MAX_TOKS THEN TEXT_IO.NEW_LINE(TEXT_IO.
STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Sorry, "&"token"&
" capacity exceeded");ERROR;HISTORY:=FATAL_MESSAGE;RAISE END_OF_AWEAVE;
END IF;TOK_MEM(TOK_PTR):=125;TOK_PTR:=TOK_PTR+1;B:=B-1;END LOOP;RETURN 0
--{:165}
;END IF;END IF;C:=BUFFER(LOC);LOC:=LOC+1;IF C=124 THEN RETURN B;END IF;
IF TOK_PTR+2>MAX_TOKS THEN TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Sorry, "&"token"&
" capacity exceeded");ERROR;HISTORY:=FATAL_MESSAGE;RAISE END_OF_AWEAVE;
END IF;TOK_MEM(TOK_PTR):=C;TOK_PTR:=TOK_PTR+1;--{164:}
IF C=64 THEN LOC:=LOC+1;
IF BUFFER(LOC-1)/=64 THEN IF NOT PHASE_ONE THEN TEXT_IO.NEW_LINE(TEXT_IO
.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Illegal use of @ in comment");
ERROR;END IF;LOC:=LOC-2;TOK_PTR:=TOK_PTR-1;--{165:}
IF TOK_PTR+2>MAX_TOKS THEN TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Sorry, "&"token"&
" capacity exceeded");ERROR;HISTORY:=FATAL_MESSAGE;RAISE END_OF_AWEAVE;
END IF;TOK_MEM(TOK_PTR):=32;TOK_PTR:=TOK_PTR+1;
WHILE B>0 LOOP IF TOK_PTR+2>MAX_TOKS THEN TEXT_IO.NEW_LINE(TEXT_IO.
STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Sorry, "&"token"&
" capacity exceeded");ERROR;HISTORY:=FATAL_MESSAGE;RAISE END_OF_AWEAVE;
END IF;TOK_MEM(TOK_PTR):=125;TOK_PTR:=TOK_PTR+1;B:=B-1;END LOOP;RETURN 0
--{:165}
;END IF;
ELSIF(C=92)AND(BUFFER(LOC)/=64)THEN IF TOK_PTR+2>MAX_TOKS THEN TEXT_IO.
NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Sorry, "&"token"&
" capacity exceeded");ERROR;HISTORY:=FATAL_MESSAGE;RAISE END_OF_AWEAVE;
END IF;TOK_MEM(TOK_PTR):=BUFFER(LOC);TOK_PTR:=TOK_PTR+1;LOC:=LOC+1;
ELSIF C=123 THEN B:=B+1;ELSIF C=125 THEN B:=B-1;IF B=0 THEN RETURN 0;
END IF;END IF--{:164}
;END LOOP;END COPY_COMMENT;--{:163}
END OUTPUT;--{:8}{9:}
