WITH DATA_STRUCTURES;USE DATA_STRUCTURES;PACKAGE PARSING IS--{217:}
FUNCTION TRANSLATE RETURN TEXT_POINTER;--{:217}{221:}
PROCEDURE APP_COMMENT;--{:221}{237:}
FUNCTION ADA_TRANSLATE RETURN TEXT_POINTER;--{:237}{239:}
PROCEDURE OUTER_PARSE;--{:239}
END PARSING;
