WITH TEXT_IO,INT_NUMBER_IO;WITH INPUT_OUTPUT;USE INPUT_OUTPUT;
WITH SEARCHING;USE SEARCHING;WITH LEXICAL_SCANNING;USE LEXICAL_SCANNING;
WITH OUTPUT;USE OUTPUT;PACKAGE BODY PARSING IS--{212:}
PROCEDURE RED(J:SIXTEEN_BITS;K:EIGHT_BITS;C:EIGHT_BITS;
D:INTEGER)IS BEGIN CAT(J):=C;TRANS(J):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;
IF K>1 THEN FOR I IN J+K..LO_PTR LOOP CAT(I-K+1):=CAT(I);
TRANS(I-K+1):=TRANS(I);END LOOP;LO_PTR:=LO_PTR-K+1;END IF;--{213:}
IF PP+D>=SCRAP_BASE THEN PP:=PP+D;ELSE PP:=SCRAP_BASE;END IF--{:213}
;END RED;--{:212}{214:}
PROCEDURE SQ(J:SIXTEEN_BITS;K:EIGHT_BITS;C:EIGHT_BITS;
D:INTEGER)IS BEGIN IF K=1 THEN CAT(J):=C;--{213:}
IF PP+D>=SCRAP_BASE THEN PP:=PP+D;ELSE PP:=SCRAP_BASE;END IF--{:213}
;ELSE FOR I IN J..J+K-1 LOOP TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(I);
TOK_PTR:=TOK_PTR+1;END LOOP;RED(J,K,C,D);END IF;END SQ;
--{:214}{218:}{175:}
PROCEDURE DO_CASES IS SEPARATE;--{:175}
FUNCTION TRANSLATE RETURN TEXT_POINTER IS SEPARATE;--{:218}{222:}{236:}
PROCEDURE APP_COMMENT IS BEGIN TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(SCRAP_PTR);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TEXT_PTR-1+TOK_FLAG;TOK_PTR:=TOK_PTR+1;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;END APP_COMMENT;--{:236}{226:}
PROCEDURE EASY_CASES IS BEGIN CASE NEXT_CONTROL IS WHEN SET_ELEMENT_SIGN
=>TOK_MEM(TOK_PTR):=92;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=105;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=110;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=IN_SCRAP;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;WHEN DOUBLE_DOT=>TOK_MEM(TOK_PTR):=92;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=116;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=111;TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;
CAT(SCRAP_PTR):=MATH;TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;
WHEN 35!36!37!94!95=>TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=92;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=NEXT_CONTROL;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=MATH;TRANS(SCRAP_PTR):=TEXT_PTR;
TEXT_PTR:=TEXT_PTR+1;TOK_START(TEXT_PTR):=TOK_PTR;
WHEN 38=>TOK_MEM(TOK_PTR):=MATH_BIN;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=92;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=46;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=92;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=38;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=125;
TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=MATH;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;WHEN 33=>TOK_MEM(TOK_PTR):=MATH_REL;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=92;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=46;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=124;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=125;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=MATH;TRANS(SCRAP_PTR):=TEXT_PTR;
TEXT_PTR:=TEXT_PTR+1;TOK_START(TEXT_PTR):=TOK_PTR;
WHEN IGNORE!124!XREF_ROMAN..XREF_RESERVED=>NULL;
WHEN 40=>TOK_MEM(TOK_PTR):=NEXT_CONTROL;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=OPEN_SCRAP;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;WHEN 41=>TOK_MEM(TOK_PTR):=NEXT_CONTROL;
TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=CLOSE_SCRAP;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;WHEN 42=>TOK_MEM(TOK_PTR):=92;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=97;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=115;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=116;
TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=MATH;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;WHEN 44=>TOK_MEM(TOK_PTR):=44;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=OPT;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=57;TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;
CAT(SCRAP_PTR):=MATH;TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;
WHEN 48..57=>IF(BUFFER(LOC)=35)OR(BUFFER(LOC+1)=35)THEN--{227:}{228:}
LOOP IF NEXT_CONTROL=95 THEN TOK_MEM(TOK_PTR):=92;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=95;TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;
CAT(SCRAP_PTR):=DIGIT_SCRAP;TRANS(SCRAP_PTR):=TEXT_PTR;
TEXT_PTR:=TEXT_PTR+1;TOK_START(TEXT_PTR):=TOK_PTR;
ELSE TOK_MEM(TOK_PTR):=NEXT_CONTROL;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=DIGIT_SCRAP;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;END IF;NEXT_CONTROL:=GET_NEXT;
EXIT WHEN NEXT_CONTROL=35;END LOOP--{:228}
;TOK_MEM(TOK_PTR):=NEXT_CONTROL;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=BASE;TRANS(SCRAP_PTR):=TEXT_PTR;
TEXT_PTR:=TEXT_PTR+1;TOK_START(TEXT_PTR):=TOK_PTR;
NEXT_CONTROL:=GET_NEXT;--{228:}
LOOP IF NEXT_CONTROL=95 THEN TOK_MEM(TOK_PTR):=92;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=95;TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;
CAT(SCRAP_PTR):=DIGIT_SCRAP;TRANS(SCRAP_PTR):=TEXT_PTR;
TEXT_PTR:=TEXT_PTR+1;TOK_START(TEXT_PTR):=TOK_PTR;
ELSE TOK_MEM(TOK_PTR):=NEXT_CONTROL;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=DIGIT_SCRAP;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;END IF;NEXT_CONTROL:=GET_NEXT;
EXIT WHEN NEXT_CONTROL=35;END LOOP--{:228}
;TOK_MEM(TOK_PTR):=NEXT_CONTROL;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=BASE;TRANS(SCRAP_PTR):=TEXT_PTR;
TEXT_PTR:=TEXT_PTR+1;TOK_START(TEXT_PTR):=TOK_PTR--{:227}
;ELSE TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=NEXT_CONTROL;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;
CAT(SCRAP_PTR):=DIGIT_SCRAP;TRANS(SCRAP_PTR):=TEXT_PTR;
TEXT_PTR:=TEXT_PTR+1;TOK_START(TEXT_PTR):=TOK_PTR;END IF;
WHEN 46=>TOK_MEM(TOK_PTR):=46;TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;
CAT(SCRAP_PTR):=PERIOD;TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;WHEN 59=>TOK_MEM(TOK_PTR):=59;
TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=SEMI;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;WHEN 58=>TOK_MEM(TOK_PTR):=58;
TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=COLON;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;--{230:}
WHEN NOT_EQUAL=>TOK_MEM(TOK_PTR):=92;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=73;TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;
CAT(SCRAP_PTR):=MATH;TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;WHEN LESS_OR_EQUAL=>TOK_MEM(TOK_PTR):=92;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=76;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=MATH;TRANS(SCRAP_PTR):=TEXT_PTR;
TEXT_PTR:=TEXT_PTR+1;TOK_START(TEXT_PTR):=TOK_PTR;
WHEN GREATER_OR_EQUAL=>TOK_MEM(TOK_PTR):=92;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=71;TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;
CAT(SCRAP_PTR):=MATH;TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;
WHEN EQUIVALENCE_SIGN=>TOK_MEM(TOK_PTR):=92;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=83;TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;
CAT(SCRAP_PTR):=MATH;TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;WHEN AND_SIGN=>TOK_MEM(TOK_PTR):=92;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=87;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=AND_SCRAP;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;WHEN OR_SIGN=>TOK_MEM(TOK_PTR):=92;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=86;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=ELSE_SCRAP;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;WHEN NOT_SIGN=>TOK_MEM(TOK_PTR):=92;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=82;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=NOT_SCRAP;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;WHEN LEFT_ARROW=>TOK_MEM(TOK_PTR):=92;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=75;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=MATH;TRANS(SCRAP_PTR):=TEXT_PTR;
TEXT_PTR:=TEXT_PTR+1;TOK_START(TEXT_PTR):=TOK_PTR;
WHEN RIGHT_ARROW=>TOK_MEM(TOK_PTR):=92;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=75;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=82;
TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=ARROW;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;WHEN DOUBLE_STAR=>TOK_MEM(TOK_PTR):=92;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=100;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=115;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=116;
TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=MATH;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;
WHEN LEFT_LABEL_BRACKET=>TOK_MEM(TOK_PTR):=92;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=66;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=76;
TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;
CAT(SCRAP_PTR):=BEGIN_LABEL_SCRAP;TRANS(SCRAP_PTR):=TEXT_PTR;
TEXT_PTR:=TEXT_PTR+1;TOK_START(TEXT_PTR):=TOK_PTR;
WHEN RIGHT_LABEL_BRACKET=>TOK_MEM(TOK_PTR):=92;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=69;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=76;
TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;
CAT(SCRAP_PTR):=END_LABEL_SCRAP;TRANS(SCRAP_PTR):=TEXT_PTR;
TEXT_PTR:=TEXT_PTR+1;TOK_START(TEXT_PTR):=TOK_PTR;
WHEN BOX_SIGN=>TOK_MEM(TOK_PTR):=92;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=66;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=79;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=88;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=MATH;TRANS(SCRAP_PTR):=TEXT_PTR;
TEXT_PTR:=TEXT_PTR+1;TOK_START(TEXT_PTR):=TOK_PTR;--{:230}
WHEN EXPONENT=>TOK_MEM(TOK_PTR):=92;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=69;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=123;
TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=EXP;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;WHEN BEGIN_COMMENT=>TOK_MEM(TOK_PTR):=92;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=66;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=MATH;TRANS(SCRAP_PTR):=TEXT_PTR;
TEXT_PTR:=TEXT_PTR+1;TOK_START(TEXT_PTR):=TOK_PTR;
WHEN END_COMMENT=>TOK_MEM(TOK_PTR):=92;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=84;TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;
CAT(SCRAP_PTR):=MATH;TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;WHEN FORCE_LINE=>TOK_MEM(TOK_PTR):=92;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=41;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=MATH;TRANS(SCRAP_PTR):=TEXT_PTR;
TEXT_PTR:=TEXT_PTR+1;TOK_START(TEXT_PTR):=TOK_PTR;
WHEN THIN_SPACE=>TOK_MEM(TOK_PTR):=92;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=44;TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;
CAT(SCRAP_PTR):=MATH;TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;WHEN MATH_BREAK=>TOK_MEM(TOK_PTR):=OPT;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=48;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=MATH;TRANS(SCRAP_PTR):=TEXT_PTR;
TEXT_PTR:=TEXT_PTR+1;TOK_START(TEXT_PTR):=TOK_PTR;
WHEN LINE_BREAK=>TOK_MEM(TOK_PTR):=FORCE;TOK_PTR:=TOK_PTR+1;APP_COMMENT;
WHEN BIG_LINE_BREAK=>TOK_MEM(TOK_PTR):=BIG_FORCE;TOK_PTR:=TOK_PTR+1;
APP_COMMENT;WHEN NO_LINE_BREAK=>TOK_MEM(TOK_PTR):=BIG_CANCEL;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=92;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=56;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=BIG_CANCEL;
TOK_PTR:=TOK_PTR+1;APP_COMMENT;WHEN PSEUDO_SEMI=>SCRAP_PTR:=SCRAP_PTR+1;
CAT(SCRAP_PTR):=SEMI;TRANS(SCRAP_PTR):=0;
WHEN JOIN=>TOK_MEM(TOK_PTR):=92;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=74;
TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=MATH;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;
WHEN OTHERS=>TOK_MEM(TOK_PTR):=NEXT_CONTROL;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=MATH;TRANS(SCRAP_PTR):=TEXT_PTR;
TEXT_PTR:=TEXT_PTR+1;TOK_START(TEXT_PTR):=TOK_PTR;END CASE;
END EASY_CASES;--{:226}
PROCEDURE ADA_PARSE IS SEPARATE;--{:222}{238:}
FUNCTION ADA_TRANSLATE RETURN TEXT_POINTER IS P:TEXT_POINTER;
SAVE_BASE:SCRAP_INDEX;BEGIN SAVE_BASE:=SCRAP_BASE;
SCRAP_BASE:=SCRAP_PTR+1;ADA_PARSE;
IF NEXT_CONTROL/=124 THEN IF NOT PHASE_ONE THEN TEXT_IO.NEW_LINE(TEXT_IO
.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Missing `|' after ADA text");
ERROR;END IF;END IF;
IF TOK_PTR+2>MAX_TOKS THEN TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Sorry, "&"token"&
" capacity exceeded");ERROR;HISTORY:=FATAL_MESSAGE;RAISE END_OF_AWEAVE;
END IF;TOK_MEM(TOK_PTR):=CANCEL;TOK_PTR:=TOK_PTR+1;APP_COMMENT;
P:=TRANSLATE;
--IF SCRAP_PTR>MAX_SCR_PTR THEN MAX_SCR_PTR:=SCRAP_PTR;END IF;
SCRAP_PTR:=SCRAP_BASE-1;SCRAP_BASE:=SAVE_BASE;RETURN P;
END ADA_TRANSLATE;--{:238}{240:}
PROCEDURE OUTER_PARSE IS BAL:EIGHT_BITS;P,Q:TEXT_POINTER;
BEGIN WHILE NEXT_CONTROL<FORMAT LOOP IF NEXT_CONTROL/=123 THEN ADA_PARSE
;ELSE--{241:}
IF(TOK_PTR+7>MAX_TOKS)OR(TEXT_PTR+3>MAX_TEXTS)OR(SCRAP_PTR>=MAX_SCRAPS)
THEN
--IF SCRAP_PTR>MAX_SCR_PTR THEN MAX_SCR_PTR:=SCRAP_PTR;END IF;
--IF TOK_PTR>MAX_TOK_PTR THEN MAX_TOK_PTR:=TOK_PTR;END IF;
--IF TEXT_PTR>MAX_TXT_PTR THEN MAX_TXT_PTR:=TEXT_PTR;END IF;
TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Sorry, "&"token/text/scrap"&
" capacity exceeded");ERROR;HISTORY:=FATAL_MESSAGE;RAISE END_OF_AWEAVE;
END IF--{:241}
;TOK_MEM(TOK_PTR):=92;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=67;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=123;TOK_PTR:=TOK_PTR+1;
BAL:=COPY_COMMENT(1);NEXT_CONTROL:=124;WHILE BAL>0 LOOP P:=TEXT_PTR;
TEXT_PTR:=TEXT_PTR+1;TOK_START(TEXT_PTR):=TOK_PTR;Q:=ADA_TRANSLATE;
TOK_MEM(TOK_PTR):=TOK_FLAG+P;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=INNER_TOK_FLAG+Q;TOK_PTR:=TOK_PTR+1;
IF NEXT_CONTROL=124 THEN BAL:=COPY_COMMENT(BAL);ELSE BAL:=0;END IF;
END LOOP;TOK_MEM(TOK_PTR):=FORCE;TOK_PTR:=TOK_PTR+1;APP_COMMENT;END IF;
END LOOP;END OUTER_PARSE;--{:240}
END PARSING;--{:9}{10:}
