SEPARATE(PARSING)PROCEDURE ADA_PARSE IS J:LONG_BUFFER_INDEX;
P:NAME_POINTER;BEGIN WHILE NEXT_CONTROL<FORMAT LOOP--{225:}{229:}
IF(SCRAP_PTR+4>MAX_SCRAPS)OR(TOK_PTR+6>MAX_TOKS)OR(TEXT_PTR+4>MAX_TEXTS)
THEN
--IF SCRAP_PTR>MAX_SCR_PTR THEN MAX_SCR_PTR:=SCRAP_PTR;END IF;
--IF TOK_PTR>MAX_TOK_PTR THEN MAX_TOK_PTR:=TOK_PTR;END IF;
--IF TEXT_PTR>MAX_TXT_PTR THEN MAX_TXT_PTR:=TEXT_PTR;END IF;
TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Sorry, "&"scrap/token/text"&
" capacity exceeded");ERROR;HISTORY:=FATAL_MESSAGE;RAISE END_OF_AWEAVE;
END IF--{:229}
;<<RESWITCH>>CASE NEXT_CONTROL IS WHEN STR!VERBATIM!OUTPUT_TOK!
CHARACTER_TOK=>--{231:}
TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=92;
TOK_PTR:=TOK_PTR+1;
CASE NEXT_CONTROL IS WHEN VERBATIM=>TOK_MEM(TOK_PTR):=61;
TOK_PTR:=TOK_PTR+1;WHEN OUTPUT_TOK=>TOK_MEM(TOK_PTR):=79;
TOK_PTR:=TOK_PTR+1;WHEN OTHERS=>TOK_MEM(TOK_PTR):=46;TOK_PTR:=TOK_PTR+1;
END CASE;TOK_MEM(TOK_PTR):=123;TOK_PTR:=TOK_PTR+1;J:=ID_FIRST;
WHILE J<ID_LOC LOOP--{232:}
CASE BUFFER(J)IS WHEN 32!92!37!36!94!39!96!123!35!125!126!38!95=>TOK_MEM
(TOK_PTR):=92;TOK_PTR:=TOK_PTR+1;WHEN 64=>IF BUFFER(J+1)=64 THEN J:=J+1;
ELSE IF NOT PHASE_ONE THEN TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,
"! Double @ should be used in strings and character literals");ERROR;
END IF;END IF;WHEN OTHERS=>NULL;END CASE;
IF TOK_PTR+2>MAX_TOKS THEN TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Sorry, "&"token"&
" capacity exceeded");ERROR;HISTORY:=FATAL_MESSAGE;RAISE END_OF_AWEAVE;
END IF;TOK_MEM(TOK_PTR):=BUFFER(J);TOK_PTR:=TOK_PTR+1--{:232}
;J:=J+1;END LOOP;IF NEXT_CONTROL=OUTPUT_TOK THEN TOK_MEM(TOK_PTR):=125;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=FORCE;TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;
CAT(SCRAP_PTR):=MATH;TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;ELSE TOK_MEM(TOK_PTR):=125;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=MATH;TRANS(SCRAP_PTR):=TEXT_PTR;
TEXT_PTR:=TEXT_PTR+1;TOK_START(TEXT_PTR):=TOK_PTR;END IF--{:231}
;WHEN ASCII_TOK=>--{233:}
TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=92;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=72;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=123;TOK_PTR:=TOK_PTR+1;J:=ID_FIRST+1;--{232:}
CASE BUFFER(J)IS WHEN 32!92!37!36!94!39!96!123!35!125!126!38!95=>TOK_MEM
(TOK_PTR):=92;TOK_PTR:=TOK_PTR+1;WHEN 64=>IF BUFFER(J+1)=64 THEN J:=J+1;
ELSE IF NOT PHASE_ONE THEN TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,
"! Double @ should be used in strings and character literals");ERROR;
END IF;END IF;WHEN OTHERS=>NULL;END CASE;
IF TOK_PTR+2>MAX_TOKS THEN TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Sorry, "&"token"&
" capacity exceeded");ERROR;HISTORY:=FATAL_MESSAGE;RAISE END_OF_AWEAVE;
END IF;TOK_MEM(TOK_PTR):=BUFFER(J);TOK_PTR:=TOK_PTR+1--{:232}
;TOK_MEM(TOK_PTR):=125;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PDOLLAR;
TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=MATH;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR--{:233}
;WHEN IDENTIFIER=>--{235:}
P:=ID_LOOKUP(NORMAL);
CASE ILK(P)IS WHEN NORMAL!PREDEFINED=>TOK_MEM(TOK_PTR):=PSPACE;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=ID_FLAG+P;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PSPACE;
TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=MATH;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;
WHEN ACCEPT_LIKE=>TOK_MEM(TOK_PTR):=RES_FLAG+P;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=SSPACE;TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;
CAT(SCRAP_PTR):=ACCEPT_SCRAP;TRANS(SCRAP_PTR):=TEXT_PTR;
TEXT_PTR:=TEXT_PTR+1;TOK_START(TEXT_PTR):=TOK_PTR;
WHEN ALL_LIKE=>TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=PSPACE;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=RES_FLAG+P;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PSPACE;
TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=MATH;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;WHEN AND_LIKE=>TOK_MEM(TOK_PTR):=92;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=87;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=AND_SCRAP;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;
WHEN ARRAY_LIKE=>TOK_MEM(TOK_PTR):=RES_FLAG+P;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=SSPACE;TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;
CAT(SCRAP_PTR):=OPEN_SCRAP;TRANS(SCRAP_PTR):=TEXT_PTR;
TEXT_PTR:=TEXT_PTR+1;TOK_START(TEXT_PTR):=TOK_PTR;
WHEN AT_LIKE=>TOK_MEM(TOK_PTR):=SSPACE;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=RES_FLAG+P;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=SSPACE;TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;
CAT(SCRAP_PTR):=COLON;TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;
WHEN BEGIN_LIKE=>TOK_MEM(TOK_PTR):=RES_FLAG+P;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=BEGINNING;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;WHEN BODY_LIKE=>TOK_MEM(TOK_PTR):=PDOLLAR;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=RES_FLAG+P;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PSPACE;
TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=MATH;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;
WHEN CASE_LIKE=>TOK_MEM(TOK_PTR):=RES_FLAG+P;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=CASE_SCRAP;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;WHEN DECLARE_LIKE=>TOK_MEM(TOK_PTR):=FORCE;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=RES_FLAG+P;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=INDENT;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=FORCE;
TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=DECL;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;WHEN GOTO_LIKE=>TOK_MEM(TOK_PTR):=PSPACE;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=RES_FLAG+P;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=SSPACE;
TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=MATH;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;WHEN IS_LIKE=>TOK_MEM(TOK_PTR):=SSPACE;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=RES_FLAG+P;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=SSPACE;TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;
CAT(SCRAP_PTR):=FOLLOWS;TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;
WHEN ELSE_LIKE=>TOK_MEM(TOK_PTR):=RES_FLAG+P;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=ELSE_SCRAP;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;WHEN ELSIF_LIKE=>TOK_MEM(TOK_PTR):=BACKUP;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=RES_FLAG+P;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=IF_SCRAP;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;
WHEN END_LIKE=>TOK_MEM(TOK_PTR):=RES_FLAG+P;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=ENDING;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;
WHEN EXCEPTION_LIKE=>TOK_MEM(TOK_PTR):=RES_FLAG+P;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=EXCEPTION_SCRAP;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;
WHEN PROC_LIKE=>TOK_MEM(TOK_PTR):=RES_FLAG+P;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=SSPACE;TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;
CAT(SCRAP_PTR):=PROC;TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;WHEN NEW_LIKE=>TOK_MEM(TOK_PTR):=PSPACE;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=RES_FLAG+P;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=PSPACE;TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;
CAT(SCRAP_PTR):=NEW_SCRAP;TRANS(SCRAP_PTR):=TEXT_PTR;
TEXT_PTR:=TEXT_PTR+1;TOK_START(TEXT_PTR):=TOK_PTR;
WHEN GENERIC_LIKE=>TOK_MEM(TOK_PTR):=RES_FLAG+P;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=GENERIC_SCRAP;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;WHEN IF_LIKE=>TOK_MEM(TOK_PTR):=RES_FLAG+P;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=INDENT;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=IF_SCRAP;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;WHEN IN_LIKE=>TOK_MEM(TOK_PTR):=92;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=105;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=110;TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;
CAT(SCRAP_PTR):=IN_SCRAP;TRANS(SCRAP_PTR):=TEXT_PTR;
TEXT_PTR:=TEXT_PTR+1;TOK_START(TEXT_PTR):=TOK_PTR;
WHEN LOOP_LIKE=>TOK_MEM(TOK_PTR):=RES_FLAG+P;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=LOOP_SCRAP;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;WHEN MOD_LIKE=>TOK_MEM(TOK_PTR):=MATH_BIN;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=RES_FLAG+P;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=125;TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;
CAT(SCRAP_PTR):=MATH;TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;WHEN NOT_LIKE=>TOK_MEM(TOK_PTR):=92;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=82;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=NOT_SCRAP;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;WHEN OF_LIKE=>TOK_MEM(TOK_PTR):=SSPACE;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=RES_FLAG+P;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=SSPACE;TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;
CAT(SCRAP_PTR):=CLOSE_SCRAP;TRANS(SCRAP_PTR):=TEXT_PTR;
TEXT_PTR:=TEXT_PTR+1;TOK_START(TEXT_PTR):=TOK_PTR;
WHEN OR_LIKE=>TOK_MEM(TOK_PTR):=RES_FLAG+P;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=ELSE_SCRAP;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;
WHEN PRAGMA_LIKE=>TOK_MEM(TOK_PTR):=RES_FLAG+P;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=SSPACE;TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;
CAT(SCRAP_PTR):=PROC;TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;
WHEN PRIVATE_LIKE=>TOK_MEM(TOK_PTR):=RES_FLAG+P;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=PRIVATE_SCRAP;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;WHEN RANGE_LIKE=>TOK_MEM(TOK_PTR):=SSPACE;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=RES_FLAG+P;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=SSPACE;
TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=MATH;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;
WHEN RECORD_LIKE=>TOK_MEM(TOK_PTR):=RES_FLAG+P;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=RECORD_SCRAP;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;
WHEN RETURN_LIKE=>TOK_MEM(TOK_PTR):=RES_FLAG+P;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=RETURN_SCRAP;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;
WHEN SEPARATE_LIKE=>TOK_MEM(TOK_PTR):=RES_FLAG+P;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=SEPARATE_SCRAP;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;WHEN TYPE_LIKE=>TOK_MEM(TOK_PTR):=PDOLLAR;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=RES_FLAG+P;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=SSPACE;
TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=MATH;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;WHEN THEN_LIKE=>TOK_MEM(TOK_PTR):=SSPACE;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=RES_FLAG+P;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=THEN_SCRAP;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;WHEN WITH_LIKE=>TOK_MEM(TOK_PTR):=PSPACE;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=RES_FLAG+P;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=SSPACE;TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;
CAT(SCRAP_PTR):=WITH_SCRAP;TRANS(SCRAP_PTR):=TEXT_PTR;
TEXT_PTR:=TEXT_PTR+1;TOK_START(TEXT_PTR):=TOK_PTR;
WHEN WHEN_LIKE=>TOK_MEM(TOK_PTR):=RES_FLAG+P;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=SSPACE;TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;
CAT(SCRAP_PTR):=WHEN_SCRAP;TRANS(SCRAP_PTR):=TEXT_PTR;
TEXT_PTR:=TEXT_PTR+1;TOK_START(TEXT_PTR):=TOK_PTR;WHEN OTHERS=>NULL;
END CASE--{:235}
;WHEN TEX_STRING=>--{234:}
TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=92;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=104;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=98;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=111;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=120;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=123;TOK_PTR:=TOK_PTR+1;
FOR L IN ID_FIRST..ID_LOC-1 LOOP IF TOK_PTR+2>MAX_TOKS THEN TEXT_IO.
NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Sorry, "&"token"&
" capacity exceeded");ERROR;HISTORY:=FATAL_MESSAGE;RAISE END_OF_AWEAVE;
END IF;TOK_MEM(TOK_PTR):=BUFFER(L);TOK_PTR:=TOK_PTR+1;END LOOP;
TOK_MEM(TOK_PTR):=125;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PDOLLAR;
TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=MATH;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR--{:234}
;WHEN OTHERS=>EASY_CASES;END CASE--{:225}
;NEXT_CONTROL:=GET_NEXT;
IF(NEXT_CONTROL=124)OR(NEXT_CONTROL=123)THEN RETURN;END IF;END LOOP;
END ADA_PARSE;--{:223}{308:}
