SEPARATE(PARSING)PROCEDURE DO_CASES IS BEGIN CASE CAT(PP)IS WHEN
ACCEPT_SCRAP=>--{177:}
IF CAT(PP+1..PP+2)=(MATH,FOLLOWS)THEN TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(
PP);TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=INDENT;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=OUTDENT;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+2);
TOK_PTR:=TOK_PTR+1;RED(PP,3,BEGINNING,-2);GOTO FOUND;
ELSIF CAT(PP+1..PP+2)=(MATH,SEMI)THEN TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(
PP);TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+2);TOK_PTR:=TOK_PTR+1;
RED(PP,3,STMT,-3);GOTO FOUND;END IF--{:177}
;WHEN AND_SCRAP=>--{178:}
IF CAT(PP+1)=THEN_SCRAP THEN TOK_MEM(TOK_PTR):=92;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=65;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=78;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=84;TOK_PTR:=TOK_PTR+1;
RED(PP,2,MATH,-3);GOTO FOUND;END IF--{:178}
;WHEN ARROW=>--{179:}
SQ(PP,1,MATH,-3);GOTO FOUND--{:179}
;WHEN BASE=>--{180:}
IF CAT(PP+1)=BASE THEN TOK_MEM(TOK_PTR):=92;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=98;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=110;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=123;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=125;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=123;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=125;TOK_PTR:=TOK_PTR+1;
RED(PP,2,MATH,-3);GOTO FOUND;END IF--{:180}
;WHEN BEGIN_LABEL_SCRAP=>--{181:}
IF CAT(PP+1..PP+2)=(MATH,END_LABEL_SCRAP)THEN TOK_MEM(TOK_PTR):=TOK_FLAG
+TRANS(PP);TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PDOLLAR;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+2);TOK_PTR:=TOK_PTR+1;
RED(PP,3,LABEL,-1);GOTO FOUND;END IF--{:181}
;WHEN BEGINNING=>--{182:}
IF CAT(PP+1)=STMT THEN TOK_MEM(TOK_PTR):=FORCE;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=INDENT;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=FORCE;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);TOK_PTR:=TOK_PTR+1;
RED(PP,2,STMT,-3);GOTO FOUND;END IF--{:182}
;WHEN CASE_SCRAP=>--{183:}
IF CAT(PP+1..PP+3)=(MATH,FOLLOWS,DECL)THEN TOK_MEM(TOK_PTR):=TOK_FLAG+
TRANS(PP);TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=INDENT;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=SSPACE;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=INDENT;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+2);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=FORCE;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+3);TOK_PTR:=TOK_PTR+1;
RED(PP,4,DECL,-3);GOTO FOUND;
ELSIF CAT(PP+1..PP+3)=(MATH,FOLLOWS,STMT)THEN TOK_MEM(TOK_PTR):=FORCE;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=INDENT;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=SSPACE;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=INDENT;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+2);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=FORCE;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+3);TOK_PTR:=TOK_PTR+1;
RED(PP,4,STMT,-3);GOTO FOUND;END IF--{:183}
;WHEN CLAUSE=>--{184:}
IF CAT(PP+1)=DECL THEN TOK_MEM(TOK_PTR):=FORCE;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=BACKUP;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=FORCE;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);TOK_PTR:=TOK_PTR+1;
RED(PP,2,DECL,-3);GOTO FOUND;
ELSIF CAT(PP+1)=STMT THEN TOK_MEM(TOK_PTR):=FORCE;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=BACKUP;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=FORCE;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);TOK_PTR:=TOK_PTR+1;
RED(PP,2,STMT,-3);GOTO FOUND;END IF--{:184}
;WHEN COLON=>--{185:}
IF CAT(PP+1)=EXCEPTION_SCRAP THEN SQ(PP+1,1,MATH,-1);GOTO FOUND;
ELSIF CAT(PP+1)=IN_SCRAP THEN TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=92;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=38;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=123;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=105;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=110;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=125;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=SSPACE;TOK_PTR:=TOK_PTR+1;
RED(PP,2,COLON,-2);GOTO FOUND;END IF--{:185}
;WHEN DECL=>--{186:}
IF CAT(PP+1)=BEGINNING THEN TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=FORCE;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=BACKUP;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=FORCE;TOK_PTR:=TOK_PTR+1;RED(PP,2,STMT,-3);GOTO FOUND;
ELSIF CAT(PP+1)=DECL THEN TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=FORCE;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);TOK_PTR:=TOK_PTR+1;
RED(PP,2,DECL,-3);GOTO FOUND;
ELSIF CAT(PP+1..PP+2)=(MOD_SCRAP,SEMI)THEN TOK_MEM(TOK_PTR):=TOK_FLAG+
TRANS(PP);TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=FORCE;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1+1);TOK_PTR:=TOK_PTR+1;
RED(PP,3,DECL,-3);GOTO FOUND;
ELSIF CAT(PP+1)=TERMINATOR THEN TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=CANCEL;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=OUTDENT;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=FORCE;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=FORCE;TOK_PTR:=TOK_PTR+1;
RED(PP,2,DECL,-3);GOTO FOUND;
ELSIF CAT(PP+1)=WITH_SCRAP THEN TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=FORCE;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);TOK_PTR:=TOK_PTR+1;
RED(PP,2,WITH_SCRAP,-1);GOTO FOUND;END IF--{:186}
;WHEN DIGIT_SCRAP=>--{187:}
IF CAT(PP+1)=BASE THEN TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);
TOK_PTR:=TOK_PTR+1;RED(PP,2,BASE,-1);GOTO FOUND;
ELSIF CAT(PP+1)=DIGIT_SCRAP THEN SQ(PP,2,DIGIT_SCRAP,-2);GOTO FOUND;
ELSIF CAT(PP+1)=PERIOD THEN SQ(PP,2,DIGIT_SCRAP,-2);GOTO FOUND;
ELSE SQ(PP,1,MATH,-3);GOTO FOUND;END IF--{:187}
;WHEN ELSE_SCRAP=>--{188:}
IF CAT(PP+1)=ELSE_SCRAP THEN TOK_MEM(TOK_PTR):=92;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=79;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=82;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=69;TOK_PTR:=TOK_PTR+1;
RED(PP,2,MATH,-3);GOTO FOUND;
ELSIF CAT(PP+1)=WHEN_SCRAP THEN TOK_MEM(TOK_PTR):=92;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=79;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=82;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=87;TOK_PTR:=TOK_PTR+1;
RED(PP,2,WHEN_SCRAP,-1);GOTO FOUND;END IF--{:188}
;WHEN ENDING=>--{189:}
IF CAT(PP+1..PP+2)=(BEGINNING,SEMI)THEN TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS
(PP);TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=SSPACE;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1+1);TOK_PTR:=TOK_PTR+1;
RED(PP,3,TERMINATOR,-1);GOTO FOUND;
ELSIF CAT(PP+1..PP+2)=(CASE_SCRAP,SEMI)THEN TOK_MEM(TOK_PTR):=BACKUP;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=OUTDENT;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=SSPACE;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1+1);TOK_PTR:=TOK_PTR+1;
RED(PP,3,TERMINATOR,-1);GOTO FOUND;
ELSIF CAT(PP+1..PP+2)=(IF_SCRAP,SEMI)THEN TOK_MEM(TOK_PTR):=TOK_FLAG+
TRANS(PP);TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=SSPACE;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=OUTDENT;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1+1);TOK_PTR:=TOK_PTR+1;
RED(PP,3,TERMINATOR,-1);GOTO FOUND;
ELSIF CAT(PP+1..PP+2)=(LOOP_SCRAP,SEMI)THEN TOK_MEM(TOK_PTR):=TOK_FLAG+
TRANS(PP);TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=SSPACE;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1+1);
TOK_PTR:=TOK_PTR+1;RED(PP,3,TERMINATOR,-1);GOTO FOUND;
ELSIF CAT(PP+1..PP+3)=(LOOP_SCRAP,MATH,SEMI)THEN TOK_MEM(TOK_PTR):=
TOK_FLAG+TRANS(PP);TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=SSPACE;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=SSPACE;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+2);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+3);TOK_PTR:=TOK_PTR+1;
RED(PP,4,TERMINATOR,-1);GOTO FOUND;
ELSIF CAT(PP+1..PP+2)=(MATH,SEMI)THEN TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(
PP);TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=SSPACE;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+2);TOK_PTR:=TOK_PTR+1;
RED(PP,3,TERMINATOR,-1);GOTO FOUND;
ELSIF CAT(PP+1..PP+2)=(RECORD_SCRAP,SEMI)THEN TOK_MEM(TOK_PTR):=OUTDENT;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=SSPACE;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1+1);TOK_PTR:=TOK_PTR+1;
RED(PP,3,TERMINATOR,-1);GOTO FOUND;
ELSIF CAT(PP+1)=SEMI THEN SQ(PP,2,TERMINATOR,-1);GOTO FOUND;END IF
--{:189}
;WHEN EXCEPTION_SCRAP=>--{190:}
TOK_MEM(TOK_PTR):=BACKUP;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);TOK_PTR:=TOK_PTR+1;
RED(PP,1,BEGINNING,-2);GOTO FOUND--{:190}
;WHEN EXP=>--{191:}
IF(CAT(PP+1)=DIGIT_SCRAP)AND(CAT(PP+2)/=DIGIT_SCRAP)THEN TOK_MEM(TOK_PTR
):=TOK_FLAG+TRANS(PP);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=125;TOK_PTR:=TOK_PTR+1;RED(PP,2,MATH,-3);GOTO FOUND;
ELSIF(CAT(PP+1)=MATH)AND((CAT(PP+2)=DIGIT_SCRAP)AND(CAT(PP+3)/=
DIGIT_SCRAP))THEN TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+2);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=125;TOK_PTR:=TOK_PTR+1;
RED(PP,3,MATH,-3);GOTO FOUND;END IF--{:191}
;WHEN GENERIC_SCRAP=>--{192:}
IF CAT(PP+1)=DECL THEN TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=FORCE;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);TOK_PTR:=TOK_PTR+1;
RED(PP,2,GENERIC_SCRAP,0);GOTO FOUND;
ELSIF CAT(PP+1)=PROC THEN TOK_MEM(TOK_PTR):=INDENT;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=OUTDENT;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=FORCE;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);
TOK_PTR:=TOK_PTR+1;RED(PP,2,PROC,-1);GOTO FOUND;END IF--{:192}
;WHEN GPROC=>--{193:}
IF CAT(PP+1..PP+2)=(MATH,SEMI)THEN TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=INDENT;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=OUTDENT;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+2);
TOK_PTR:=TOK_PTR+1;RED(PP,3,DECL,-3);GOTO FOUND;
ELSIF CAT(PP+1..PP+4)=(MATH,FOLLOWS,MATH,SEMI)THEN TOK_MEM(TOK_PTR):=
TOK_FLAG+TRANS(PP);TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=INDENT;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1+1);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1+2);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=OUTDENT;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+4);
TOK_PTR:=TOK_PTR+1;RED(PP,5,DECL,-3);GOTO FOUND;END IF--{:193}
;WHEN OTHERS=>NULL;END CASE;PP:=PP+1;<<FOUND>>NULL;END DO_CASES;
--{:176}{219:}
