SEPARATE(PARSING)FUNCTION TRANSLATE RETURN TEXT_POINTER IS K:
LONG_BUFFER_INDEX;BEGIN PP:=SCRAP_BASE;LO_PTR:=PP-1;HI_PTR:=PP;--{215:}
LOOP--{216:}
IF LO_PTR<PP+4 THEN LOOP IF HI_PTR<=SCRAP_PTR THEN LO_PTR:=LO_PTR+1;
CAT(LO_PTR):=CAT(HI_PTR);TRANS(LO_PTR):=TRANS(HI_PTR);HI_PTR:=HI_PTR+1;
END IF;EXIT WHEN(HI_PTR>SCRAP_PTR)OR(LO_PTR=PP+4);END LOOP;
FOR I IN LO_PTR+1..PP+4 LOOP CAT(I):=0;END LOOP;END IF--{:216}
;
IF(TOK_PTR+11>MAX_TOKS)OR(TEXT_PTR+4>MAX_TEXTS)THEN
--IF TOK_PTR>MAX_TOK_PTR THEN MAX_TOK_PTR:=TOK_PTR;END IF;
--IF TEXT_PTR>MAX_TXT_PTR THEN MAX_TXT_PTR:=TEXT_PTR;END IF;
TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Sorry, "&"token/text"&
" capacity exceeded");ERROR;HISTORY:=FATAL_MESSAGE;RAISE END_OF_AWEAVE;
END IF;EXIT WHEN PP>LO_PTR;--{174:}
IF CAT(PP)<IF_SCRAP THEN DO_CASES;ELSE CASE CAT(PP)IS WHEN IF_SCRAP=>
--{194:}
IF CAT(PP+1..PP+3)=(MATH,THEN_SCRAP,STMT)THEN TOK_MEM(TOK_PTR):=FORCE;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=INDENT;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=SSPACE;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=OUTDENT;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+2);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=FORCE;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+3);TOK_PTR:=TOK_PTR+1;
RED(PP,4,STMT,-3);GOTO FOUND;END IF--{:194}
;WHEN IN_SCRAP=>--{195:}
SQ(PP,1,MATH,-3);GOTO FOUND--{:195}
;WHEN LABEL=>--{196:}
IF CAT(PP+1)=LABEL THEN TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=SSPACE;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=OPT;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=55;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PP+1;TOK_PTR:=TOK_PTR+1;
RED(PP,2,LABEL,-1);GOTO FOUND;
ELSIF CAT(PP+1)=STMT THEN TOK_MEM(TOK_PTR):=FORCE;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=BACKUP;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=SSPACE;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=CANCEL;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);
TOK_PTR:=TOK_PTR+1;RED(PP,2,STMT,-3);GOTO FOUND;END IF--{:196}
;WHEN LOOP_SCRAP=>--{197:}
SQ(PP,1,BEGINNING,-2);GOTO FOUND--{:197}
;WHEN MATH=>--{198:}
IF CAT(PP+1..PP+2)=(AND_SCRAP,MATH)THEN SQ(PP,3,MATH,-3);GOTO FOUND;
ELSIF CAT(PP+1..PP+2)=(COLON,BEGINNING)THEN TOK_MEM(TOK_PTR):=BACKUP;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=SSPACE;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PDOLLAR;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=SSPACE;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+2);TOK_PTR:=TOK_PTR+1;
RED(PP,3,BEGINNING,-3);GOTO FOUND;
ELSIF CAT(PP+1..PP+2)=(COLON,DECL)THEN TOK_MEM(TOK_PTR):=FORCE;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=BACKUP;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=SSPACE;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PDOLLAR;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=SSPACE;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=CANCEL;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+2);TOK_PTR:=TOK_PTR+1;
RED(PP,3,DECL,-3);GOTO FOUND;
ELSIF CAT(PP+1..PP+3)=(COLON,MATH,SEMI)THEN TOK_MEM(TOK_PTR):=PDOLLAR;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+2);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+3);TOK_PTR:=TOK_PTR+1;
RED(PP,4,DECL,-3);GOTO FOUND;
ELSIF CAT(PP+1..PP+2)=(ELSE_SCRAP,MATH)THEN TOK_MEM(TOK_PTR):=TOK_FLAG+
TRANS(PP);TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=92;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=86;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+2);TOK_PTR:=TOK_PTR+1;
RED(PP,3,MATH,-3);GOTO FOUND;
ELSIF CAT(PP+1..PP+3)=(FOLLOWS,MATH,SEMI)THEN TOK_MEM(TOK_PTR):=PDOLLAR;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+2);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+3);TOK_PTR:=TOK_PTR+1;
RED(PP,4,DECL,-3);GOTO FOUND;
ELSIF CAT(PP+1..PP+2)=(FOLLOWS,RECORD_SCRAP)THEN TOK_MEM(TOK_PTR):=
PDOLLAR;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=INDENT;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=FORCE;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+2);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=INDENT;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=FORCE;TOK_PTR:=TOK_PTR+1;RED(PP,3,DECL,-3);GOTO FOUND;
ELSIF CAT(PP+1)=LOOP_SCRAP THEN TOK_MEM(TOK_PTR):=PDOLLAR;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=SSPACE;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);TOK_PTR:=TOK_PTR+1;
RED(PP,2,BEGINNING,-2);GOTO FOUND;
ELSIF CAT(PP+1)=MATH THEN SQ(PP,2,MATH,-3);GOTO FOUND;
ELSIF CAT(PP+1)=SEMI THEN TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);TOK_PTR:=TOK_PTR+1;
RED(PP,2,STMT,-3);GOTO FOUND;
ELSIF CAT(PP+1)=STMT THEN TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);TOK_PTR:=TOK_PTR+1;
RED(PP,2,STMT,-3);GOTO FOUND;
ELSIF CAT(PP+1)=SEPARATE_SCRAP THEN TOK_MEM(TOK_PTR):=PDOLLAR;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);TOK_PTR:=TOK_PTR+1;
RED(PP,2,SEPARATE_SCRAP,-1);GOTO FOUND;
ELSIF CAT(PP+1..PP+2)=(WHEN_SCRAP,MATH)THEN SQ(PP,3,MATH,-3);GOTO FOUND;
ELSIF CAT(PP+1)=WITH_SCRAP THEN TOK_MEM(TOK_PTR):=PDOLLAR;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PSPACE;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);TOK_PTR:=TOK_PTR+1;
RED(PP,2,WITH_SCRAP,-1);GOTO FOUND;END IF--{:198}
;WHEN MOD_SCRAP=>--{199:}
IF CAT(PP+1)=SEMI THEN TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=FORCE;TOK_PTR:=TOK_PTR+1;
RED(PP,2,STMT,-3);GOTO FOUND;ELSE SQ(PP,1,MATH,-3);GOTO FOUND;END IF
--{:199}
;WHEN NEW_SCRAP=>--{200:}
SQ(PP,1,MATH,-3);GOTO FOUND--{:200}
;WHEN NOT_SCRAP=>--{201:}
IF CAT(PP+1)=IN_SCRAP THEN TOK_MEM(TOK_PTR):=92;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=110;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=111;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=116;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=105;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=110;
TOK_PTR:=TOK_PTR+1;RED(PP,2,MATH,-3);GOTO FOUND;ELSE SQ(PP,1,MATH,-3);
GOTO FOUND;END IF--{:201}
;WHEN OPEN_SCRAP=>--{202:}
IF CAT(PP+1)=DECL THEN TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=92;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=44;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=OPT;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=53;
TOK_PTR:=TOK_PTR+1;RED(PP,2,OPEN_SCRAP,0);GOTO FOUND;
ELSIF CAT(PP+1..PP+2)=(MATH,CLOSE_SCRAP)THEN TOK_MEM(TOK_PTR):=INDENT;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=OUTDENT;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+2);TOK_PTR:=TOK_PTR+1;
RED(PP,3,MATH,-3);GOTO FOUND;
ELSIF CAT(PP+1..PP+4)=(MATH,COLON,MATH,CLOSE_SCRAP)THEN TOK_MEM(TOK_PTR)
:=TOK_FLAG+TRANS(PP);TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=INDENT;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1+1);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1+2);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=OUTDENT;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+4);TOK_PTR:=TOK_PTR+1;
RED(PP,5,MATH,-3);GOTO FOUND;END IF--{:202}
;WHEN PERIOD=>--{203:}
SQ(PP,1,MATH,-3);GOTO FOUND--{:203}
;WHEN PRIVATE_SCRAP=>--{204:}
IF CAT(PP+1)=SEMI THEN SQ(PP,1,MATH,-2);GOTO FOUND;
ELSE TOK_MEM(TOK_PTR):=FORCE;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=BACKUP;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=FORCE;TOK_PTR:=TOK_PTR+1;RED(PP,1,DECL,-3);GOTO FOUND;
END IF--{:204}
;WHEN PROC=>--{205:}
IF CAT(PP+1..PP+3)=(MATH,FOLLOWS,NEW_SCRAP)THEN SQ(PP+2,2,MATH,-3);
GOTO FOUND;
ELSIF CAT(PP+1..PP+3)=(MATH,FOLLOWS,SEPARATE_SCRAP)THEN SQ(PP+2,2,MATH,-
3);GOTO FOUND;
ELSIF CAT(PP+1..PP+2)=(MATH,FOLLOWS)THEN TOK_MEM(TOK_PTR):=TOK_FLAG+
TRANS(PP);TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=INDENT;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=OUTDENT;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+2);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=CANCEL;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=INDENT;TOK_PTR:=TOK_PTR+1;RED(PP,3,DECL,-3);
GOTO FOUND;
ELSIF CAT(PP+1..PP+2)=(MATH,SEMI)THEN TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(
PP);TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=INDENT;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=OUTDENT;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+2);
TOK_PTR:=TOK_PTR+1;RED(PP,3,DECL,-3);GOTO FOUND;END IF--{:205}
;WHEN RETURN_SCRAP=>--{206:}
IF CAT(PP+1)=SEMI THEN SQ(PP,2,STMT,-3);GOTO FOUND;
ELSE TOK_MEM(TOK_PTR):=PSPACE;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=SSPACE;TOK_PTR:=TOK_PTR+1;RED(PP,1,MATH,-3);
GOTO FOUND;END IF--{:206}
;WHEN SEPARATE_SCRAP=>--{207:}
IF CAT(PP+1)=MATH THEN TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=SSPACE;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;RED(PP,2,DECL,-3);
GOTO FOUND;END IF--{:207}
;WHEN STMT=>--{208:}
IF CAT(PP+1..PP+2)=(ELSE_SCRAP,STMT)THEN TOK_MEM(TOK_PTR):=TOK_FLAG+
TRANS(PP);TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=FORCE;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=BACKUP;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=FORCE;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+2);TOK_PTR:=TOK_PTR+1;
RED(PP,3,STMT,-3);GOTO FOUND;
ELSIF CAT(PP+1)=STMT THEN TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=BREAK_SPACE;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);TOK_PTR:=TOK_PTR+1;
RED(PP,2,STMT,-3);GOTO FOUND;
ELSIF CAT(PP+1)=TERMINATOR THEN TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=CANCEL;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=OUTDENT;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=FORCE;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=FORCE;TOK_PTR:=TOK_PTR+1;
RED(PP,2,STMT,-3);GOTO FOUND;END IF--{:208}
;WHEN WHEN_SCRAP=>--{209:}
IF CAT(PP+1..PP+2)=(MATH,ARROW)THEN TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP)
;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+2);TOK_PTR:=TOK_PTR+1;
RED(PP,3,CLAUSE,-1);GOTO FOUND;END IF--{:209}
;WHEN WITH_SCRAP=>--{210:}
IF CAT(PP+1)=COLON THEN SQ(PP,2,WITH_SCRAP,-1);GOTO FOUND;
ELSIF CAT(PP+1..PP+2)=(MATH,SEMI)THEN TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(
PP);TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+2);TOK_PTR:=TOK_PTR+1;
RED(PP,3,DECL,-3);GOTO FOUND;ELSIF CAT(PP+1)=PROC THEN SQ(PP,2,GPROC,0);
GOTO FOUND;
ELSIF CAT(PP+1..PP+2)=(RECORD_SCRAP,COLON)THEN TOK_MEM(TOK_PTR):=PDOLLAR
;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=INDENT;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=FORCE;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=INDENT;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
RED(PP,2,MATH,-1);GOTO FOUND;
ELSIF CAT(PP+1)=RECORD_SCRAP THEN TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=INDENT;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=FORCE;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=INDENT;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(PP+1);
TOK_PTR:=TOK_PTR+1;RED(PP,2,DECL,-3);GOTO FOUND;END IF--{:210}
;WHEN OTHERS=>NULL;END CASE;PP:=PP+1;END IF;<<FOUND>>NULL--{:174}
;END LOOP--{:215}
;IF(LO_PTR=SCRAP_BASE)AND(CAT(LO_PTR)/=MATH)THEN RETURN TRANS(LO_PTR);
ELSE--{220:}
FOR J IN SCRAP_BASE..LO_PTR LOOP IF J/=SCRAP_BASE THEN TOK_MEM(TOK_PTR)
:=32;TOK_PTR:=TOK_PTR+1;END IF;
IF CAT(J)=MATH OR CAT(J)=OPEN_SCRAP OR CAT(J)=CLOSE_SCRAP THEN TOK_MEM(
TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;END IF;
TOK_MEM(TOK_PTR):=TOK_FLAG+TRANS(J);TOK_PTR:=TOK_PTR+1;
IF CAT(J)=MATH OR CAT(J)=OPEN_SCRAP OR CAT(J)=CLOSE_SCRAP THEN TOK_MEM(
TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;END IF;
IF TOK_PTR+6>MAX_TOKS THEN TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Sorry, "&"token"&
" capacity exceeded");ERROR;HISTORY:=FATAL_MESSAGE;RAISE END_OF_AWEAVE;
END IF;END LOOP;TEXT_PTR:=TEXT_PTR+1;TOK_START(TEXT_PTR):=TOK_PTR;
RETURN TEXT_PTR-1--{:220}
;END IF;END TRANSLATE;--{:219}{223:}
