WITH TEXT_IO;WITH INPUT_OUTPUT;USE INPUT_OUTPUT;
PACKAGE BODY SEARCHING IS--{61:}
FUNCTION ID_LOOKUP(T:EIGHT_BITS)RETURN NAME_POINTER IS C:EIGHT_BITS;
I:BUFFER_INDEX;H:HASH_INDEX;K:BYTE_INDEX;W:W_RANGE;
L:BUFFER_INDEX:=ID_LOC-ID_FIRST;P,Q:NAME_POINTER;BEGIN--{62:}
H:=BUFFER(ID_FIRST);I:=ID_FIRST+1;
WHILE I<ID_LOC LOOP H:=(H+H+BUFFER(I))MOD HASH_SIZE;I:=I+1;END LOOP
--{:62}
;--{63:}
P:=HASH(H);
WHILE P/=0 LOOP IF(BYTE_START(P+WW)-BYTE_START(P)=L)AND((ILK(P)=T)OR((T=
NORMAL)AND(ILK(P)>TYPEWRITER)))THEN--{64:}
I:=ID_FIRST;K:=BYTE_START(P);W:=P MOD WW;
WHILE(I<ID_LOC)AND(BUFFER(I)=BYTE_MEM(W,K))LOOP I:=I+1;K:=K+1;END LOOP;
IF I=ID_LOC THEN GOTO FOUND;END IF--{:64}
;END IF;P:=LINK(P);END LOOP;P:=NAME_PTR;LINK(P):=HASH(H);HASH(H):=P
--{:63}
;<<FOUND>>IF P=NAME_PTR THEN--{65:}
W:=NAME_PTR MOD WW;K:=BYTE_PTR(W);
IF K+L>MAX_BYTES THEN TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Sorry, "&"byte memory"&
" capacity exceeded");ERROR;HISTORY:=FATAL_MESSAGE;RAISE END_OF_AWEAVE;
END IF;
IF NAME_PTR>MAX_NAMES-WW THEN TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Sorry, "&"name"&
" capacity exceeded");ERROR;HISTORY:=FATAL_MESSAGE;RAISE END_OF_AWEAVE;
END IF;I:=ID_FIRST;WHILE I<ID_LOC LOOP BYTE_MEM(W,K):=BUFFER(I);K:=K+1;
I:=I+1;END LOOP;BYTE_PTR(W):=K;BYTE_START(NAME_PTR+WW):=K;
NAME_PTR:=NAME_PTR+1;ILK(P):=T;XREF(P):=0--{:65}
;END IF;RETURN P;END ID_LOOKUP;--{:61}{76:}
FUNCTION MOD_LOOKUP(L:SIXTEEN_BITS)RETURN NAME_POINTER IS C:COMPARE:=
GREATER;J:LONG_NAME_INDEX;K:BYTE_INDEX;W:W_RANGE;P:NAME_POINTER:=ROOT;
Q:NAME_POINTER:=0;BEGIN WHILE P/=0 LOOP--{78:}
K:=BYTE_START(P);W:=P MOD WW;C:=EQUAL;J:=1;
WHILE(K<BYTE_START(P+WW))AND(J<=L)AND(MOD_TEXT(J)=BYTE_MEM(W,K))LOOP K:=
K+1;J:=J+1;END LOOP;IF K=BYTE_START(P+WW)THEN IF J>L THEN C:=EQUAL;
ELSE C:=EXTENSION;END IF;ELSIF J>L THEN C:=PREFIX;
ELSIF MOD_TEXT(J)<BYTE_MEM(W,K)THEN C:=LESS;ELSE C:=GREATER;END IF
--{:78}
;Q:=P;IF C=LESS THEN P:=LLINK(Q);ELSIF C=GREATER THEN P:=RLINK(Q);
ELSE GOTO FOUND;END IF;END LOOP;--{77:}
W:=NAME_PTR MOD WW;K:=BYTE_PTR(W);
IF K+L>MAX_BYTES THEN TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Sorry, "&"byte memory"&
" capacity exceeded");ERROR;HISTORY:=FATAL_MESSAGE;RAISE END_OF_AWEAVE;
END IF;
IF NAME_PTR>MAX_NAMES-WW THEN TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Sorry, "&"name"&
" capacity exceeded");ERROR;HISTORY:=FATAL_MESSAGE;RAISE END_OF_AWEAVE;
END IF;P:=NAME_PTR;IF C=LESS THEN LLINK(Q):=P;ELSE RLINK(Q):=P;END IF;
LLINK(P):=0;RLINK(P):=0;C:=EQUAL;
FOR M IN 1..L LOOP BYTE_MEM(W,K+M-1):=MOD_TEXT(M);END LOOP;
BYTE_PTR(W):=K+L;BYTE_START(NAME_PTR+WW):=K+L;NAME_PTR:=NAME_PTR+1
--{:77}
;
<<FOUND>>IF C/=EQUAL THEN IF NOT PHASE_ONE THEN TEXT_IO.NEW_LINE(TEXT_IO
.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Incompatible section names");
ERROR;END IF;P:=0;END IF;RETURN P;END MOD_LOOKUP;--{:76}{80:}
FUNCTION PREFIX_LOOKUP(L:SIXTEEN_BITS)RETURN NAME_POINTER IS C:COMPARE;
COUNT:NAME_INDEX:=0;J:LONG_NAME_INDEX;K:BYTE_INDEX;W:W_RANGE;
P:NAME_POINTER:=ROOT;Q:NAME_POINTER:=0;R:NAME_POINTER:=0;
BEGIN WHILE P/=0 LOOP--{78:}
K:=BYTE_START(P);W:=P MOD WW;C:=EQUAL;J:=1;
WHILE(K<BYTE_START(P+WW))AND(J<=L)AND(MOD_TEXT(J)=BYTE_MEM(W,K))LOOP K:=
K+1;J:=J+1;END LOOP;IF K=BYTE_START(P+WW)THEN IF J>L THEN C:=EQUAL;
ELSE C:=EXTENSION;END IF;ELSIF J>L THEN C:=PREFIX;
ELSIF MOD_TEXT(J)<BYTE_MEM(W,K)THEN C:=LESS;ELSE C:=GREATER;END IF
--{:78}
;IF C=LESS THEN P:=LLINK(P);ELSIF C=GREATER THEN P:=RLINK(P);ELSE R:=P;
COUNT:=COUNT+1;Q:=RLINK(P);P:=LLINK(P);END IF;IF P=0 THEN P:=Q;Q:=0;
END IF;END LOOP;
IF COUNT/=1 THEN IF COUNT=0 THEN IF NOT PHASE_ONE THEN TEXT_IO.NEW_LINE(
TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Name does not match");ERROR;
END IF;
ELSE IF NOT PHASE_ONE THEN TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Ambiguous prefix");ERROR;END IF;
END IF;END IF;RETURN R;END PREFIX_LOOKUP;--{:80}
END SEARCHING;--{:5}{6:}
