WITH DATA_STRUCTURES;USE DATA_STRUCTURES;PACKAGE SEARCHING IS--{60:}
FUNCTION ID_LOOKUP(T:EIGHT_BITS)RETURN NAME_POINTER;--{:60}{75:}
FUNCTION MOD_LOOKUP(L:SIXTEEN_BITS)RETURN NAME_POINTER;--{:75}{79:}
FUNCTION PREFIX_LOOKUP(L:SIXTEEN_BITS)RETURN NAME_POINTER;--{:79}
END SEARCHING;
