WITH TEXT_IO,INT_NUMBER_IO;WITH INPUT_OUTPUT;USE INPUT_OUTPUT;
WITH SEARCHING;USE SEARCHING;WITH LEXICAL_SCANNING;USE LEXICAL_SCANNING;
WITH OUTPUT;USE OUTPUT;WITH PARSING;USE PARSING;
PACKAGE BODY SECOND_PHASE IS--{245:}
PROCEDURE PUSH_LEVEL(P:TEXT_POINTER)IS BEGIN IF STACK_PTR=STACK_SIZE
THEN TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Sorry, "&"stack"&
" capacity exceeded");ERROR;HISTORY:=FATAL_MESSAGE;RAISE END_OF_AWEAVE;
ELSE IF STACK_PTR>0 THEN STACK(STACK_PTR):=CUR_STATE;END IF;
STACK_PTR:=STACK_PTR+1;
--IF STACK_PTR>MAX_STACK_PTR THEN MAX_STACK_PTR:=STACK_PTR;END IF;
CUR_TOK:=TOK_START(P);CUR_END:=TOK_START(P+1);END IF;END PUSH_LEVEL;
--{:245}{248:}
FUNCTION GET_OUTPUT RETURN EIGHT_BITS IS A:SIXTEEN_BITS;
BEGIN<<RESTART>>WHILE CUR_TOK=CUR_END LOOP STACK_PTR:=STACK_PTR-1;
CUR_STATE:=STACK(STACK_PTR);END LOOP;A:=TOK_MEM(CUR_TOK);
CUR_TOK:=CUR_TOK+1;IF A>=8#400# THEN CUR_NAME:=A MOD ID_FLAG;
CASE A/ID_FLAG IS WHEN 2=>A:=RES_WORD;WHEN 3=>A:=MOD_NAME;
WHEN 4=>PUSH_LEVEL(CUR_NAME);GOTO RESTART;WHEN 5=>PUSH_LEVEL(CUR_NAME);
CUR_MODE:=INNER;GOTO RESTART;WHEN OTHERS=>A:=IDENTIFIER;END CASE;END IF;
RETURN A;END GET_OUTPUT;--{:248}{250:}
PROCEDURE OUTPUT_ADA IS SAVE_TOK_PTR,SAVE_TEXT_PTR,SAVE_NEXT_CONTROL:
SIXTEEN_BITS;P:TEXT_POINTER;BEGIN SAVE_TOK_PTR:=TOK_PTR;
SAVE_TEXT_PTR:=TEXT_PTR;SAVE_NEXT_CONTROL:=NEXT_CONTROL;
NEXT_CONTROL:=124;P:=ADA_TRANSLATE;TOK_MEM(TOK_PTR):=P+INNER_TOK_FLAG;
TOK_PTR:=TOK_PTR+1;MAKE_OUTPUT;
--IF TEXT_PTR>MAX_TXT_PTR THEN MAX_TXT_PTR:=TEXT_PTR;END IF;
--IF TOK_PTR>MAX_TOK_PTR THEN MAX_TOK_PTR:=TOK_PTR;END IF;
TEXT_PTR:=SAVE_TEXT_PTR;TOK_PTR:=SAVE_TOK_PTR;
NEXT_CONTROL:=SAVE_NEXT_CONTROL;END OUTPUT_ADA;--{:250}{251:}
PROCEDURE MAKE_OUTPUT IS A:EIGHT_BITS;B:EIGHT_BITS;K,K_LIMIT:BYTE_INDEX;
W:W_RANGE;J:LONG_BUFFER_INDEX;D:INTEGER;STRING_DELIMITER:ASCII_CODE;
SAVE_LOC,SAVE_LIMIT:LONG_BUFFER_INDEX;CUR_MOD_NAME:NAME_POINTER;
SAVE_MODE:OUTPUT_MODE;IGNORE_SPACES:BOOLEAN;
BEGIN TOK_MEM(TOK_PTR):=END_TRANSLATION;TOK_PTR:=TOK_PTR+1;
TEXT_PTR:=TEXT_PTR+1;TOK_START(TEXT_PTR):=TOK_PTR;
PUSH_LEVEL(TEXT_PTR-1);LOOP A:=GET_OUTPUT;IGNORE_SPACES:=FALSE;
<<RESWITCH>>CASE A IS WHEN END_TRANSLATION=>RETURN;
WHEN IDENTIFIER!RES_WORD=>--{253:}
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=92;
IF A=IDENTIFIER THEN IF ILK(CUR_NAME)=PREDEFINED THEN IF OUT_PTR=
LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=112;
ELSIF BYTE_START(CUR_NAME+WW)-BYTE_START(CUR_NAME)=1 THEN IF OUT_PTR=
LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=124;ELSE IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=92;END IF;
ELSE IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=38;END IF;
IF BYTE_START(CUR_NAME+WW)-BYTE_START(CUR_NAME)=1 THEN IF OUT_PTR=
LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=BYTE_MEM(CUR_NAME MOD WW,BYTE_START(CUR_NAME));
ELSE OUT_NAME(CUR_NAME);END IF--{:253}
;WHEN MOD_NAME=>--{257:}
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=92;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=88;CUR_XREF:=XREF(CUR_NAME);
IF XMEM(CUR_XREF).NUM_FIELD>=DEF_FLAG THEN OUT_MOD(XMEM(CUR_XREF).
NUM_FIELD-DEF_FLAG);
IF PHASE_THREE THEN CUR_XREF:=XMEM(CUR_XREF).XLINK_FIELD;
WHILE XMEM(CUR_XREF).NUM_FIELD>=DEF_FLAG LOOP IF OUT_PTR=LINE_LENGTH
THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=44;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=32;OUT_MOD(XMEM(CUR_XREF).NUM_FIELD-DEF_FLAG);
CUR_XREF:=XMEM(CUR_XREF).XLINK_FIELD;END LOOP;END IF;
ELSE IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=48;END IF;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;
END IF;OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=58;--{258:}
K:=BYTE_START(CUR_NAME);W:=CUR_NAME MOD WW;
K_LIMIT:=BYTE_START(CUR_NAME+WW);CUR_MOD_NAME:=CUR_NAME;
WHILE K<K_LIMIT LOOP B:=BYTE_MEM(W,K);K:=K+1;IF B=64 THEN--{259:}
IF BYTE_MEM(W,K)/=64 THEN TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,
"! Illegal control code in section name:");
TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"<");PRINT_ID(CUR_MOD_NAME);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"> ");HISTORY:=ERROR_MESSAGE;END IF;
K:=K+1--{:259}
;END IF;IF B/=124 THEN IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=B;ELSE--{260:}
J:=LIMIT+1;BUFFER(J):=124;STRING_DELIMITER:=0;
LOOP IF K>=K_LIMIT THEN TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,
"! ADA text in section name didn't end:");
TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"<");PRINT_ID(CUR_MOD_NAME);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"> ");HISTORY:=ERROR_MESSAGE;EXIT;
END IF;B:=BYTE_MEM(W,K);K:=K+1;IF B=64 THEN--{261:}
IF J>LONG_BUF_SIZE-4 THEN TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Sorry, "&"buffer"&
" capacity exceeded");ERROR;HISTORY:=FATAL_MESSAGE;RAISE END_OF_AWEAVE;
END IF;BUFFER(J+1):=64;BUFFER(J+2):=BYTE_MEM(W,K);J:=J+2;K:=K+1--{:261}
;ELSE IF B=34 THEN IF STRING_DELIMITER=0 THEN STRING_DELIMITER:=B;
ELSIF STRING_DELIMITER=B THEN STRING_DELIMITER:=0;END IF;
ELSIF(B=39)AND(BYTE_MEM(W,K+1)=39)AND(STRING_DELIMITER=0)THEN J:=J+2;
BUFFER(J-1..J):=(39,BYTE_MEM(W,K));K:=K+3;B:=39;END IF;
IF(B/=124)OR(STRING_DELIMITER/=0)THEN IF J>LONG_BUF_SIZE-3 THEN TEXT_IO.
NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Sorry, "&"buffer"&
" capacity exceeded");ERROR;HISTORY:=FATAL_MESSAGE;RAISE END_OF_AWEAVE;
END IF;J:=J+1;BUFFER(J):=B;ELSE EXIT;END IF;END IF;END LOOP--{:260}
;SAVE_LOC:=LOC;SAVE_LIMIT:=LIMIT;LOC:=LIMIT+2;LIMIT:=J+1;
BUFFER(LIMIT):=124;OUTPUT_ADA;LOC:=SAVE_LOC;LIMIT:=SAVE_LIMIT;END IF;
END LOOP--{:258}
;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=92;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=88--{:257}
;WHEN MATH_BIN!MATH_OP!MATH_REL=>--{254:}
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=92;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=109;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=97;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=116;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=104;
IF A=MATH_BIN THEN IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=98;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=105;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=110;
ELSIF A=MATH_REL THEN IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=114;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=101;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=108;
ELSE IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=111;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=112;END IF;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=123--{:254}
;WHEN CANCEL=>LOOP A:=GET_OUTPUT;EXIT WHEN(A<BACKUP)OR(A>BIG_FORCE);
END LOOP;IGNORE_SPACES:=FALSE;GOTO RESWITCH;
WHEN BIG_CANCEL=>LOOP A:=GET_OUTPUT;
EXIT WHEN((A<BACKUP)AND(A/=32)AND(A NOT IN PSPACE..SSPACE))OR(A>
BIG_FORCE);END LOOP;IGNORE_SPACES:=FALSE;GOTO RESWITCH;
WHEN PDOLLAR|PSPACE..SSPACE=>--{252:}
D:=0;B:=0;
WHILE(A=PDOLLAR)OR(A IN PSPACE..SSPACE)LOOP IF A=PDOLLAR THEN D:=D+1;
ELSE B:=B+A-PSPACE+1;END IF;A:=GET_OUTPUT;
IF CUR_MODE=INNER THEN WHILE A IN BIG_CANCEL..BACKUP LOOP IF A=OPT THEN
A:=GET_OUTPUT;END IF;A:=GET_OUTPUT;END LOOP;END IF;END LOOP;
IF(D MOD 2)=1 THEN IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=92;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=63;END IF;
IF NOT IGNORE_SPACES AND B>1 THEN IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;
END IF;OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=92;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=56;END IF;IGNORE_SPACES:=FALSE;GOTO RESWITCH--{:252}
;WHEN INDENT..BIG_FORCE=>--{255:}
IF A<BREAK_SPACE THEN IF CUR_MODE=OUTER THEN IF OUT_PTR=LINE_LENGTH THEN
BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=92;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=A-CANCEL+48;
IF A=OPT THEN IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=GET_OUTPUT;END IF;
ELSIF A=OPT THEN B:=GET_OUTPUT;END IF;ELSE--{256:}
B:=A;SAVE_MODE:=CUR_MODE;LOOP A:=GET_OUTPUT;
IF(A=CANCEL)OR(A=BIG_CANCEL)THEN GOTO RESWITCH;END IF;
IF((A/=32)AND(A<BREAK_SPACE)AND(A NOT IN PSPACE..SSPACE))OR(A>BIG_FORCE)
THEN IF SAVE_MODE=OUTER THEN IF(OUT_PTR>3)AND THEN(OUT_BUF(OUT_PTR-3..
OUT_PTR)=(92,89,92,80))THEN GOTO RESWITCH;END IF;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=92;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=B-CANCEL+48;
IGNORE_SPACES:=B IN FORCE..BIG_FORCE;
IF A/=END_TRANSLATION THEN FINISH_LINE;END IF;
ELSIF(A/=END_TRANSLATION)AND(CUR_MODE=INNER)THEN IF OUT_PTR=LINE_LENGTH
THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=32;END IF;
GOTO RESWITCH;END IF;IF A>B THEN B:=A;END IF;END LOOP--{:256}
;END IF--{:255}
;WHEN OTHERS=>IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=A;END CASE;END LOOP;
END MAKE_OUTPUT;--{:251}{268:}
PROCEDURE FINISH_ADA IS P:TEXT_POINTER;
BEGIN IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=92;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=80;
IF TOK_PTR+2>MAX_TOKS THEN TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Sorry, "&"token"&
" capacity exceeded");ERROR;HISTORY:=FATAL_MESSAGE;RAISE END_OF_AWEAVE;
END IF;TOK_MEM(TOK_PTR):=FORCE;TOK_PTR:=TOK_PTR+1;APP_COMMENT;
P:=TRANSLATE;TOK_MEM(TOK_PTR):=P+TOK_FLAG;TOK_PTR:=TOK_PTR+1;
MAKE_OUTPUT;
IF(OUT_PTR>1)AND THEN(OUT_BUF(OUT_PTR-1)=92)THEN IF OUT_BUF(OUT_PTR)=54
THEN OUT_PTR:=OUT_PTR-2;
ELSIF OUT_BUF(OUT_PTR)=55 THEN OUT_BUF(OUT_PTR):=89;END IF;END IF;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=92;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=112;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=97;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=114;FINISH_LINE;
--IF TEXT_PTR>MAX_TXT_PTR THEN MAX_TXT_PTR:=TEXT_PTR;END IF;
--IF TOK_PTR>MAX_TOK_PTR THEN MAX_TOK_PTR:=TOK_PTR;END IF;
--IF SCRAP_PTR>MAX_SCR_PTR THEN MAX_SCR_PTR:=SCRAP_PTR;END IF;
TOK_PTR:=1;TEXT_PTR:=1;SCRAP_PTR:=0;END FINISH_ADA;--{:268}{279:}
PROCEDURE FOOTNOTE(FLAG:SIXTEEN_BITS)IS COUNT:INTEGER;
BEGIN IF XMEM(CUR_XREF).NUM_FIELD<=FLAG THEN RETURN;END IF;FINISH_LINE;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=92;
IF FLAG=0 THEN IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=85;
ELSE IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=65;END IF;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;
END IF;OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=32;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=115;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=101;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=99;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=116;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=105;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=111;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=110;--{280:}
COUNT:=1;
LOOP EXIT WHEN(XMEM(XMEM(CUR_XREF).XLINK_FIELD).NUM_FIELD<=FLAG)OR(XMEM(
XMEM(CUR_XREF).XLINK_FIELD).NUM_FIELD/=XMEM(CUR_XREF).NUM_FIELD);
CUR_XREF:=XMEM(CUR_XREF).XLINK_FIELD;COUNT:=COUNT+1;END LOOP;
FIRST_XREF:=XMEM(CUR_XREF).XLINK_FIELD;
IF XMEM(FIRST_XREF).NUM_FIELD>FLAG THEN IF OUT_PTR=LINE_LENGTH THEN
BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=115;END IF;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=126;LOOP OUT_MOD(XMEM(CUR_XREF).NUM_FIELD-FLAG,COUNT);
CUR_XREF:=XMEM(CUR_XREF).XLINK_FIELD;
EXIT WHEN XMEM(CUR_XREF).NUM_FIELD<=FLAG;NEXT_XREF:=CUR_XREF;COUNT:=1;
LOOP EXIT WHEN(XMEM(XMEM(CUR_XREF).XLINK_FIELD).NUM_FIELD<=FLAG)OR(XMEM(
XMEM(CUR_XREF).XLINK_FIELD).NUM_FIELD/=XMEM(CUR_XREF).NUM_FIELD);
CUR_XREF:=XMEM(CUR_XREF).XLINK_FIELD;COUNT:=COUNT+1;END LOOP;
IF(XMEM(XMEM(CUR_XREF).XLINK_FIELD).NUM_FIELD>FLAG)OR(NEXT_XREF/=
FIRST_XREF)THEN IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=44;END IF;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=32;
IF XMEM(XMEM(CUR_XREF).XLINK_FIELD).NUM_FIELD<=FLAG THEN IF OUT_PTR=
LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=97;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=110;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=100;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=126;END IF;END LOOP--{:280}
;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=46;END FOOTNOTE;--{:279}{304:}
PROCEDURE PHASE_II IS BEGIN--{262:}
RESET_INPUT;TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"Writing the output file...");
MODULE_COUNT:=0;COPY_LIMBO;FINISH_LINE;FLUSH_BUFFER(0,FALSE);
WHILE NOT INPUT_HAS_ENDED LOOP--{264:}
MODULE_COUNT:=MODULE_COUNT+1;--{265:}
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=92;
IF BUFFER(LOC-1)/=42 THEN IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=77;
ELSE IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=78;TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"*");
INT_NUMBER_IO.PUT(TEXT_IO.STANDARD_OUTPUT,MODULE_COUNT,1);NULL;END IF;
OUT_MOD(MODULE_COUNT);IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=46;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=32--{:265}
;SAVE_LINE:=OUT_LINE;SAVE_PLACE:=OUT_PTR;--{266:}
LOOP NEXT_CONTROL:=COPY_TEX;CASE NEXT_CONTROL IS WHEN 124=>STACK_PTR:=0;
CUR_MODE:=OUTER;OUTPUT_ADA;
WHEN 64=>IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=64;
WHEN TEX_STRING!XREF_ROMAN..XREF_RESERVED!MODULE_NAME=>LOC:=LOC-2;
NEXT_CONTROL:=GET_NEXT;
IF NEXT_CONTROL=TEX_STRING THEN IF NOT PHASE_ONE THEN TEXT_IO.NEW_LINE(
TEXT_IO.STANDARD_OUTPUT);TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,
"! TeX string should be in ADA text only");ERROR;END IF;END IF;
WHEN BEGIN_COMMENT!END_COMMENT!THIN_SPACE!MATH_BREAK!LINE_BREAK!
BIG_LINE_BREAK!NO_LINE_BREAK!JOIN!PSEUDO_SEMI=>IF NOT PHASE_ONE THEN
TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! You can't do that in TeX text");
ERROR;END IF;WHEN OTHERS=>NULL;END CASE;EXIT WHEN NEXT_CONTROL>=FORMAT;
END LOOP--{:266}
;--{267:}
IF NEXT_CONTROL<=DEFINITION THEN IF(SAVE_LINE/=OUT_LINE)OR(SAVE_PLACE/=
OUT_PTR)THEN IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=92;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=89;END IF;SAVE_LINE:=OUT_LINE;SAVE_PLACE:=OUT_PTR;
END IF;WHILE NEXT_CONTROL<=DEFINITION LOOP STACK_PTR:=0;CUR_MODE:=OUTER;
IF NEXT_CONTROL=DEFINITION THEN--{269:}
TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=BACKUP;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=92;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=68;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PDOLLAR;
TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=MATH;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;NEXT_CONTROL:=GET_NEXT;
IF NEXT_CONTROL/=IDENTIFIER THEN IF NOT PHASE_ONE THEN TEXT_IO.NEW_LINE(
TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Improper macro definition");
ERROR;END IF;ELSE TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=ID_FLAG+ID_LOOKUP(NORMAL);TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;
CAT(SCRAP_PTR):=MATH;TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;END IF;NEXT_CONTROL:=GET_NEXT--{:269}
;ELSE--{270:}
TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=BACKUP;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=92;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=70;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PDOLLAR;
TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=MATH;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;NEXT_CONTROL:=GET_NEXT;
IF NEXT_CONTROL=IDENTIFIER THEN TOK_MEM(TOK_PTR):=PDOLLAR;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=ID_FLAG+ID_LOOKUP(NORMAL);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=MATH;TRANS(SCRAP_PTR):=TEXT_PTR;
TEXT_PTR:=TEXT_PTR+1;TOK_START(TEXT_PTR):=TOK_PTR;
NEXT_CONTROL:=GET_NEXT;
IF NEXT_CONTROL=EQUIVALENCE_SIGN THEN TOK_MEM(TOK_PTR):=92;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=83;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=MATH;TRANS(SCRAP_PTR):=TEXT_PTR;
TEXT_PTR:=TEXT_PTR+1;TOK_START(TEXT_PTR):=TOK_PTR;
NEXT_CONTROL:=GET_NEXT;
IF NEXT_CONTROL=IDENTIFIER THEN TOK_MEM(TOK_PTR):=PDOLLAR;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=ID_FLAG+ID_LOOKUP(NORMAL);
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=PDOLLAR;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=MATH;TRANS(SCRAP_PTR):=TEXT_PTR;
TEXT_PTR:=TEXT_PTR+1;TOK_START(TEXT_PTR):=TOK_PTR;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=SEMI;TRANS(SCRAP_PTR):=0;
NEXT_CONTROL:=GET_NEXT;END IF;END IF;END IF;
IF SCRAP_PTR/=5 THEN IF NOT PHASE_ONE THEN TEXT_IO.NEW_LINE(TEXT_IO.
STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Improper format definition");
ERROR;END IF;END IF--{:270}
;END IF;OUTER_PARSE;FINISH_ADA;END LOOP--{:267}
;--{272:}
THIS_MODULE:=0;
IF NEXT_CONTROL<=MODULE_NAME THEN IF(SAVE_LINE/=OUT_LINE)OR(SAVE_PLACE/=
OUT_PTR)THEN IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=92;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=89;END IF;STACK_PTR:=0;CUR_MODE:=OUTER;
IF NEXT_CONTROL=BEGIN_ADA THEN NEXT_CONTROL:=GET_NEXT;
ELSE THIS_MODULE:=CUR_MODULE;--{273:}
LOOP NEXT_CONTROL:=GET_NEXT;EXIT WHEN NEXT_CONTROL/=43;END LOOP;
IF(NEXT_CONTROL/=61)AND(NEXT_CONTROL/=EQUIVALENCE_SIGN)THEN IF NOT
PHASE_ONE THEN TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,
"! You need an = sign after the section name");ERROR;END IF;
ELSE NEXT_CONTROL:=GET_NEXT;END IF;
IF(OUT_PTR>1)AND THEN(OUT_BUF(OUT_PTR-1..OUT_PTR)=(92,89))THEN TOK_MEM(
TOK_PTR):=BACKUP;TOK_PTR:=TOK_PTR+1;END IF;
TOK_MEM(TOK_PTR):=MOD_FLAG+THIS_MODULE;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=MOD_SCRAP;
TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;CUR_XREF:=XREF(THIS_MODULE);
IF XMEM(CUR_XREF).NUM_FIELD/=MODULE_COUNT+DEF_FLAG THEN TOK_MEM(TOK_PTR)
:=MATH_REL;TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=43;TOK_PTR:=TOK_PTR+1;
TOK_MEM(TOK_PTR):=125;TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;
CAT(SCRAP_PTR):=MATH;TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR;THIS_MODULE:=0;END IF;TOK_MEM(TOK_PTR):=92;
TOK_PTR:=TOK_PTR+1;TOK_MEM(TOK_PTR):=83;TOK_PTR:=TOK_PTR+1;
SCRAP_PTR:=SCRAP_PTR+1;CAT(SCRAP_PTR):=MATH;TRANS(SCRAP_PTR):=TEXT_PTR;
TEXT_PTR:=TEXT_PTR+1;TOK_START(TEXT_PTR):=TOK_PTR;
TOK_MEM(TOK_PTR):=FORCE;TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;
CAT(SCRAP_PTR):=SEMI;TRANS(SCRAP_PTR):=TEXT_PTR;TEXT_PTR:=TEXT_PTR+1;
TOK_START(TEXT_PTR):=TOK_PTR--{:273}
;END IF;WHILE NEXT_CONTROL<=MODULE_NAME LOOP OUTER_PARSE;--{274:}
IF NEXT_CONTROL<MODULE_NAME THEN IF NOT PHASE_ONE THEN TEXT_IO.NEW_LINE(
TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! You can't do that in ADA text");
ERROR;END IF;NEXT_CONTROL:=GET_NEXT;
ELSIF NEXT_CONTROL=MODULE_NAME THEN TOK_MEM(TOK_PTR):=MOD_FLAG+
CUR_MODULE;TOK_PTR:=TOK_PTR+1;SCRAP_PTR:=SCRAP_PTR+1;
CAT(SCRAP_PTR):=MOD_SCRAP;TRANS(SCRAP_PTR):=TEXT_PTR;
TEXT_PTR:=TEXT_PTR+1;TOK_START(TEXT_PTR):=TOK_PTR;
NEXT_CONTROL:=GET_NEXT;END IF--{:274}
;END LOOP;FINISH_ADA;END IF--{:272}
;--{275:}
IF THIS_MODULE>0 THEN--{277:}
FIRST_XREF:=XREF(THIS_MODULE);THIS_XREF:=XMEM(FIRST_XREF).XLINK_FIELD;
IF XMEM(THIS_XREF).NUM_FIELD>DEF_FLAG THEN MID_XREF:=THIS_XREF;
CUR_XREF:=0;LOOP NEXT_XREF:=XMEM(THIS_XREF).XLINK_FIELD;
XMEM(THIS_XREF).XLINK_FIELD:=CUR_XREF;CUR_XREF:=THIS_XREF;
THIS_XREF:=NEXT_XREF;EXIT WHEN XMEM(THIS_XREF).NUM_FIELD<=DEF_FLAG;
END LOOP;XMEM(FIRST_XREF).XLINK_FIELD:=CUR_XREF;ELSE MID_XREF:=0;END IF;
CUR_XREF:=0;
WHILE THIS_XREF/=0 LOOP NEXT_XREF:=XMEM(THIS_XREF).XLINK_FIELD;
XMEM(THIS_XREF).XLINK_FIELD:=CUR_XREF;CUR_XREF:=THIS_XREF;
THIS_XREF:=NEXT_XREF;END LOOP;
IF MID_XREF>0 THEN XMEM(MID_XREF).XLINK_FIELD:=CUR_XREF;
ELSE XMEM(FIRST_XREF).XLINK_FIELD:=CUR_XREF;END IF;
CUR_XREF:=XMEM(FIRST_XREF).XLINK_FIELD--{:277}
;FOOTNOTE(DEF_FLAG);FOOTNOTE(0);END IF--{:275}
;--{281:}
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=92;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=102;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=105;FINISH_LINE;FLUSH_BUFFER(0,FALSE)--{:281}{:264}
;END LOOP--{:262}
;END PHASE_II;--{:304}
END SECOND_PHASE;--{:10}{11:}
