WITH DATA_STRUCTURES;USE DATA_STRUCTURES;PACKAGE SECOND_PHASE IS--{244:}
PROCEDURE PUSH_LEVEL(P:TEXT_POINTER);--{:244}{249:}
PROCEDURE MAKE_OUTPUT;--{:249}{278:}
PROCEDURE FOOTNOTE(FLAG:SIXTEEN_BITS);--{:278}{303:}
PROCEDURE PHASE_II;--{:303}
END SECOND_PHASE;
