WITH TEXT_IO,INT_NUMBER_IO;WITH INPUT_OUTPUT;USE INPUT_OUTPUT;
WITH OUTPUT;USE OUTPUT;WITH SECOND_PHASE;USE SECOND_PHASE;
PACKAGE BODY THIRD_PHASE IS--{291:}
PROCEDURE UNBUCKET(D:EIGHT_BITS)IS BEGIN FOR F IN REVERSE 0..100 LOOP IF
BUCKET(COLLATE(F))>0 THEN IF SORT_PTR>MAX_SORTS THEN TEXT_IO.NEW_LINE(
TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"! Sorry, "&"sorting"&
" capacity exceeded");ERROR;HISTORY:=FATAL_MESSAGE;RAISE END_OF_AWEAVE;
END IF;SORT_PTR:=SORT_PTR+1;
--IF SORT_PTR>MAX_SORT_PTR THEN MAX_SORT_PTR:=SORT_PTR;END IF;
IF F=0 THEN DEPTH(SORT_PTR):=INFINITY;ELSE DEPTH(SORT_PTR):=D;END IF;
HEAD(SORT_PTR):=BUCKET(COLLATE(F));BUCKET(COLLATE(F)):=0;END IF;
END LOOP;END UNBUCKET;--{:291}{299:}
PROCEDURE MOD_PRINT(P:NAME_POINTER)IS BEGIN IF P>0 THEN MOD_PRINT(LLINK(
P));IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=92;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=58;TOK_PTR:=1;TEXT_PTR:=1;
SCRAP_PTR:=0;STACK_PTR:=0;CUR_MODE:=OUTER;TOK_MEM(TOK_PTR):=P+MOD_FLAG;
TOK_PTR:=TOK_PTR+1;MAKE_OUTPUT;FOOTNOTE(0);FINISH_LINE;
MOD_PRINT(RLINK(P));END IF;END MOD_PRINT;--{:299}{306:}
PROCEDURE PHASE_III IS BEGIN--{282:}
PHASE_THREE:=TRUE;TEXT_IO.NEW_LINE(TEXT_IO.STANDARD_OUTPUT);
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"Writing the index...");
IF CHANGE_EXISTS THEN FINISH_LINE;--{284:}
K_MODULE:=1;WHILE NOT CHANGED_MODULE(K_MODULE)LOOP K_MODULE:=K_MODULE+1;
END LOOP;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=92;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=99;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=104;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=32;OUT_MOD(K_MODULE);LOOP LOOP K_MODULE:=K_MODULE+1;
EXIT WHEN CHANGED_MODULE(K_MODULE);END LOOP;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=44;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=32;OUT_MOD(K_MODULE);
EXIT WHEN K_MODULE=MODULE_COUNT;END LOOP;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=46--{:284}
;END IF;FINISH_LINE;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=92;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=105;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=110;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=120;FINISH_LINE;--{286:}
FOR D IN INTEGER RANGE 0..127 LOOP BUCKET(D):=0;END LOOP;
FOR H IN INTEGER RANGE 0..HASH_SIZE-1 LOOP NEXT_NAME:=HASH(H);
WHILE NEXT_NAME/=0 LOOP CUR_NAME:=NEXT_NAME;NEXT_NAME:=LINK(CUR_NAME);
IF XREF(CUR_NAME)/=0 THEN C:=BYTE_MEM(CUR_NAME MOD WW,BYTE_START(
CUR_NAME));IF(C<=90)AND(C>=65)THEN C:=C+8#40#;END IF;
BLINK(CUR_NAME):=BUCKET(C);BUCKET(C):=CUR_NAME;END IF;END LOOP;END LOOP
--{:286}
;--{292:}
SORT_PTR:=0;UNBUCKET(1);
WHILE SORT_PTR>0 LOOP CUR_DEPTH:=DEPTH(SORT_PTR);
IF(BLINK(HEAD(SORT_PTR))=0)OR(CUR_DEPTH=INFINITY)THEN--{294:}
CUR_NAME:=HEAD(SORT_PTR);LOOP IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;
END IF;OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=92;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=58;--{295:}
CASE ILK(CUR_NAME)IS WHEN NORMAL=>IF BYTE_START(CUR_NAME+WW)-BYTE_START(
CUR_NAME)=1 THEN IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=92;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=124;ELSE IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=92;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=92;END IF;WHEN ROMAN=>NULL;
WHEN WILDCARD=>IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=92;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=57;WHEN ITALIC=>IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;
END IF;OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=92;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=92;
WHEN SLANTED=>IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=92;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=115;
WHEN PREDEFINED=>IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=92;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=112;
WHEN TYPEWRITER=>IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=92;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=46;WHEN OTHERS=>IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;
END IF;OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=92;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=38;END CASE;OUT_NAME(CUR_NAME)--{:295}
;--{296:}{297:}
THIS_XREF:=XREF(CUR_NAME);CUR_XREF:=0;
LOOP NEXT_XREF:=XMEM(THIS_XREF).XLINK_FIELD;
XMEM(THIS_XREF).XLINK_FIELD:=CUR_XREF;CUR_XREF:=THIS_XREF;
THIS_XREF:=NEXT_XREF;EXIT WHEN THIS_XREF=0;END LOOP--{:297}
;WHILE CUR_XREF/=0 LOOP IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=44;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=32;CUR_VAL:=XMEM(CUR_XREF).NUM_FIELD;
THIS_XREF:=CUR_XREF;
IF CUR_VAL<DEF_FLAG THEN NEXT_XREF:=XMEM(THIS_XREF).XLINK_FIELD;
WHILE(NEXT_XREF/=0)AND THEN((XMEM(NEXT_XREF).NUM_FIELD<DEF_FLAG)AND(XMEM
(THIS_XREF).NUM_FIELD=(XMEM(NEXT_XREF).NUM_FIELD-1)))LOOP THIS_XREF:=
NEXT_XREF;NEXT_XREF:=XMEM(THIS_XREF).XLINK_FIELD;END LOOP;
OUT_MOD(CUR_VAL);
IF CUR_XREF/=THIS_XREF THEN IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;
END IF;OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=45;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=45;OUT_MOD(XMEM(THIS_XREF).NUM_FIELD);END IF;
ELSIF CUR_VAL<BODY_FLAG THEN IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;
END IF;OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=92;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=91;OUT_MOD(CUR_VAL-DEF_FLAG);
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=93;ELSE IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=92;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=92;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=123;OUT_MOD(CUR_VAL-BODY_FLAG);
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=125;END IF;CUR_XREF:=XMEM(THIS_XREF).XLINK_FIELD;
END LOOP;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=46;FINISH_LINE--{:296}
;CUR_NAME:=BLINK(CUR_NAME);EXIT WHEN CUR_NAME=0;END LOOP;
SORT_PTR:=SORT_PTR-1--{:294}
;ELSE--{293:}
NEXT_NAME:=HEAD(SORT_PTR);LOOP CUR_NAME:=NEXT_NAME;
NEXT_NAME:=BLINK(CUR_NAME);CUR_BYTE:=BYTE_START(CUR_NAME)+CUR_DEPTH;
CUR_BANK:=CUR_NAME MOD WW;IF CUR_BYTE=BYTE_START(CUR_NAME+WW)THEN C:=0;
ELSE C:=BYTE_MEM(CUR_BANK,CUR_BYTE);IF(C<=90)AND(C>=65)THEN C:=C+8#40#;
END IF;END IF;BLINK(CUR_NAME):=BUCKET(C);BUCKET(C):=CUR_NAME;
EXIT WHEN NEXT_NAME=0;END LOOP;SORT_PTR:=SORT_PTR-1;
UNBUCKET(CUR_DEPTH+1)--{:293}
;END IF;END LOOP--{:292}
;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=92;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=102;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=105;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=110;FINISH_LINE;--{300:}
MOD_PRINT(ROOT)--{:300}
;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=92;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=99;
IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;OUT_PTR:=OUT_PTR+1;
OUT_BUF(OUT_PTR):=111;IF OUT_PTR=LINE_LENGTH THEN BREAK_OUT;END IF;
OUT_PTR:=OUT_PTR+1;OUT_BUF(OUT_PTR):=110;FINISH_LINE;
TEXT_IO.PUT(TEXT_IO.STANDARD_OUTPUT,"Done.")--{:282}
;END PHASE_III;--{:306}
END THIRD_PHASE;--{:11}{176:}
